export type CorrectiveActionSeverity = "LOW" | "MODERATE" | "HIGH" | "CRITICAL";
export type CorrectiveActionRisk = "LOW" | "MEDIUM" | "HIGH" | "VERY_HIGH" | "CRITICAL" | "EXTREME";
export type CorrectiveActionPriority = "LOW" | "NORMAL" | "HIGH" | "URGENT";
export type CorrectiveActionStatus = "DRAFT" | "OPEN" | "ASSIGNED" | "IN_PROGRESS" | "ON_HOLD" | "AWAITING_EVIDENCE" | "AWAITING_VERIFICATION" | "REINSPECTION_REQUIRED" | "REOPENED" | "CLOSED" | "CANCELLED" | "ARCHIVED";
export type CorrectiveActionSource = "MANUAL" | "WORK_ORDER" | "SAFETY_INSPECTION" | "PLANNED_MAINTENANCE" | "CLEANING_TASK" | "HOUSEKEEPING_INSPECTION" | "ROOM_READINESS" | "ASSET" | "ROOM" | "BED" | "CONTRACTOR" | "CERTIFICATE" | "COMPLIANCE" | "AUDIT" | "INCIDENT" | "DOCUMENT" | "SAFETY" | "OTHER";
export type CorrectiveActionEvidenceStatus = "MISSING" | "RECEIVED" | "VERIFIED";
export type CorrectiveActionVerificationResult = "APPROVED" | "REJECTED" | "MORE_EVIDENCE_REQUIRED" | "REINSPECTION_REQUIRED";
export type CorrectiveActionReinspectionResult = "PASSED" | "FAILED" | "PARTIALLY_PASSED" | "FURTHER_WORK_REQUIRED";

export interface CorrectiveActionCategory { id: string; tenantId: string; homeId: string; name: string; description?: string; colour: string; isActive: boolean; sortOrder: number; createdAt: string; updatedAt: string; }
export interface CorrectiveActionEvidence { id: string; type: string; description: string; documentReference?: string; mandatory: boolean; status: CorrectiveActionEvidenceStatus; addedByUserId: string; addedAt: string; verifiedByUserId?: string; verifiedAt?: string; }
export interface CorrectiveActionVerification { id: string; cycle: number; result: CorrectiveActionVerificationResult; comments: string; verifiedByUserId: string; verifiedAt: string; evidenceReviewed: string[]; }
export interface CorrectiveActionReinspection { id: string; result: CorrectiveActionReinspectionResult; comments: string; reinspectedByUserId: string; reinspectedAt: string; sourceInspectionId?: string; }
export interface CorrectiveActionClosure { id: string; summary: string; closedByUserId: string; closedAt: string; residualRisk?: CorrectiveActionRisk; preventiveMeasures?: string; lessonsLearned?: string; }
export interface CorrectiveActionReopen { id: string; reason: string; reopenedByUserId: string; reopenedAt: string; newDueDate: string; previousClosureId?: string; }
export interface CorrectiveActionNote { id: string; type: string; text: string; authorUserId: string; createdAt: string; attachmentReference?: string; }

export interface CorrectiveAction {
  id: string; tenantId: string; homeId: string; referenceNumber: string; title: string; description: string; categoryId: string;
  severity: CorrectiveActionSeverity; riskLevel: CorrectiveActionRisk; priority: CorrectiveActionPriority; status: CorrectiveActionStatus;
  responsiblePersonId?: string; responsibleTeamId?: string; responsibleContractorId?: string; escalationOwnerId?: string;
  contractorComplianceSnapshot?: { state: string; checkedAt: string; checkedBy: string; blockers: string[]; warnings: string[] };
  createdByUserId: string; updatedByUserId: string; dateIdentified?: string; dueDate?: string; reviewDate?: string; verificationDueDate?: string; reinspectionDate?: string; completedDate?: string; closedDate?: string;
  sourceType: CorrectiveActionSource; sourceReferenceId?: string; sourceIssueId?: string; sourceInspectionId?: string; sourceInspectionNumber?: string; sourceFailedResponseId?: string;
  assetId?: string; locationId?: string; roomId?: string; bedId?: string; contractorId?: string; certificateId?: string;
  requiredAction?: string; immediateRisk?: string; immediateControl?: string; rootCauseCategory?: string; rootCauseDescription?: string; contributingFactors?: string; preventiveAction?: string; recurrenceRisk?: string;
  evidenceRequirements?: string[]; evidenceReferences?: string[]; evidence?: CorrectiveActionEvidence[]; verificationRequired?: boolean; verifications?: CorrectiveActionVerification[]; reinspectionRequired?: boolean; reinspections?: CorrectiveActionReinspection[];
  linkedWorkOrderIds?: string[]; linkedPlannedMaintenanceIds?: string[]; linkedInspectionIds?: string[]; linkedCleaningTaskIds?: string[]; linkedRoomReadinessIds?: string[];
  notes?: CorrectiveActionNote[]; closures?: CorrectiveActionClosure[]; reopenHistory?: CorrectiveActionReopen[];
  completionSummary?: string; cancellationReason?: string; holdReason?: string; holdCategory?: string; expectedResumeDate?: string;
  archived?: boolean; archivedAt?: string; archivedByUserId?: string; version: number; createdAt: string; updatedAt: string; deletedAt?: string;
}

export const correctiveActionPriorityFor = (severity: CorrectiveActionSeverity): CorrectiveActionPriority => severity === "CRITICAL" ? "URGENT" : severity === "HIGH" ? "HIGH" : "NORMAL";
export const CORRECTIVE_ACTION_SLA_DAYS: Record<CorrectiveActionSeverity, number> = { CRITICAL: 1, HIGH: 3, MODERATE: 7, LOW: 30 };
export function suggestCorrectiveActionDueDate(severity: CorrectiveActionSeverity, identified = new Date().toISOString().slice(0, 10), sla = CORRECTIVE_ACTION_SLA_DAYS) { const result = new Date(`${identified}T12:00:00`); result.setDate(result.getDate() + sla[severity]); return result.toISOString().slice(0, 10); }
export const correctiveActionIsOverdue = (item: CorrectiveAction, today = new Date().toISOString().slice(0, 10)) => Boolean(item.dueDate && item.dueDate < today && !["CLOSED", "CANCELLED", "ARCHIVED"].includes(item.status));
export const correctiveActionDaysOverdue = (item: CorrectiveAction, today = new Date().toISOString().slice(0, 10)) => correctiveActionIsOverdue(item, today) ? Math.max(1, Math.floor((Date.parse(`${today}T12:00:00`) - Date.parse(`${item.dueDate}T12:00:00`)) / 86400000)) : 0;
export const mandatoryEvidenceComplete = (item: CorrectiveAction) => (item.evidenceRequirements || []).every((requirement) => (item.evidence || []).some((evidence) => evidence.mandatory && evidence.description === requirement && evidence.status !== "MISSING"));
export const latestVerificationApproved = (item: CorrectiveAction) => !item.verificationRequired || item.verifications?.at(-1)?.result === "APPROVED";
export const latestReinspectionPassed = (item: CorrectiveAction) => !item.reinspectionRequired || item.reinspections?.at(-1)?.result === "PASSED";
export function correctiveActionClosureBlockers(item: CorrectiveAction, workOrders: Record<string, string | { status: string; reference?: string }> = {}) { const blockers: string[] = []; if (!item.completionSummary?.trim()) blockers.push("Completion summary has not been added"); for (const requirement of item.evidenceRequirements || []) { if (!(item.evidence || []).some((evidence) => evidence.description === requirement && evidence.status !== "MISSING")) blockers.push(`Required ${requirement.toLowerCase()} is missing`); } if (!latestVerificationApproved(item)) blockers.push("Independent verification has not been completed"); if (!latestReinspectionPassed(item)) blockers.push("Reinspection has not passed"); for (const id of item.linkedWorkOrderIds || []) { const record = workOrders[id]; const status = typeof record === "string" ? record : record?.status || ""; const reference = typeof record === "string" ? id : record?.reference || id; if (!["COMPLETED", "CLOSED"].includes(status)) blockers.push(`Work Order ${reference} is still ${status ? status.toLowerCase().replaceAll("_", " ") : "open"}`); } return blockers; }
export function correctiveActionSourceKey(input: Pick<CorrectiveAction, "homeId" | "sourceType" | "sourceReferenceId" | "sourceIssueId" | "sourceFailedResponseId">) { return [input.homeId, input.sourceType, input.sourceReferenceId || "", input.sourceIssueId || input.sourceFailedResponseId || ""].join("|"); }
export function findDuplicateCorrectiveAction(input: Pick<CorrectiveAction, "homeId" | "sourceType" | "sourceReferenceId" | "sourceIssueId" | "sourceFailedResponseId">, actions: CorrectiveAction[]) { if (input.sourceType === "MANUAL" || !input.sourceReferenceId) return undefined; const key = correctiveActionSourceKey(input); return actions.find((item) => !item.deletedAt && correctiveActionSourceKey(item) === key); }
export const allowedCorrectiveActionTransitions: Record<CorrectiveActionStatus, CorrectiveActionStatus[]> = {
  DRAFT: ["OPEN", "CANCELLED"], OPEN: ["ASSIGNED", "IN_PROGRESS", "ON_HOLD", "CANCELLED"], ASSIGNED: ["IN_PROGRESS", "ON_HOLD", "CANCELLED"], IN_PROGRESS: ["ON_HOLD", "AWAITING_EVIDENCE", "AWAITING_VERIFICATION", "REINSPECTION_REQUIRED", "CANCELLED"], ON_HOLD: ["IN_PROGRESS", "CANCELLED"], AWAITING_EVIDENCE: ["IN_PROGRESS", "AWAITING_VERIFICATION", "CANCELLED"], AWAITING_VERIFICATION: ["IN_PROGRESS", "AWAITING_EVIDENCE", "REINSPECTION_REQUIRED", "CLOSED"], REINSPECTION_REQUIRED: ["IN_PROGRESS", "AWAITING_VERIFICATION", "CLOSED"], REOPENED: ["IN_PROGRESS", "ON_HOLD", "AWAITING_EVIDENCE", "AWAITING_VERIFICATION", "REINSPECTION_REQUIRED", "CANCELLED"], CLOSED: ["REOPENED", "ARCHIVED"], CANCELLED: ["ARCHIVED"], ARCHIVED: []
};
export const defaultCorrectiveActionCategories = (homeId: string): CorrectiveActionCategory[] => ["Safety Failure", "Cleaning Failure", "Asset or Equipment", "Fire Safety", "Infection Control", "Water Safety", "Electrical Safety", "Room or Bed Blocked", "Contractor Compliance", "Certificate or Document", "Work Order Follow-Up", "Audit Finding", "Incident Follow-Up", "Documentation Gap", "Repeated Failure", "General"].map((name, index) => ({ id: `ca-category-${index + 1}`, tenantId: "tenant-oritas-demo", homeId, name, colour: ["#dc2626", "#ea580c", "#0284c7", "#7c3aed", "#059669"][index % 5], isActive: true, sortOrder: index + 1, createdAt: "2026-01-01T09:00:00.000Z", updatedAt: "2026-01-01T09:00:00.000Z" }));

export function correctiveActionDashboard(actions: CorrectiveAction[], today = new Date().toISOString().slice(0, 10)) { const active = actions.filter((item) => !item.archived && !["CLOSED", "CANCELLED", "ARCHIVED"].includes(item.status)); return { open: active.length, overdue: active.filter((item) => correctiveActionIsOverdue(item, today)).length, highRisk: active.filter((item) => ["HIGH", "VERY_HIGH", "CRITICAL", "EXTREME"].includes(item.riskLevel)).length, critical: active.filter((item) => item.severity === "CRITICAL" || ["CRITICAL", "EXTREME"].includes(item.riskLevel)).length, awaitingEvidence: active.filter((item) => item.status === "AWAITING_EVIDENCE" || !mandatoryEvidenceComplete(item)).length, awaitingVerification: active.filter((item) => item.status === "AWAITING_VERIFICATION").length, reinspectionRequired: active.filter((item) => item.status === "REINSPECTION_REQUIRED").length, reopened: active.filter((item) => item.status === "REOPENED").length, unassigned: active.filter((item) => !item.responsiblePersonId && !item.responsibleTeamId && !item.responsibleContractorId).length, dueToday: active.filter((item) => item.dueDate === today).length }; }
export function correctiveActionWorkProjection(item: CorrectiveAction) { return { id: item.id, reference: item.referenceNumber, workType: "Corrective Action" as const, title: item.title, nursingHomeId: item.homeId, locationId: item.assetId || item.roomId || item.bedId || item.locationId, assignedTo: item.responsiblePersonId || item.responsibleTeamId || item.responsibleContractorId, dueDate: item.dueDate, risk: item.riskLevel, status: item.status, source: item.sourceType, primaryAction: "Open action", route: `/maintenance/corrective-actions/${item.id}` }; }
