export type MaintenanceReportCategory = "Operations" | "Planned Maintenance" | "Safety & Compliance" | "Housekeeping" | "Assets, Rooms & Beds" | "Contractors & Certificates" | "Corrective Actions" | "Costs" | "Evidence Packs" | "Scheduled Reports";
export type MaintenanceReportSource = "workOrders" | "planned" | "safety" | "housekeeping" | "assets" | "occupancy" | "contractors" | "certificates" | "correctiveActions" | "costs";
export type MaintenanceReportFormat = "PDF" | "Excel" | "CSV";
export interface MaintenanceReportDefinition { key:string; name:string; category:MaintenanceReportCategory; description:string; source:MaintenanceReportSource; keywords:string[]; formats:MaintenanceReportFormat[]; common?:boolean; availability?:"AVAILABLE"|"NOT_YET_AVAILABLE"; }
export interface MaintenanceReportFilters { homeId:string; status?:string; datePreset?:string; from?:string; to?:string; archived?:boolean; }
export interface SavedMaintenanceReport { id:string; reportKey:string; name:string; description?:string; filters:MaintenanceReportFilters; sort?:string; columns:string[]; outputFormat:MaintenanceReportFormat; ownerUserId:string; sharedUserIds:string[]; sharedRoleIds:string[]; sharedTeamIds:string[]; sharedHomeIds:string[]; createdAt:string; updatedAt:string; }
export interface ScheduledMaintenanceReport { id:string; savedReportId:string; name:string; frequency:"DAILY"|"WEEKLY"|"MONTHLY"|"QUARTERLY"|"CUSTOM"; day?:string; time:string; outputFormat:MaintenanceReportFormat; recipientUserIds:string[]; recipientRoleIds:string[]; homeId:string; includeEmpty:boolean; active:boolean; startDate:string; endDate?:string; ownerUserId:string; createdAt:string; }
export interface MaintenanceReportRecent { reportKey:string; runAt:string; filters:MaintenanceReportFilters; outputFormat:MaintenanceReportFormat; resultCount:number; }

const formats: MaintenanceReportFormat[]=["PDF","Excel","CSV"];
const d=(key:string,name:string,category:MaintenanceReportCategory,description:string,source:MaintenanceReportSource,keywords:string[]=[],common=false):MaintenanceReportDefinition=>({key,name,category,description,source,keywords,formats,common,availability:"AVAILABLE"});
export const MAINTENANCE_REPORTS:MaintenanceReportDefinition[]=[
 d("work-order-register","Work Order Register","Operations","All Work Orders with ownership, priority, due date and status.","workOrders",["work","register"],true),d("open-work-orders","Open Work Orders","Operations","Work that still requires action.","workOrders",["open","unassigned"],true),d("overdue-work-orders","Overdue Work Orders","Operations","Active Work Orders past their due date.","workOrders",["overdue","late"],true),d("critical-work","Critical Work","Operations","Critical operational and safety work.","workOrders",["critical","risk"]),d("unassigned-work","Unassigned Work","Operations","Work without a responsible owner.","workOrders",["unassigned"]),d("work-awaiting-verification","Work Awaiting Verification","Operations","Completed work awaiting approval.","workOrders",["verification"]),
 d("planned-schedule","Planned Maintenance Schedule","Planned Maintenance","Planned schedules and future obligations.","planned",["calendar","future"],true),d("planned-overdue","Planned Work Overdue","Planned Maintenance","Planned occurrences that missed their due date.","planned",["overdue","missed"],true),d("planned-completion","Planned Work Completion","Planned Maintenance","Completion and on-time performance.","planned",["completion","on time"]),d("paused-schedules","Paused Schedules","Planned Maintenance","Schedules currently paused.","planned",["paused"]),
 d("safety-register","Safety Inspection Register","Safety & Compliance","Inspection status, results and source references.","safety",["inspection","fire","water"],true),d("failed-safety","Failed Safety Checks","Safety & Compliance","Failed checks requiring action.","safety",["failed","risk"],true),d("safety-overdue","Safety Checks Overdue","Safety & Compliance","Safety checks past their due date.","safety",["overdue"]),d("safety-reinspection","Reinspection Required","Safety & Compliance","Failures requiring a new inspection.","safety",["reinspection"]),
 d("cleaning-register","Cleaning Task Register","Housekeeping","Cleaning tasks and completion status.","housekeeping",["cleaning","task"],true),d("cleaning-overdue","Cleaning Overdue","Housekeeping","Cleaning tasks past their due time.","housekeeping",["overdue"]),d("cleaning-failed","Cleaning Failed","Housekeeping","Failed cleaning and exceptions.","housekeeping",["failed","exception"]),d("room-readiness","Room Readiness","Housekeeping","Current readiness and blocked rooms.","housekeeping",["room","ready"],true),
 d("asset-register","Asset Register","Assets, Rooms & Beds","Asset condition, location and operational status.","assets",["asset","equipment"],true),d("assets-out-of-service","Assets Out of Service","Assets, Rooms & Beds","Assets unavailable for operational use.","assets",["blocked","maintenance"]),d("room-register","Room Register","Assets, Rooms & Beds","Rooms and operational status.","assets",["room"]),d("current-occupancy","Current Occupancy","Assets, Rooms & Beds","Registered and operational occupancy using shared calculations.","occupancy",["beds","capacity","occupancy"],true),d("available-beds","Available Beds","Assets, Rooms & Beds","Beds that satisfy the shared assignability rule.","occupancy",["available","beds"]),d("blocked-beds","Blocked Beds","Assets, Rooms & Beds","Beds currently unavailable or blocked.","occupancy",["blocked","beds"]),
 d("contractor-register","Contractor Register","Contractors & Certificates","Contractor identity, approval and operational status.","contractors",["contractor"],true),d("contractor-compliance","Contractor Compliance","Contractors & Certificates","Approval and compliance by Nursing Home.","contractors",["compliance","insurance"]),d("certificate-register","Certificate Register","Contractors & Certificates","Certificate validity, expiry and verification.","certificates",["certificate"],true),d("expired-certificates","Expired Certificates","Contractors & Certificates","Expired certificates requiring action.","certificates",["expired"]),d("certificates-due-soon","Certificates Due Soon","Contractors & Certificates","Certificates approaching expiry.","certificates",["expiry","due soon"]),
 d("corrective-action-register","Corrective Action Register","Corrective Actions","All corrective actions and current accountability.","correctiveActions",["action","register"],true),d("open-corrective-actions","Open Corrective Actions","Corrective Actions","Corrective actions that remain active.","correctiveActions",["open"]),d("overdue-corrective-actions","Overdue Corrective Actions","Corrective Actions","Actions past due using the shared overdue calculation.","correctiveActions",["overdue"],true),d("high-risk-actions","High-Risk Actions","Corrective Actions","High and critical risk actions.","correctiveActions",["high","critical"]),d("awaiting-evidence","Awaiting Evidence","Corrective Actions","Actions still missing mandatory evidence.","correctiveActions",["evidence"]),d("awaiting-verification","Awaiting Verification","Corrective Actions","Actions awaiting independent verification.","correctiveActions",["verification"]),
 d("work-order-cost","Work Order Cost","Costs","Recorded Work Order labour, material and contractor costs.","costs",["cost","spend"],true),d("monthly-maintenance-spend","Monthly Maintenance Spend","Costs","Recorded maintenance expenditure by month.","costs",["monthly","budget"]),
];
export const REPORT_CATEGORY_DESCRIPTIONS:Record<MaintenanceReportCategory,string>={"Operations":"Work Orders, overdue work, ownership and completion.","Planned Maintenance":"Schedules, due work and planned completion.","Safety & Compliance":"Safety checks, failures, restrictions and reinspections.","Housekeeping":"Cleaning, quality checks and room readiness.","Assets, Rooms & Beds":"Inventory, operational status, capacity and occupancy.","Contractors & Certificates":"Provider compliance, certificates and expiry.","Corrective Actions":"Open, overdue, evidence and verification accountability.","Costs":"Recorded labour, materials and contractor expenditure.","Evidence Packs":"Structured evidence for inspections and governance reviews.","Scheduled Reports":"Saved report schedules for future backend delivery."};
export const REPORT_CATEGORIES=(Object.keys(REPORT_CATEGORY_DESCRIPTIONS) as MaintenanceReportCategory[]);
export function searchMaintenanceReports(query:string,reports=MAINTENANCE_REPORTS){const term=query.trim().toLowerCase();if(!term)return reports;return reports.filter((item)=>[item.name,item.category,item.description,item.source,...item.keywords].join(" ").toLowerCase().includes(term));}
export function maintenanceDatePreset(preset:string,today=new Date()){const end=new Date(today);const start=new Date(today);if(preset==="YESTERDAY"){start.setDate(start.getDate()-1);end.setDate(end.getDate()-1);}else if(preset==="THIS_WEEK")start.setDate(start.getDate()-((start.getDay()+6)%7));else if(preset==="LAST_30_DAYS")start.setDate(start.getDate()-29);else if(preset==="LAST_90_DAYS")start.setDate(start.getDate()-89);else if(preset==="THIS_MONTH")start.setDate(1);else if(preset==="THIS_YEAR"){start.setMonth(0);start.setDate(1);}return {from:start.toISOString().slice(0,10),to:end.toISOString().slice(0,10)};}
const STORAGE="oritas-maintenance-reports-v1";
export interface MaintenanceReportPreferences { favourites:string[]; recent:MaintenanceReportRecent[]; saved:SavedMaintenanceReport[]; scheduled:ScheduledMaintenanceReport[]; }
export function loadMaintenanceReportPreferences():MaintenanceReportPreferences{if(typeof window==="undefined")return {favourites:[],recent:[],saved:[],scheduled:[]};try{return {...{favourites:[],recent:[],saved:[],scheduled:[]},...JSON.parse(localStorage.getItem(STORAGE)||"{}")};}catch{return {favourites:[],recent:[],saved:[],scheduled:[]};}}
export function saveMaintenanceReportPreferences(value:MaintenanceReportPreferences){if(typeof window!=="undefined")localStorage.setItem(STORAGE,JSON.stringify(value));}
export function validateSavedReportAccess(report:SavedMaintenanceReport,userId:string,role:string,homeIds:string[]){const shared=report.ownerUserId===userId||report.sharedUserIds.includes(userId)||report.sharedRoleIds.includes(role);return shared&&(!report.filters.homeId||homeIds.includes(report.filters.homeId));}
export function validateSchedule(input:Partial<ScheduledMaintenanceReport>){const errors:string[]=[];if(!input.savedReportId)errors.push("Select a saved report.");if(!input.name?.trim())errors.push("Enter a schedule name.");if(!input.homeId)errors.push("Select a Nursing Home.");if(!input.time)errors.push("Select a delivery time.");if(!input.recipientUserIds?.length&&!input.recipientRoleIds?.length)errors.push("Select at least one recipient user or role.");return errors;}
