export type ServiceTrade = { id: string; tenantId: string; name: string; description?: string; category: string; active: boolean; archivedAt?: string; displayOrder: number; defaultWorkOrderCategory?: string; defaultPlannedCategory?: string; approvalRequired: boolean; requiredInsuranceTypes: string[]; requiredCertificateTypeIds: string[]; requiredDocumentTypes: string[]; nursingHomeApprovalRequired: boolean; reviewIntervalMonths?: number; internalVerificationRequired: boolean; assignmentOverridePermitted: boolean; riskClassification: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL"; updatedAt: string };
export type ContractorComplianceReview = { id: string; tenantId: string; contractorId: string; nursingHomeId?: string; reviewScope: "GLOBAL" | "NURSING_HOME"; reviewedByUserId: string; reviewedByNameSnapshot: string; reviewedAt: string; decision: "APPROVED" | "APPROVED_WITH_CONDITIONS" | "MORE_INFORMATION_REQUIRED" | "RESTRICTED" | "SUSPENDED" | "REJECTED"; complianceStatusSnapshot: string; serviceIdsReviewed: string[]; insuranceFindings: string[]; certificateFindings: string[]; missingRequirements: string[]; conditions?: string; restrictions?: string; nextReviewDate?: string; comments?: string; evidenceReferences: string[]; createdAt: string; updatedAt: string };
export type MaintenanceDocumentVersion = { id: string; versionNumber: number; fileName: string; uploadedBy: string; uploadedAt: string; effectiveDate?: string; reviewDate?: string; expiryDate?: string; notes?: string; status: "CURRENT" | "DUE_FOR_REVIEW" | "EXPIRED" | "SUPERSEDED" | "REJECTED" | "ARCHIVED"; previousVersionId?: string; replacementVersionId?: string; current: boolean };
export type MaintenanceDocumentRecord = { id: string; tenantId: string; homeId: string; reference: string; title: string; documentType: string; linkedEntityType?: string; linkedEntityId?: string; contractorId?: string; currentVersionId: string; versions: MaintenanceDocumentVersion[]; archivedAt?: string };
export type ExpiryReminder = { id: string; sourceId: string; sourceVersionId: string; expiryDate: string; thresholdDays: number; recipient: string; status: "SCHEDULED" | "SENT" | "FAILED"; scheduledAt: string; sentAt?: string };
export type ExpiryEscalation = { id: string; sourceKey: string; ruleId: string; triggeredAt: string; severity: string; actionsApplied: string[]; resolvedAt?: string; resolvedBy?: string; notes?: string; correctiveActionId?: string };

export function saveServiceTrade(rows: ServiceTrade[], input: Omit<ServiceTrade, "updatedAt">, now = new Date().toISOString()) { const duplicate = rows.find((item) => item.id !== input.id && !item.archivedAt && item.name.toLowerCase() === input.name.trim().toLowerCase()); if (duplicate) throw new Error("An active Service or Trade with this name already exists."); const row = { ...input, name: input.name.trim(), updatedAt: now }; return rows.some((item) => item.id === row.id) ? rows.map((item) => item.id === row.id ? row : item) : [...rows, row]; }
export function archiveServiceTrade(rows: ServiceTrade[], id: string, now = new Date().toISOString()) { return rows.map((item) => item.id === id ? { ...item, active: false, archivedAt: now, updatedAt: now } : item); }
export function restoreServiceTrade(rows: ServiceTrade[], id: string, now = new Date().toISOString()) { return rows.map((item) => item.id === id ? { ...item, active: true, archivedAt: undefined, updatedAt: now } : item); }
export function appendComplianceReview(rows: ContractorComplianceReview[], review: ContractorComplianceReview) { if (rows.some((item) => item.id === review.id)) return rows; if (review.decision === "APPROVED_WITH_CONDITIONS" && (!review.conditions?.trim() || !review.nextReviewDate)) throw new Error("Conditions and the next review date are required."); return [...rows, review]; }
export function contractorReviewPresentation(review?: ContractorComplianceReview) { if (!review) return "Not reviewed"; if (review.decision === "APPROVED_WITH_CONDITIONS") return "Approved with Conditions"; return review.decision.replaceAll("_", " ").toLowerCase().replace(/\b\w/g, (c) => c.toUpperCase()); }
export function uploadDocumentVersion(document: MaintenanceDocumentRecord, input: Omit<MaintenanceDocumentVersion, "id" | "versionNumber" | "status" | "current" | "previousVersionId"> & { idempotencyKey: string }, today = new Date()) { if (!input.fileName.trim()) throw new Error("Select a document file."); if (document.versions.some((item) => item.id === input.idempotencyKey)) return document; const current = document.versions.find((item) => item.id === document.currentVersionId); const next: MaintenanceDocumentVersion = { ...input, id: input.idempotencyKey, versionNumber: Math.max(0, ...document.versions.map((item) => item.versionNumber)) + 1, status: documentStatus(input, today), current: true, previousVersionId: current?.id }; return { ...document, currentVersionId: next.id, versions: [...document.versions.map((item) => item.id === current?.id ? { ...item, status: "SUPERSEDED" as const, current: false, replacementVersionId: next.id } : item), next] }; }
export function documentStatus(input: { reviewDate?: string; expiryDate?: string }, today = new Date()): MaintenanceDocumentVersion["status"] { const date = today.toISOString().slice(0, 10); if (input.expiryDate && input.expiryDate < date) return "EXPIRED"; if (input.reviewDate && input.reviewDate <= date) return "DUE_FOR_REVIEW"; return "CURRENT"; }
export function scheduleExpiryReminder(rows: ExpiryReminder[], input: Omit<ExpiryReminder, "id" | "status" | "scheduledAt">, now = new Date().toISOString()) { const id = [input.sourceId, input.sourceVersionId, input.expiryDate, input.thresholdDays, input.recipient].join(":"); if (rows.some((item) => item.id === id)) return rows; return [...rows, { ...input, id, status: "SCHEDULED", scheduledAt: now }]; }
export function triggerExpiryEscalation(rows: ExpiryEscalation[], input: Omit<ExpiryEscalation, "id" | "triggeredAt">, now = new Date().toISOString()) { const id = `${input.sourceKey}:${input.ruleId}`; if (rows.some((item) => item.id === id && !item.resolvedAt)) return rows; return [...rows, { ...input, id, triggeredAt: now }]; }
export function linkCorrectiveAction(rows: ExpiryEscalation[], escalationId: string, correctiveActionId: string) { return rows.map((item) => item.id === escalationId ? item.correctiveActionId ? item : { ...item, correctiveActionId } : item); }

const STORAGE_KEY = "oritas-phase5a-governance-v1";
export type Phase5AGovernanceData = { services: ServiceTrade[]; reviews: ContractorComplianceReview[]; documents: MaintenanceDocumentRecord[]; reminders: ExpiryReminder[]; escalations: ExpiryEscalation[] };
export const emptyPhase5AGovernance = (): Phase5AGovernanceData => ({ services: [], reviews: [], documents: [], reminders: [], escalations: [] });
export function loadPhase5AGovernance(): Phase5AGovernanceData { if (typeof window === "undefined") return emptyPhase5AGovernance(); try { return { ...emptyPhase5AGovernance(), ...JSON.parse(window.localStorage.getItem(STORAGE_KEY) || "{}") }; } catch { return emptyPhase5AGovernance(); } }
export function persistPhase5AGovernance(data: Phase5AGovernanceData) { if (typeof window !== "undefined") window.localStorage.setItem(STORAGE_KEY, JSON.stringify(data)); }
