/**
 * Client-side prototype only. Replace this repository with authenticated API,
 * database and document-storage adapters before production use. It provides no
 * server-side permissions, concurrency control, audit integrity or secure PDF distribution.
 */
export type GeneratedHandoverStatus = "draft" | "finalised" | "superseded" | "cancelled";
export interface GeneratedHandoverItem { id: string; handoverId: string; residentSectionId: string; residentId: string; sourceModule: string; sourceEntityType: string; sourceEntityId: string; sourceEventId?: string; occurredAt: string; title: string; summary: string; sectionType: string; authorName?: string; systemGenerated: boolean; manuallyAdded: boolean; important: boolean; followUpRequired: boolean; excluded: boolean; sortOrder: number; }
export interface GeneratedHandoverResidentSection { id: string; handoverId: string; residentId: string; residentName: string; preferredName?: string; room?: string; wing?: string; residentIdentifier?: string; shiftSummary: string; nextShiftNotes: string; sortOrder: number; }
export interface GeneratedHandover { id: string; referenceNumber: string; status: GeneratedHandoverStatus; shiftType: "morning" | "afternoon" | "night" | "custom"; periodFrom: string; periodTo: string; nursingHomeId: string; nursingHomeName: string; wingId?: string; wingName?: string; generatedByUserId: string; generatedByName: string; generatedByRole: string; generatedAt: string; finalisedAt?: string; versionNumber: number; supersedesHandoverId?: string; supersededByHandoverId?: string; residentIds: string[]; residentCount: number; pdfFileName?: string; createdAt: string; updatedAt: string; sections: GeneratedHandoverResidentSection[]; items: GeneratedHandoverItem[]; cancellationReason?: string; }
export interface HandoverRepository { createDraft(value: GeneratedHandover): GeneratedHandover; getById(id: string): GeneratedHandover | undefined; list(): GeneratedHandover[]; listByResident(residentId: string): GeneratedHandover[]; updateDraft(value: GeneratedHandover): GeneratedHandover; finalise(id: string): GeneratedHandover; cancel(id: string, reason: string): GeneratedHandover; }
const KEY = "oritas.generated-shift-handovers.v1";
const load = (): GeneratedHandover[] => typeof window === "undefined" ? [] : JSON.parse(window.localStorage.getItem(KEY) || "[]");
const save = (items: GeneratedHandover[]) => window.localStorage.setItem(KEY, JSON.stringify(items));
export const generatedHandoverRepository: HandoverRepository = { createDraft: (value) => { const all = [value, ...load()]; save(all); return value; }, getById: (id) => load().find(x => x.id === id), list: () => load(), listByResident: (residentId) => load().filter(x => x.residentIds.includes(residentId)), updateDraft: (value) => { if (value.status !== "draft") throw new Error("Only drafts can be edited."); const all = load().map(x => x.id === value.id ? { ...value, updatedAt: new Date().toISOString() } : x); save(all); return all.find(x => x.id === value.id)!; }, finalise: (id) => { const all = load().map(x => x.id === id && x.status === "draft" ? { ...x, status: "finalised" as const, finalisedAt: new Date().toISOString(), updatedAt: new Date().toISOString() } : x); save(all); const result = all.find(x => x.id === id); if (!result) throw new Error("Handover not found."); return result; }, cancel: (id, reason) => { if (!reason.trim()) throw new Error("A cancellation reason is required."); const all = load().map(x => x.id === id ? { ...x, status: "cancelled" as const, cancellationReason: reason, updatedAt: new Date().toISOString() } : x); save(all); return all.find(x => x.id === id)!; } };
