import { jsPDF } from "jspdf";
import { generatedHandoverRepository, type GeneratedHandover } from "./generatedHandovers";

const clean = (value: string) =>
  value
    .replace(/[^a-z0-9-]+/gi, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "");
const date = (value: string) =>
  new Intl.DateTimeFormat("en-IE", { dateStyle: "long" }).format(new Date(value));
const dateTime = (value: string) =>
  new Intl.DateTimeFormat("en-IE", { dateStyle: "medium", timeStyle: "short" }).format(
    new Date(value),
  );
const time = (value: string) =>
  new Intl.DateTimeFormat("en-IE", { hour: "2-digit", minute: "2-digit", hour12: false }).format(
    new Date(value),
  );
const titleCase = (value: string) =>
  value.replace(/_/g, " ").replace(/\b\w/g, (letter) => letter.toUpperCase());
const watermark = (handover: GeneratedHandover) =>
  handover.archived
    ? "ARCHIVED"
    : handover.status === "draft"
      ? "DRAFT"
      : handover.status === "cancelled"
        ? "CANCELLED"
        : handover.status === "superseded"
          ? "SUPERSEDED"
          : undefined;

async function logoData() {
  const response = await fetch("/oritas-favicon.png");
  if (!response.ok) throw new Error("ORITAS logo could not load.");
  const blob = await response.blob();
  return await new Promise<string>((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = () => resolve(String(reader.result));
    reader.onerror = () => reject(new Error("ORITAS logo could not load."));
    reader.readAsDataURL(blob);
  });
}

export const handoverPdfService = {
  getPdfFileName(h: GeneratedHandover) {
    return `${clean(["ORITAS-Handover", h.nursingHomeName, h.wingName, h.periodFrom.slice(0, 10), titleCase(h.shiftType), h.referenceNumber, `v${h.versionNumber}`].filter(Boolean).join("-"))}.pdf`;
  },
  async generatePdfBlob(handover: GeneratedHandover): Promise<Blob> {
    const logo = await logoData();
    const doc = new jsPDF({ format: "a4", orientation: "portrait", unit: "mm" });
    const width = 210,
      height = 297,
      left = 17,
      right = 193,
      bottom = 267;
    let y = 18;
    const ensure = (space: number, continuation?: string) => {
      if (y + space <= bottom) return;
      doc.addPage();
      y = 18;
      if (continuation) {
        doc.setFont("helvetica", "bold");
        doc.setFontSize(11);
        doc.text(`${continuation} — continued`, left, y);
        y += 9;
      }
    };
    const text = (value: string, size = 9, bold = false, indent = 0) => {
      doc.setFont("helvetica", bold ? "bold" : "normal");
      doc.setFontSize(size);
      const lines = doc.splitTextToSize(value, right - left - indent);
      ensure(lines.length * size * 0.42 + 2);
      doc.text(lines, left + indent, y);
      y += lines.length * size * 0.42 + 2;
    };
    doc.addImage(logo, "PNG", left, 12, 18, 18);
    doc.setTextColor(22, 43, 93);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(18);
    doc.text("ORITAS", 40, 20);
    doc.setFontSize(13);
    doc.text("Resident Handover", 40, 27);
    y = 39;
    doc.setTextColor(20, 20, 20);
    text(
      `${handover.nursingHomeName}${handover.wingName ? ` — ${handover.wingName}` : ""}`,
      13,
      true,
    );
    text(`${titleCase(handover.shiftType)} Handover`, 11, true);
    text(
      `Period: ${date(handover.periodFrom)}, ${time(handover.periodFrom)}–${time(handover.periodTo)}`,
    );
    text(`Generated by: ${handover.generatedByName}, ${titleCase(handover.generatedByRole)}`);
    text(`Generated: ${dateTime(handover.generatedAt)}`);
    text(
      `Reference: ${handover.referenceNumber}    Version: ${handover.versionNumber}    Status: ${handover.archived ? "Archived · " : ""}${titleCase(handover.status)}    Residents: ${handover.residentCount}`,
    );
    if (handover.correctionReason) text(`Correction reason: ${handover.correctionReason}`);
    if (handover.cancellationReason)
      text(
        `Cancellation reason: ${handover.cancellationReason}${handover.cancellationNotes ? ` — ${handover.cancellationNotes}` : ""}`,
      );
    if (handover.residentCount > 1) {
      y += 3;
      text("Handover Summary", 12, true);
      text(
        `Residents included: ${handover.residentCount}    Follow-up items: ${handover.items.filter((i) => i.followUpRequired).length}    Important items: ${handover.items.filter((i) => i.important).length}    Incidents: ${handover.items.filter((i) => i.sectionType === "Incidents and Escalations").length}`,
      );
    }
    for (const [sectionIndex, section] of handover.sections.entries()) {
      if (sectionIndex > 0 || y > 215) {
        doc.addPage();
        y = 18;
      } else y += 7;
      doc.setFillColor(235, 240, 252);
      doc.rect(left, y - 5, right - left, 12, "F");
      text(
        `${section.residentName}${section.preferredName ? ` (prefers ${section.preferredName})` : ""} — Room ${section.room || "Not recorded"}`,
        12,
        true,
      );
      const details = [
        section.wing,
        section.residentIdentifier
          ? `Resident identifier: ${section.residentIdentifier}`
          : undefined,
      ]
        .filter(Boolean)
        .join(" · ");
      if (details) text(details, 8);
      if (section.shiftSummary.trim()) {
        text("Shift Summary", 10, true);
        text(section.shiftSummary);
      }
      const items = handover.items.filter(
        (item) => item.residentSectionId === section.id && !item.excluded,
      );
      for (const group of [...new Set(items.map((item) => item.sectionType))]) {
        ensure(18, section.residentName);
        text(group, 10, true);
        for (const item of items.filter((value) => value.sectionType === group)) {
          text(`• ${time(item.occurredAt)} — ${item.title}`, 9, true, 3);
          text(item.summary, 9, false, 6);
          if (item.authorName) text(`Recorded by ${item.authorName}`, 8, false, 6);
        }
      }
      if (section.nextShiftNotes.trim()) {
        text("Follow-Up for Next Shift", 10, true);
        text(section.nextShiftNotes);
      }
    }
    const pages = doc.getNumberOfPages();
    for (let page = 1; page <= pages; page++) {
      doc.setPage(page);
      const mark = watermark(handover);
      if (mark) {
        doc.saveGraphicsState();
        doc.setTextColor(205, 210, 220);
        doc.setFontSize(42);
        doc.setFont("helvetica", "bold");
        doc.text(mark, width / 2, height / 2, { align: "center", angle: 35 });
        doc.restoreGraphicsState();
      }
      doc.setDrawColor(190);
      doc.line(left, 272, right, 272);
      doc.setTextColor(80);
      doc.setFont("helvetica", "normal");
      doc.setFontSize(7);
      doc.text(
        `Generated by ORITAS · Confidential Clinical Information · ${handover.referenceNumber} · v${handover.versionNumber}`,
        left,
        278,
      );
      doc.text(`Page ${page} of ${pages}`, right, 278, { align: "right" });
      doc.text("© ORITAS. Generated through the ORITAS Care Management Platform.", left, 283);
    }
    return doc.output("blob");
  },
  async generatePdf(handoverId: string, actor = "Current user") {
    const handover = generatedHandoverRepository.getById(handoverId);
    if (!handover) throw new Error("Handover not found.");
    const blob = await this.generatePdfBlob(handover);
    generatedHandoverRepository.savePdfMetadata(handover.id, {
      fileName: this.getPdfFileName(handover),
      generatedAt: new Date().toISOString(),
      generatedBy: actor,
      version: handover.versionNumber,
    });
    return blob;
  },
  async previewPdf(handoverId: string, actor?: string) {
    const blob = await this.generatePdf(handoverId, actor);
    return URL.createObjectURL(blob);
  },
  async downloadPdf(handoverId: string, actor?: string) {
    const handover = generatedHandoverRepository.getById(handoverId);
    if (!handover) throw new Error("Handover not found.");
    const blob = await this.generatePdf(handoverId, actor);
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = this.getPdfFileName(handover);
    link.click();
    setTimeout(() => URL.revokeObjectURL(url), 1000);
  },
  async printPdf(handoverId: string, actor?: string) {
    const url = await this.previewPdf(handoverId, actor);
    const frame = document.createElement("iframe");
    frame.style.position = "fixed";
    frame.style.width = "1px";
    frame.style.height = "1px";
    frame.style.opacity = "0";
    frame.src = url;
    document.body.appendChild(frame);
    frame.onload = () => {
      if (!frame.contentWindow) throw new Error("Browser blocked print window.");
      frame.contentWindow.focus();
      frame.contentWindow.print();
      setTimeout(() => {
        frame.remove();
        URL.revokeObjectURL(url);
      }, 3000);
    };
  },
};
