import type { NextOfKin, Resident, UserProfile } from "./types";
export const RESIDENT_CONTACTS_VERSION = 1;
export type ResidentContactRole = "next_of_kin" | "nominated_representative" | "first_contact" | "gp" | "pharmacy" | "community_nurse" | "consultant";
export interface ResidentContactCard { relationshipId: string; contactId: string; role: ResidentContactRole; displayName: string; relationshipToResident?: string; organisationName?: string; professionalRole?: string; specialty?: string; phone?: string; mobile?: string; email?: string; preferredContactMethod?: string; primaryForRole: boolean; emergencyContact: boolean; authorityLabel?: string; active: boolean; route?: string; }
export interface ResidentContactsViewModel { residentId: string; nursingHomeId: string; generatedAt: string; cacheKey: string; primary: { firstContact?: ResidentContactCard; nominatedRepresentative?: ResidentContactCard; primaryNextOfKin?: ResidentContactCard; gp?: ResidentContactCard; pharmacy?: ResidentContactCard }; groups: { nextOfKin: ResidentContactCard[]; nominatedRepresentatives: ResidentContactCard[]; firstContacts: ResidentContactCard[]; gps: ResidentContactCard[]; pharmacies: ResidentContactCard[]; communityNurses: ResidentContactCard[]; consultants: ResidentContactCard[] } }
const nokCard = (residentId: string, item: NextOfKin, role: ResidentContactRole): ResidentContactCard => ({ relationshipId: `${item.id}:${role}`, contactId: item.id, role, displayName: item.name, relationshipToResident: item.relationship, phone: item.phone, mobile: item.mobile, email: item.email, preferredContactMethod: item.mobile || item.phone ? "Phone" : item.email ? "Email" : undefined, primaryForRole: role === "first_contact" ? item.primaryContact : role === "next_of_kin" && item.primaryContact, emergencyContact: item.emergencyContact, authorityLabel: item.powerOfAttorney ? "Power of Attorney recorded" : item.legalRepresentative ? "Nominated Representative" : undefined, active: true, route: `/residents/${residentId}?careSection=nok` });
export function getResidentContacts(resident: Resident, nursingHomeId: string, users: UserProfile[], capabilities: string[]): ResidentContactsViewModel {
  if (!capabilities.includes("resident_contacts.view")) throw new Error("Missing capability: resident_contacts.view"); const generatedAt = new Date().toISOString(); const current = (resident.nextOfKinList || []).filter((item) => item.active !== false); const nok = current.map((item) => nokCard(resident.id, item, "next_of_kin")); const first = current.filter((item) => item.primaryContact).map((item) => nokCard(resident.id, item, "first_contact")); const reps = current.filter((item) => item.legalRepresentative || item.powerOfAttorney).map((item) => nokCard(resident.id, item, "nominated_representative"));
  const professional = (name: string | undefined, role: ResidentContactRole, specialty?: string): ResidentContactCard[] => { if (!name?.trim()) return []; const user = users.find((item) => item.name === name); return [{ relationshipId: `legacy:${resident.id}:${role}`, contactId: user?.id || `legacy:${role}:${name}`, role, displayName: name, professionalRole: role === "gp" ? "General Practitioner" : "Consultant", specialty, phone: user?.phone, email: user?.email, primaryForRole: role === "gp", emergencyContact: false, active: true, route: "/profile" }]; };
  const gps = professional(resident.gp, "gp"); const consultants = professional(resident.consultant, "consultant", resident.consultantSpecialty); const groups = { nextOfKin: nok, nominatedRepresentatives: reps, firstContacts: first, gps, pharmacies: [], communityNurses: [], consultants };
  return { residentId: resident.id, nursingHomeId, generatedAt, cacheKey: JSON.stringify(["resident-contacts", RESIDENT_CONTACTS_VERSION, resident.id, nursingHomeId, "capabilities-v1"]), primary: { firstContact: first[0], nominatedRepresentative: reps[0], primaryNextOfKin: nok.find((item) => item.primaryForRole), gp: gps[0], pharmacy: undefined }, groups };
}
