import type { Resident, TimelineEvent } from "./types";
import type { RltTimelineItem } from "./rltTimeline";
export const RESIDENT_TIMELINE_VERSION = 1;
export type ResidentTimelineCategory = "admission_and_occupancy" | "clinical" | "care_planning" | "risk_and_incident" | "medication" | "contacts" | "preferences_and_strengths" | "end_of_life" | "other";
export interface ResidentTimelineItem { id: string; residentId: string; nursingHomeId: string; eventType: string; occurredAt: string; recordedAt?: string; title: string; summary: string; category: ResidentTimelineCategory; direction?: string; severity?: string; rltDomains: Array<{ rltDomainId: string; displayName: string }>; source: { sourceModule: string; sourceEntityType: string; sourceEntityId: string; route?: string }; actor?: { displayName?: string; roleLabel?: string }; sensitivity: "standard" | "sensitive" | "highly_sensitive"; }
export interface ResidentTimelinePage { residentId: string; nursingHomeId: string; generatedAt: string; cacheKey: string; items: ResidentTimelineItem[]; total: number; offset: number; limit: number; hasMore: boolean; }
const category = (type: string): ResidentTimelineCategory => type.includes("incident") || type.includes("risk") ? "risk_and_incident" : type.includes("care_plan") || type.includes("careplan") || type.includes("care_action") ? "care_planning" : type.includes("strength") || type.includes("preference") ? "preferences_and_strengths" : type.includes("death") || type.includes("end_of_life") ? "end_of_life" : type.includes("admit") || type.includes("hospital") || type.includes("resident_moved") || type.includes("discharg") ? "admission_and_occupancy" : type.includes("assessment") || type.includes("observation") || type.includes("dependency") || type.includes("chart.weight") ? "clinical" : type.includes("contact") ? "contacts" : "other";
export function getResidentTimeline(input: { resident: Resident; nursingHomeId: string; rltTimeline: RltTimelineItem[]; events: TimelineEvent[]; capabilities: string[]; filters?: { categories?: ResidentTimelineCategory[]; dateFrom?: string; dateTo?: string }; pagination?: { offset: number; limit: number } }): ResidentTimelinePage {
  if (!input.capabilities.includes("resident_timeline.view")) throw new Error("Missing capability: resident_timeline.view");
  const generatedAt = new Date().toISOString(); const items: ResidentTimelineItem[] = [];
  items.push({ id: `resident-timeline:admission:${input.resident.id}`, residentId: input.resident.id, nursingHomeId: input.nursingHomeId, eventType: "resident_admitted", occurredAt: input.resident.admissionDate, title: "Resident Admitted", summary: input.resident.admissionSource ? `Admitted from ${input.resident.admissionSource.replace(/_/g, " ")}.` : "Resident admission recorded.", category: "admission_and_occupancy", rltDomains: [], source: { sourceModule: "resident_lifecycle", sourceEntityType: "resident", sourceEntityId: input.resident.id, route: `/residents/${input.resident.id}` }, sensitivity: "standard" });
  for (const item of input.rltTimeline) items.push({ id: item.id, residentId: item.residentId, nursingHomeId: item.nursingHomeId, eventType: item.eventType, occurredAt: item.occurredAt, recordedAt: item.recordedAt, title: item.title, summary: item.summary, category: category(item.eventType), direction: item.clinicalDirection, severity: item.severity, rltDomains: item.rltDomains.map((tag) => ({ rltDomainId: tag.rltDomainId, displayName: tag.displayName })), source: item.source, actor: item.actor, sensitivity: item.sensitivity });
  const existingSources = new Set(items.map((item) => `${item.source.sourceEntityType}:${item.source.sourceEntityId}`));
  for (const event of input.events.filter((item) => item.residentId === input.resident.id && (!item.facilityId || item.facilityId === input.nursingHomeId))) { const sourceId = event.linkedRecordId || event.id; const sourceType = event.linkedRecordKind || event.type; if (existingSources.has(`${sourceType}:${sourceId}`)) continue; items.push({ id: `resident-timeline:event:${event.id}`, residentId: input.resident.id, nursingHomeId: input.nursingHomeId, eventType: event.type, occurredAt: event.createdAt, title: event.title, summary: (event.description || event.title).slice(0, 220), category: category(event.type), severity: event.priority === "critical" ? "critical" : event.priority === "high" ? "high" : "information", rltDomains: [], source: { sourceModule: event.type.split(".")[0], sourceEntityType: sourceType, sourceEntityId: sourceId, route: `/residents/${input.resident.id}` }, actor: { displayName: event.createdBy, roleLabel: event.role }, sensitivity: "standard" }); }
  let filtered = [...new Map(items.map((item) => [`${item.source.sourceEntityType}:${item.source.sourceEntityId}:${item.eventType}`, item])).values()];
  if (input.filters?.categories?.length) filtered = filtered.filter((item) => input.filters!.categories!.includes(item.category)); if (input.filters?.dateFrom) filtered = filtered.filter((item) => Date.parse(item.occurredAt) >= Date.parse(input.filters!.dateFrom!)); if (input.filters?.dateTo) filtered = filtered.filter((item) => Date.parse(item.occurredAt) <= Date.parse(input.filters!.dateTo!));
  filtered.sort((a, b) => b.occurredAt.localeCompare(a.occurredAt) || a.id.localeCompare(b.id)); const pagination = input.pagination || { offset: 0, limit: 20 }; const page = filtered.slice(pagination.offset, pagination.offset + pagination.limit);
  return { residentId: input.resident.id, nursingHomeId: input.nursingHomeId, generatedAt, cacheKey: JSON.stringify(["resident-timeline", RESIDENT_TIMELINE_VERSION, input.resident.id, input.nursingHomeId, input.filters, pagination, "capabilities-v1"]), items: page, total: filtered.length, offset: pagination.offset, limit: pagination.limit, hasMore: pagination.offset + pagination.limit < filtered.length };
}
