import type { Resident, UserProfile } from "./types";

export type ResidentRelationshipType = "named_nurse" | "key_worker" | "gp" | "primary_contact";
export interface ResidentRelationshipAssignment { id: string; residentId: string; nursingHomeId: string; relationshipType: ResidentRelationshipType; relatedEntityId: string; displayName: string; effectiveFrom: string; effectiveTo?: string; status: "current" | "ended"; assignedByUserAccountId: string; }
export interface ResidentProfileAudit { id: string; residentId: string; nursingHomeId: string; fieldKey: string; previousValue?: unknown; newValue?: unknown; actorUserAccountId: string; occurredAt: string; reason?: string; }
export interface ResidentProfileEvent { id: string; eventType: "ResidentProfileUpdated" | "ResidentPreferredNameChanged" | "ResidentPhotoChanged" | "ResidentNamedNurseAssigned" | "ResidentNamedNurseRemoved" | "ResidentKeyWorkerAssigned" | "ResidentKeyWorkerRemoved" | "ResidentGpAssigned" | "ResidentGpRemoved" | "ResidentPrimaryContactChanged"; residentId: string; nursingHomeId: string; changedFieldKeys: string[]; previousSummary?: string; currentSummary?: string; actorUserAccountId: string; occurredAt: string; correlationId: string; }
export interface ResidentProfileState { relationships: ResidentRelationshipAssignment[]; audit: ResidentProfileAudit[]; events: ResidentProfileEvent[]; }
export const EMPTY_RESIDENT_PROFILE_STATE: ResidentProfileState = { relationships: [], audit: [], events: [] };
export interface UpdateResidentProfileInput { firstName?: string; middleName?: string; lastName?: string; preferredName?: string; previousSurname?: string; dob?: string; gender?: Resident["gender"]; pronouns?: string; residentNumber?: string; nationality?: string; phone?: string; email?: string; address?: string; communicationNeeds?: string; religion?: string; preferredLanguage?: string; allergies?: string; photoUrl?: string; namedNurseUserId?: string; keyWorkerUserId?: string; gpUserId?: string; primaryContactId?: string; reason?: string; }
export interface ResidentProfileContext { userAccountId: string; nursingHomeId: string; capabilities: string[]; occurredAt: string; correlationId: string; residentBelongsToHome: (residentId: string, homeId: string) => boolean; }

const normalise = (value: string | undefined) => value?.trim() || undefined;
const changed = (before: unknown, after: unknown) => JSON.stringify(before ?? null) !== JSON.stringify(after ?? null);
const need = (context: ResidentProfileContext, capability: string) => { if (!context.capabilities.includes(capability)) throw new Error(`Missing capability: ${capability}`); };
const MAX_PROFILE_PHOTO_LENGTH = 180_000;
const photoAuditValue = (value: unknown) => (typeof value === "string" && value.trim() ? "[profile photo recorded]" : undefined);

function assignRelationship(state: ResidentProfileState, resident: Resident, type: ResidentRelationshipType, relatedEntityId: string | undefined, displayName: string | undefined, context: ResidentProfileContext) {
  const current = state.relationships.find((item) => item.residentId === resident.id && item.relationshipType === type && item.status === "current");
  if (current && current.relatedEntityId === relatedEntityId) return;
  if (current) { current.status = "ended"; current.effectiveTo = context.occurredAt; }
  if (relatedEntityId && displayName) state.relationships.push({ id: `resident-relationship:${resident.id}:${type}:${Date.parse(context.occurredAt)}`, residentId: resident.id, nursingHomeId: context.nursingHomeId, relationshipType: type, relatedEntityId, displayName, effectiveFrom: context.occurredAt, status: "current", assignedByUserAccountId: context.userAccountId });
  const names: Record<ResidentRelationshipType, [ResidentProfileEvent["eventType"], ResidentProfileEvent["eventType"]]> = { named_nurse: ["ResidentNamedNurseAssigned", "ResidentNamedNurseRemoved"], key_worker: ["ResidentKeyWorkerAssigned", "ResidentKeyWorkerRemoved"], gp: ["ResidentGpAssigned", "ResidentGpRemoved"], primary_contact: ["ResidentPrimaryContactChanged", "ResidentPrimaryContactChanged"] };
  state.events.push({ id: `resident-profile-event:${resident.id}:${type}:${state.events.length + 1}`, eventType: relatedEntityId ? names[type][0] : names[type][1], residentId: resident.id, nursingHomeId: context.nursingHomeId, changedFieldKeys: [type], previousSummary: current?.displayName, currentSummary: displayName, actorUserAccountId: context.userAccountId, occurredAt: context.occurredAt, correlationId: context.correlationId });
}

export function updateResidentProfile(state: ResidentProfileState, resident: Resident, users: UserProfile[], input: UpdateResidentProfileInput, context: ResidentProfileContext): Resident {
  need(context, "resident_profile.edit");
  if (!context.residentBelongsToHome(resident.id, context.nursingHomeId)) throw new Error("Resident is outside the authorised nursing home.");
  if (resident.status === "deleted" || resident.deletedAt) throw new Error("A deleted resident profile cannot be edited.");
  const identityKeys: Array<keyof UpdateResidentProfileInput> = ["firstName", "middleName", "lastName", "preferredName", "previousSurname", "dob", "residentNumber"];
  const demographicKeys: Array<keyof UpdateResidentProfileInput> = ["gender", "pronouns", "nationality", "phone", "email", "address", "communicationNeeds", "religion", "preferredLanguage", "allergies"];
  const photoKeys: Array<keyof UpdateResidentProfileInput> = ["photoUrl"];
  if (identityKeys.some((key) => input[key] !== undefined)) need(context, "resident_profile.edit_identity");
  if (input.residentNumber !== undefined) need(context, "resident_profile.edit_sensitive_identifiers");
  if (demographicKeys.some((key) => input[key] !== undefined)) need(context, "resident_profile.edit_demographics");
  if (photoKeys.some((key) => input[key] !== undefined)) need(context, "resident_profile.edit_photo");
  const next: Resident = { ...resident, keyWorkers: resident.keyWorkers ? { ...resident.keyWorkers } : undefined, nextOfKinList: resident.nextOfKinList?.map((item) => ({ ...item })) };
  const changes: string[] = [];
  for (const key of [...identityKeys, ...demographicKeys, ...photoKeys]) { if (input[key] === undefined) continue; const value = typeof input[key] === "string" ? normalise(input[key] as string) : input[key]; if ((key === "firstName" || key === "lastName") && !value) throw new Error("Legal first name and surname cannot be blank."); if (key === "dob" && value && !Number.isFinite(Date.parse(value as string))) throw new Error("Date of birth is invalid."); if (key === "photoUrl" && typeof value === "string" && value.length > MAX_PROFILE_PHOTO_LENGTH) throw new Error("The profile photo is too large. Please choose a smaller image."); const before = next[key as keyof Resident]; if (!changed(before, value)) continue; (next as unknown as Record<string, unknown>)[key] = value; changes.push(key); state.audit.push({ id: `resident-profile-audit:${resident.id}:${state.audit.length + 1}`, residentId: resident.id, nursingHomeId: context.nursingHomeId, fieldKey: key, previousValue: key === "photoUrl" ? photoAuditValue(before) : before, newValue: key === "photoUrl" ? photoAuditValue(value) : value, actorUserAccountId: context.userAccountId, occurredAt: context.occurredAt, reason: input.reason }); }
  const selectUser = (id: string | undefined, capability: string, roles?: string[]) => { if (id === undefined) return undefined; need(context, capability); if (!id) return null; const user = users.find((item) => item.id === id && item.status === "active" && (!roles || roles.includes(item.role)) && (item.facilityIds?.includes(context.nursingHomeId) || (item.facilityId || context.nursingHomeId) === context.nursingHomeId)); if (!user) throw new Error("Selected professional is not active, eligible, or assigned to this nursing home."); return user; };
  const nurse = selectUser(input.namedNurseUserId, "resident_profile.assign_named_nurse", ["nurse", "cnm", "don"]); if (nurse !== undefined) { next.keyWorkers = { namedNurse: nurse?.name || "", namedCarer: next.keyWorkers?.namedCarer || "", keyWorker: next.keyWorkers?.keyWorker || "" }; assignRelationship(state, resident, "named_nurse", nurse?.id, nurse?.name, context); changes.push("namedNurse"); }
  const worker = selectUser(input.keyWorkerUserId, "resident_profile.assign_key_worker"); if (worker !== undefined) { next.keyWorkers = { namedNurse: next.keyWorkers?.namedNurse || "", namedCarer: next.keyWorkers?.namedCarer || "", keyWorker: worker?.name || "" }; assignRelationship(state, resident, "key_worker", worker?.id, worker?.name, context); changes.push("keyWorker"); }
  const gp = selectUser(input.gpUserId, "resident_profile.assign_gp", ["doctor"]); if (gp !== undefined) { next.gp = gp?.name || ""; assignRelationship(state, resident, "gp", gp?.id, gp?.name, context); changes.push("gp"); }
  if (input.primaryContactId !== undefined) { need(context, "resident_profile.manage_contacts"); const contact = input.primaryContactId ? next.nextOfKinList?.find((item) => item.id === input.primaryContactId) : undefined; if (input.primaryContactId && !contact) throw new Error("Primary contact must belong to this resident's contact list."); next.nextOfKinList = next.nextOfKinList?.map((item) => ({ ...item, primaryContact: item.id === input.primaryContactId })); assignRelationship(state, resident, "primary_contact", contact?.id, contact?.name, context); changes.push("primaryContact"); }
  if (!changes.length) return resident;
  next.preferredName = normalise(next.preferredName);
  next.profileUpdatedAt = context.occurredAt;
  state.events.push({ id: `resident-profile-event:${resident.id}:updated:${state.events.length + 1}`, eventType: input.photoUrl !== undefined && changed(resident.photoUrl, next.photoUrl) ? "ResidentPhotoChanged" : input.preferredName !== undefined && changed(resident.preferredName, next.preferredName) ? "ResidentPreferredNameChanged" : "ResidentProfileUpdated", residentId: resident.id, nursingHomeId: context.nursingHomeId, changedFieldKeys: [...new Set(changes)], previousSummary: `${resident.firstName} ${resident.lastName}`, currentSummary: `${next.preferredName || next.firstName} ${next.lastName}`, actorUserAccountId: context.userAccountId, occurredAt: context.occurredAt, correlationId: context.correlationId });
  return next;
}
