import type { WorkItem } from "@/domain/work/workTypes";
import type { Assessment, ClinicalAlert, HandoverNote, Incident, ProblemIntervention, Resident, Task, VitalSign, WeightRecord } from "./types";
import type { ResidentHeaderViewModel } from "./residentHeader";
import type { ResidentRltClinicalOverview } from "./rltClinicalOverview";
import type { RltTimelineItem } from "./rltTimeline";
import type { EndOfLifeSummary } from "./endOfLifePathway";

export type ResidentOverviewSeverity = "information" | "low" | "medium" | "high" | "critical";
export interface ResidentClinicalAlertSummary { id: string; type: string; label: string; conciseExplanation?: string; severity: ResidentOverviewSeverity; sourceEntityType: string; sourceEntityId: string; occurredAt?: string; reviewDueAt?: string; route?: string; }
export interface ResidentRecommendedAction { code: string; label: string; reason: string; priority: "routine" | "important" | "urgent" | "critical"; sourceEntityType: string; sourceEntityId: string; route: string; }
export interface ResidentClinicalOverview {
  residentId: string; nursingHomeId: string; generatedAt: string;
  currentClinicalStory: { headline: string; summaryPoints: string[]; clinicalDirection: "stable" | "improving" | "deteriorating" | "mixed" | "insufficient_data"; lastMeaningfulChangeAt?: string };
  immediateAlerts: ResidentClinicalAlertSummary[];
  currentPriorities: ResidentRecommendedAction[];
  recentChanges: Array<{ id: string; label: string; occurredAt: string; direction?: string; route?: string }>;
  carePlanning: { activeCarePlanCount: number; dueTodayCount: number; overdueCount: number; domainsWithPlans: string[]; nearestReview?: { title: string; dueAt: string; route: string }; currentCareFocus: string[] };
  assessments: { dueCount: number; overdueCount: number; recentImportant: Array<{ id: string; title: string; riskLevel: string; date: string; route: string }>; highestRisk?: string };
  observations: { latestNews2?: { score: number; risk?: string; recordedAt: string }; attentionCount: number; route: string };
  risks: Array<{ id: string; label: string; level: string; domain: string; route?: string }>;
  nutritionAndWeight?: { latestWeightKg?: number; recordedAt?: string; concern?: string; carePlanStatus?: string };
  mobilityAndFalls: { dependency: string; fallsRisk?: string; recentFall?: { id: string; date: string }; carePlanStatus?: string };
  incidents: { recentCount: number; unresolvedFollowUpCount: number; latest?: { id: string; type: string; date: string; severity: string } };
  currentWork: { overdue: number; dueToday: number; activeCount: number; items: Array<{ id: string; title: string; dueAt?: string; priority: string; route?: string }> };
  handover: { priorityCount: number; latestImportant?: { id: string; summary: string; effectiveAt: string; acknowledgementRequired: boolean; route: string } };
  strengthsAndPreferences: { canDo: string[]; prefers: string[]; pleaseAvoid: string[] };
  medicationConcerns?: string[];
  endOfLife?: EndOfLifeSummary;
  recommendedNextActions: ResidentRecommendedAction[];
}

export interface ResidentClinicalOverviewData { resident: Resident; header: ResidentHeaderViewModel; rltOverview: ResidentRltClinicalOverview; timeline: RltTimelineItem[]; assessments: Assessment[]; clinicalAlerts: ClinicalAlert[]; vitals: VitalSign[]; weights: WeightRecord[]; incidents: Incident[]; tasks: Task[]; handovers: HandoverNote[]; interventions: ProblemIntervention[]; workItems: WorkItem[]; endOfLife?: EndOfLifeSummary; strengths: string[]; preferences: string[]; pleaseAvoid: string[]; }
export interface ResidentClinicalOverviewAuthorization { nursingHomeId: string; wardId?: string; shiftId?: string; capabilities: string[]; generatedAt?: string; }

const rank: Record<ResidentOverviewSeverity, number> = { critical: 5, high: 4, medium: 3, low: 2, information: 1 };
const riskPriority = (value: string): ResidentOverviewSeverity => value === "critical" || value === "very_high" ? "critical" : value === "high" ? "high" : value === "moderate" || value === "warning" || value === "medium" ? "medium" : "low";
const titleCase = (value: string) => value.replace(/_/g, " ").replace(/\b\w/g, (letter) => letter.toUpperCase());
const sameDay = (left: string, right: string) => left.slice(0, 10) === right.slice(0, 10);

export function getResidentClinicalOverview(data: ResidentClinicalOverviewData, authorization: ResidentClinicalOverviewAuthorization): ResidentClinicalOverview {
  if (!authorization.capabilities.includes("resident_clinical_overview.view")) throw new Error("Missing capability: resident_clinical_overview.view");
  if (data.header.nursingHomeId !== authorization.nursingHomeId) throw new Error("Resident is outside the authorised nursing home.");
  const now = authorization.generatedAt || new Date().toISOString(); const nowMs = Date.parse(now); const residentId = data.resident.id;
  const activeDomains = data.rltOverview.domains.filter((item) => item.carePlanStatus.activeCount > 0);
  const overdueDomains = activeDomains.filter((item) => item.reviewStatus.state === "overdue"); const dueDomains = activeDomains.filter((item) => ["due_today", "due_soon"].includes(item.reviewStatus.state));
  const risks = authorization.capabilities.includes("resident_clinical_overview.view_risks") ? data.rltOverview.domains.flatMap((domain) => domain.relatedRisks.map((risk) => ({ id: risk.riskId, label: risk.displayName, level: risk.level, domain: domain.displayName, route: risk.route }))).sort((a, b) => rank[riskPriority(b.level)] - rank[riskPriority(a.level)]).slice(0, 8) : [];
  const immediateAlerts: ResidentClinicalAlertSummary[] = [];
  for (const allergy of data.header.allergies) immediateAlerts.push({ id: allergy.allergyId, type: "allergy", label: `Allergy: ${allergy.substance}`, conciseExplanation: allergy.reaction, severity: allergy.severity === "life_threatening" ? "critical" : allergy.severity === "severe" ? "high" : "medium", sourceEntityType: "allergy", sourceEntityId: allergy.allergyId, route: allergy.sourceRoute });
  if (data.header.advanceCare.dnarStatus === "recorded") immediateAlerts.push({ id: `dnar:${residentId}`, type: "advance_care", label: "DNAR Decision Recorded", severity: "high", sourceEntityType: "advance_care_decision", sourceEntityId: data.header.advanceCare.sourceRecordIds[0] || residentId, route: `/residents/${residentId}?rltDomainId=dying` });
  if (data.header.isolation.active) immediateAlerts.push({ id: `isolation:${residentId}`, type: "isolation", label: `Isolation Active${data.header.isolation.type ? ` · ${data.header.isolation.type}` : ""}`, severity: "high", sourceEntityType: "isolation", sourceEntityId: residentId });
  for (const alert of data.clinicalAlerts.filter((item) => item.residentId === residentId && !item.resolvedAt && !item.dismissedAt && ["warning", "high", "critical"].includes(item.severity))) immediateAlerts.push({ id: alert.id, type: alert.type, label: alert.title, conciseExplanation: alert.message, severity: alert.severity === "critical" ? "critical" : "high", sourceEntityType: "clinical_alert", sourceEntityId: alert.id, occurredAt: alert.createdAt, route: `/residents/${residentId}?careSection=vitals` });
  for (const domain of overdueDomains) immediateAlerts.push({ id: `overdue-plan:${domain.rltDomainId}`, type: "care_plan_review", label: `${domain.displayName} Nursing Care Plan review overdue`, severity: "high", sourceEntityType: "care_plan_item", sourceEntityId: domain.carePlanStatus.activePlans[0]?.carePlanItemId || domain.rltDomainId, reviewDueAt: domain.reviewStatus.nearestReviewDate, route: domain.reviewStatus.route });
  if (data.endOfLife?.pathway && ["end_of_life_care_active", "last_days_of_life"].includes(data.endOfLife.pathway.status)) immediateAlerts.push({ id: data.endOfLife.pathway.id, type: "end_of_life", label: `End-of-Life pathway: ${titleCase(data.endOfLife.pathway.status)}`, severity: data.endOfLife.pathway.status === "last_days_of_life" ? "critical" : "high", sourceEntityType: "end_of_life_pathway", sourceEntityId: data.endOfLife.pathway.id, route: `/residents/${residentId}?rltDomainId=dying` });
  const dedupedAlerts = [...new Map(immediateAlerts.map((item) => [`${item.type}:${item.sourceEntityId}`, item])).values()].sort((a, b) => rank[b.severity] - rank[a.severity]);
  const activeTasks = data.tasks.filter((item) => item.residentId === residentId && !["completed", "deleted"].includes(item.status));
  const activeWork = data.workItems.filter((item) => item.residentId === residentId && ["scheduled", "in_progress", "deferred", "missed"].includes(item.persistedStatus));
  const combinedWork = [...activeWork.map((item) => ({ id: String(item.id), title: item.title, dueAt: item.schedule.effectiveDueAt || item.schedule.dueAt, priority: item.priority, route: item.source.route })), ...activeTasks.map((item) => ({ id: item.id, title: item.title, dueAt: item.dueDate, priority: item.priority || "normal", route: `/tasks` }))];
  const uniqueWork = [...new Map(combinedWork.map((item) => [item.id, item])).values()]; const overdueWork = uniqueWork.filter((item) => item.dueAt && Date.parse(item.dueAt) < nowMs); const dueTodayWork = uniqueWork.filter((item) => item.dueAt && sameDay(item.dueAt, now));
  const actions: ResidentRecommendedAction[] = [];
  overdueDomains.forEach((domain) => actions.push({ code: `review-care-plan:${domain.rltDomainId}`, label: `Review ${domain.displayName} Nursing Care Plan`, reason: "The current clinical review date is overdue.", priority: "urgent", sourceEntityType: "care_plan_item", sourceEntityId: domain.carePlanStatus.activePlans[0]?.carePlanItemId || domain.rltDomainId, route: domain.reviewStatus.route || `/residents/${residentId}?rltDomainId=${domain.rltDomainId}` }));
  overdueWork.slice(0, 4).forEach((item) => actions.push({ code: `overdue-work:${item.id}`, label: item.title, reason: "This work is overdue for the resident.", priority: item.priority === "critical" ? "critical" : "urgent", sourceEntityType: "work_item", sourceEntityId: item.id, route: item.route || `/residents/${residentId}?careSection=tasks` }));
  const recentTimeline = data.timeline.filter((item) => Date.parse(item.occurredAt) >= nowMs - 14 * 86400000).slice(0, 6);
  const directionSet = new Set(recentTimeline.map((item) => item.clinicalDirection)); const clinicalDirection = directionSet.has("deteriorated") && directionSet.has("improved") ? "mixed" : directionSet.has("deteriorated") ? "deteriorating" : directionSet.has("improved") ? "improving" : recentTimeline.length || activeDomains.length ? "stable" : "insufficient_data";
  const points: string[] = [];
  dedupedAlerts.slice(0, 2).forEach((item) => points.push(item.label)); overdueDomains.slice(0, 2).forEach((item) => points.push(`${item.displayName} Nursing Care Plan review is overdue.`)); risks.filter((item) => ["high", "critical"].includes(item.level)).slice(0, 2).forEach((item) => points.push(`${item.label} remains ${titleCase(item.level)}.`)); if (overdueWork.length) points.push(`${overdueWork.length} item${overdueWork.length === 1 ? " is" : "s are"} overdue.`); data.strengths.slice(0, 1).forEach((item) => points.push(`Resident strength: ${item}.`)); data.preferences.slice(0, 1).forEach((item) => points.push(`Resident preference: ${item}.`));
  const topIssue = dedupedAlerts[0]?.label || (overdueDomains[0] ? `${overdueDomains[0].displayName} review` : risks[0]?.label); const headline = topIssue ? `${data.header.identity.displayName} requires attention for ${topIssue.toLowerCase()}.` : activeDomains.length ? `${data.header.identity.displayName} has ${activeDomains.length} active Nursing Care Plan${activeDomains.length === 1 ? "" : "s"} with no immediate source-recorded deterioration.` : `There is insufficient current clinical information to summarise ${data.header.identity.displayName}'s care needs.`;
  const allowedAssessments = authorization.capabilities.includes("resident_clinical_overview.view_assessments") ? data.assessments.filter((item) => item.residentId === residentId && !["deleted", "archived"].includes(item.status || "")) : [];
  const recentAssessments = allowedAssessments.filter((item) => Date.parse(item.date) >= nowMs - 30 * 86400000 && ["high", "very_high"].includes(item.riskLevel)).sort((a, b) => b.date.localeCompare(a.date)).slice(0, 4);
  const assessmentDue = allowedAssessments.filter((item) => item.nextReassessmentDate && Date.parse(item.nextReassessmentDate) >= nowMs && Date.parse(item.nextReassessmentDate) < nowMs + 7 * 86400000); const assessmentOverdue = allowedAssessments.filter((item) => item.nextReassessmentDate && Date.parse(item.nextReassessmentDate) < nowMs);
  const latestVital = data.vitals.filter((item) => item.residentId === residentId && !item.deletedAt).sort((a, b) => b.recordedAt.localeCompare(a.recordedAt))[0];
  const latestWeight = data.weights.filter((item) => item.residentId === residentId).sort((a, b) => b.date.localeCompare(a.date))[0] || (latestVital?.weight ? { weightKg: latestVital.weight, date: latestVital.recordedAt } : undefined);
  const mobility = data.rltOverview.domains.find((item) => item.rltDomainId === "mobilisation"); const fallsRisk = mobility?.relatedRisks.find((item) => /fall/i.test(`${item.riskType} ${item.displayName}`)); const recentFalls = data.incidents.filter((item) => item.residentId === residentId && item.type === "fall" && item.recordStatus !== "deleted").sort((a, b) => b.date.localeCompare(a.date));
  const residentHandovers = data.handovers.filter((item) => item.residentId === residentId && item.recordStatus !== "deleted" && (!authorization.wardId || !item.currentVisibilityWardId || item.currentVisibilityWardId === authorization.wardId || item.wardId === authorization.wardId) && item.handoverPriority !== "routine").sort((a, b) => (b.effectiveFrom || b.date).localeCompare(a.effectiveFrom || a.date));
  const medicationConcerns = authorization.capabilities.includes("resident_clinical_overview.view_medication") && data.resident.currentMedication?.trim() ? ["Medication information is recorded; open the authorised medication source for details."] : undefined;
  return { residentId, nursingHomeId: authorization.nursingHomeId, generatedAt: now,
    currentClinicalStory: { headline, summaryPoints: [...new Set(points)].slice(0, 6), clinicalDirection, lastMeaningfulChangeAt: recentTimeline[0]?.occurredAt }, immediateAlerts: dedupedAlerts, currentPriorities: actions.slice(0, 6), recentChanges: recentTimeline.map((item) => ({ id: item.id, label: item.title, occurredAt: item.occurredAt, direction: item.clinicalDirection, route: item.source.route })),
    carePlanning: { activeCarePlanCount: data.rltOverview.overallSummary.activeCarePlanCount, dueTodayCount: dueDomains.filter((item) => item.reviewStatus.state === "due_today").length, overdueCount: overdueDomains.length, domainsWithPlans: activeDomains.map((item) => item.displayName), nearestReview: [...activeDomains].filter((item) => item.reviewStatus.nearestReviewDate).sort((a, b) => a.reviewStatus.nearestReviewDate!.localeCompare(b.reviewStatus.nearestReviewDate!))[0] ? (() => { const item = [...activeDomains].filter((domain) => domain.reviewStatus.nearestReviewDate).sort((a, b) => a.reviewStatus.nearestReviewDate!.localeCompare(b.reviewStatus.nearestReviewDate!))[0]; return { title: item.displayName, dueAt: item.reviewStatus.nearestReviewDate!, route: item.reviewStatus.route || `/residents/${residentId}?rltDomainId=${item.rltDomainId}` }; })() : undefined, currentCareFocus: activeDomains.flatMap((item) => item.currentCareFocus.keyActions).slice(0, 5) },
    assessments: { dueCount: assessmentDue.length, overdueCount: assessmentOverdue.length, recentImportant: recentAssessments.map((item) => ({ id: item.id, title: `${titleCase(item.type)} Assessment`, riskLevel: item.riskLevel, date: item.date, route: `/assessments/${item.id}` })), highestRisk: recentAssessments[0]?.riskLevel },
    observations: { latestNews2: latestVital?.news2Score !== undefined ? { score: latestVital.news2Score, risk: latestVital.news2Risk, recordedAt: latestVital.recordedAt } : undefined, attentionCount: data.clinicalAlerts.filter((item) => item.residentId === residentId && !item.resolvedAt && !item.dismissedAt).length, route: `/residents/${residentId}?careSection=vitals` }, risks,
    nutritionAndWeight: latestWeight || data.rltOverview.domains.find((item) => item.rltDomainId === "eating_drinking")?.carePlanStatus.hasActivePlan ? { latestWeightKg: latestWeight?.weightKg, recordedAt: latestWeight?.date, concern: data.rltOverview.domains.find((item) => item.rltDomainId === "eating_drinking")?.relatedRisks[0]?.displayName, carePlanStatus: data.rltOverview.domains.find((item) => item.rltDomainId === "eating_drinking")?.carePlanStatus.status } : undefined,
    mobilityAndFalls: { dependency: mobility?.dependency.displayLabel || "Dependency has not yet been recorded.", fallsRisk: fallsRisk?.level, recentFall: recentFalls[0] ? { id: recentFalls[0].id, date: recentFalls[0].date } : undefined, carePlanStatus: mobility?.carePlanStatus.status },
    incidents: { recentCount: data.incidents.filter((item) => item.residentId === residentId && item.recordStatus !== "deleted" && Date.parse(item.date) >= nowMs - 30 * 86400000).length, unresolvedFollowUpCount: data.incidents.filter((item) => item.residentId === residentId && item.recordStatus !== "deleted" && item.followUpRequired && item.status !== "closed").length, latest: data.incidents.filter((item) => item.residentId === residentId && item.recordStatus !== "deleted").sort((a, b) => b.date.localeCompare(a.date))[0] ? (() => { const item = data.incidents.filter((incident) => incident.residentId === residentId && incident.recordStatus !== "deleted").sort((a, b) => b.date.localeCompare(a.date))[0]; return { id: item.id, type: item.type, date: item.date, severity: item.severity }; })() : undefined },
    currentWork: { overdue: overdueWork.length, dueToday: dueTodayWork.length, activeCount: uniqueWork.length, items: uniqueWork.sort((a, b) => `${a.dueAt || "z"}`.localeCompare(`${b.dueAt || "z"}`)).slice(0, 6) }, handover: { priorityCount: residentHandovers.length, latestImportant: residentHandovers[0] ? { id: residentHandovers[0].id, summary: residentHandovers[0].summary, effectiveAt: residentHandovers[0].effectiveFrom || residentHandovers[0].date, acknowledgementRequired: !residentHandovers[0].acknowledgedAt, route: "/handovers" } : undefined }, strengthsAndPreferences: { canDo: data.strengths.slice(0, 4), prefers: data.preferences.slice(0, 4), pleaseAvoid: data.pleaseAvoid.slice(0, 4) }, medicationConcerns, endOfLife: authorization.capabilities.includes("resident_clinical_overview.view_end_of_life") ? data.endOfLife : undefined, recommendedNextActions: actions.slice(0, 6) };
}

export const RESIDENT_CLINICAL_OVERVIEW_QUERY_KEY = (residentId: string, nursingHomeId: string, wardId: string | undefined, shiftId: string | undefined, capabilityVersion: string) => ["resident-clinical-overview", 1, residentId, nursingHomeId, wardId || "all", shiftId || "none", capabilityVersion] as const;
