import type { WorkItem } from "@/domain/work/workTypes";
import { RLT_DOMAINS, RLT_DOMAIN_BY_ID, type RltDomainId, type RltDomainKey } from "./rlt";

export type ResidentStrengthStatus = "current" | "superseded" | "inactive";
export type ResidentStrengthSource = "resident" | "family" | "nominated_representative" | "staff_observation" | "assessment" | "care_plan_review" | "pre_admission" | "previous_record" | "other";
export type ResidentStrengthCategory = "physical_ability" | "cognitive_ability" | "communication_ability" | "decision_making" | "self_care" | "mobility" | "social" | "emotional" | "spiritual" | "routine" | "equipment_use" | "coping_strategy" | "other";
export type ResidentAbilityLevel = "independent" | "with_prompting" | "with_supervision" | "with_assistance" | "variable" | "not_assessed";
export type ResidentPreferenceStatus = "current" | "superseded" | "inactive";
export type PreferenceImportance = "routine" | "important" | "essential";
export type PreferenceSource = "resident" | "family" | "nominated_representative" | "advance_care_plan" | "staff_observation" | "assessment" | "pre_admission" | "previous_record" | "other";
export type PreferenceApplicability = "always" | "when_possible" | "specific_time" | "specific_context" | "conditional";
export type PreferenceAccommodationStatus = "not_reviewed" | "can_accommodate" | "partially_accommodated" | "cannot_accommodate";
export type PreferenceSafetyReviewStatus = "not_required" | "pending" | "reviewed" | "cannot_fully_accommodate";
export type PreferenceSensitivity = "standard" | "sensitive" | "highly_sensitive";
export type ResidentPreferenceCategory = "food" | "drink" | "meal_routine" | "communication" | "preferred_name" | "language" | "hearing" | "vision" | "staff_approach" | "personal_care" | "bathing" | "oral_care" | "dressing" | "grooming" | "toileting" | "continence" | "mobility" | "positioning" | "sleep" | "bedtime_routine" | "waking_routine" | "temperature" | "environment" | "activities" | "social_contact" | "privacy" | "relationships" | "religion" | "spirituality" | "end_of_life" | "risk_taking" | "other";
export type RecordChangeReason = "initial_record" | "routine_review" | "condition_improved" | "condition_deteriorated" | "resident_update" | "assessment" | "care_plan_review" | "hospital_return" | "correction" | "previous_record_confirmation" | "other";

export const STRENGTH_CATEGORIES: readonly ResidentStrengthCategory[] = ["physical_ability", "cognitive_ability", "communication_ability", "decision_making", "self_care", "mobility", "social", "emotional", "spiritual", "routine", "equipment_use", "coping_strategy", "other"];
export const ABILITY_LEVELS: readonly ResidentAbilityLevel[] = ["independent", "with_prompting", "with_supervision", "with_assistance", "variable", "not_assessed"];
export const ABILITY_LABELS: Record<ResidentAbilityLevel, string> = { independent: "Independent", with_prompting: "With Prompting", with_supervision: "With Supervision", with_assistance: "With Assistance", variable: "Variable", not_assessed: "Not Assessed" };
export const PREFERENCE_IMPORTANCE: readonly PreferenceImportance[] = ["routine", "important", "essential"];

export const PREFERENCE_CATEGORY_DOMAINS: Record<ResidentPreferenceCategory, readonly RltDomainId[]> = {
  food: ["eating_drinking"], drink: ["eating_drinking"], meal_routine: ["eating_drinking"],
  communication: ["communication"], preferred_name: ["communication", "expressing_sexuality"], language: ["communication"], hearing: ["communication"], vision: ["communication", "safe_environment"],
  staff_approach: ["communication", "personal_cleansing_dressing", "dying"], personal_care: ["personal_cleansing_dressing"], bathing: ["personal_cleansing_dressing"], oral_care: ["personal_cleansing_dressing"], dressing: ["personal_cleansing_dressing", "expressing_sexuality"], grooming: ["personal_cleansing_dressing", "expressing_sexuality"],
  toileting: ["elimination"], continence: ["elimination"], mobility: ["mobilisation"], positioning: ["mobilisation", "breathing", "sleeping"], sleep: ["sleeping"], bedtime_routine: ["sleeping"], waking_routine: ["sleeping"], temperature: ["body_temperature"], environment: ["safe_environment", "sleeping"],
  activities: ["meaningful_activity"], social_contact: ["meaningful_activity", "communication"], privacy: ["expressing_sexuality", "personal_cleansing_dressing", "dying"], relationships: ["expressing_sexuality", "meaningful_activity", "dying"], religion: ["meaningful_activity", "dying"], spirituality: ["meaningful_activity", "dying"], end_of_life: ["dying"], risk_taking: ["safe_environment", "mobilisation"],
  other: RLT_DOMAINS.map((domain) => domain.id),
};

interface VersionedRecord { versionNumber: number; versionChainId: string; previousVersionId?: string; changeReasonCode: RecordChangeReason; changeReasonText?: string; }
export interface ResidentStrength extends VersionedRecord {
  id: string; residentId: string; nursingHomeId: string; wardId?: string; rltDomainId: RltDomainId; rltDomainKey: RltDomainKey; category: ResidentStrengthCategory;
  title: string; description: string; residentOwnWords?: string; abilityLevel: ResidentAbilityLevel; canDoIndependently: string[]; canDoWithSupport: string[]; supportThatHelps: string[]; equipmentOrAdaptations: string[]; limitationsOrConditions?: string[]; contextNotes?: string;
  source: ResidentStrengthSource; sourceEntityType?: string; sourceEntityId?: string; contributorName?: string; contributorRelationship?: string;
  effectiveFrom: string; effectiveTo?: string; status: ResidentStrengthStatus; reviewDate?: string; lastReviewedAt?: string; recordedByUserAccountId: string; recordedByStaffMemberId?: string; createdAt: string; updatedAt: string;
}
export interface ResidentPreference extends VersionedRecord {
  id: string; residentId: string; nursingHomeId: string; wardId?: string; rltDomainId: RltDomainId; rltDomainKey: RltDomainKey; category: ResidentPreferenceCategory;
  title: string; preference: string; residentOwnWords?: string; importance: PreferenceImportance; applicability: PreferenceApplicability; preferredOptions: string[]; dislikedOptions: string[]; avoid: string[]; contextOrConditions?: string; preferredTime?: string; preferredTimeWindow?: { startLocalTime?: string; endLocalTime?: string }; preferredPeopleOrGender?: string[]; culturalNeeds?: string[]; religiousNeeds?: string[]; spiritualNeeds?: string[]; communicationSupport?: string[]; equipmentOrAdaptations?: string[];
  source: PreferenceSource; statedByResident: boolean; contributorName?: string; contributorRelationship?: string; representativeRecordId?: string; sourceEntityType?: string; sourceEntityId?: string; importanceReason?: string;
  safetyReviewRequired: boolean; safetyReviewStatus: PreferenceSafetyReviewStatus; accommodationStatus: PreferenceAccommodationStatus; accommodationReason?: string; agreedAlternative?: string; sensitivity: PreferenceSensitivity;
  effectiveFrom: string; effectiveTo?: string; reviewDate?: string; lastReviewedAt?: string; status: ResidentPreferenceStatus; recordedByUserAccountId: string; recordedByStaffMemberId?: string; createdAt: string; updatedAt: string;
}
export type PreferenceConflictType = "resident_vs_family" | "current_vs_previous" | "preference_vs_safety" | "preference_vs_policy" | "preference_vs_environment" | "other";
export interface PreferenceConflict { id: string; residentId: string; nursingHomeId: string; preferenceIds: string[]; conflictType: PreferenceConflictType; status: "open" | "under_review" | "resolved"; summary: string; resolutionSummary?: string; agreedOutcome?: string; createdAt: string; createdByUserAccountId: string; resolvedAt?: string; resolvedByUserAccountId?: string; }
export interface PreferenceSafetyReview { id: string; preferenceId: string; residentId: string; nursingHomeId: string; reason: string; clinicalConcern: string; status: "pending" | "resolved"; decision?: string; mitigation?: string; residentInvolved: boolean; representativeInvolved: boolean; reviewerUserAccountId?: string; requestedAt: string; resolvedAt?: string; reviewDate?: string; linkedRiskId?: string; linkedCarePlanId?: string; }
export interface StrengthPreferenceReview { id: string; recordType: "strength" | "preference"; recordId: string; decision: "confirmed" | "updated" | "superseded" | "inactive"; comments?: string; reviewedAt: string; reviewedByUserAccountId: string; nextReviewDate?: string; }
export interface StrengthPreferenceAuditEntry { id: string; recordType: "strength" | "preference" | "preference_conflict" | "preference_safety_review"; recordId: string; action: string; residentId: string; nursingHomeId: string; rltDomainId?: RltDomainId; previousValue?: unknown; newValue?: unknown; source?: string; reason?: string; effectiveAt: string; recordedAt: string; actorUserAccountId: string; }
export interface StrengthPreferenceEvent { id: string; eventType: "ResidentStrengthRecorded" | "ResidentStrengthChanged" | "ResidentStrengthReviewed" | "ResidentStrengthSuperseded" | "ResidentPreferenceRecorded" | "ResidentPreferenceChanged" | "ResidentPreferenceReviewed" | "ResidentPreferenceSuperseded" | "ResidentPreferenceAccommodationChanged" | "ResidentPreferenceSafetyReviewRequested" | "ResidentPreferenceSafetyReviewResolved" | "ResidentPreferenceConflictRaised" | "ResidentPreferenceConflictResolved"; eventVersion: 1; residentId: string; nursingHomeId: string; wardId?: string; rltDomainId?: RltDomainId; recordId: string; category?: string; source?: string; actorUserAccountId: string; occurredAt: string; recordedAt: string; correlationId: string; safeSummary: string; }
export interface StrengthPreferenceState { strengths: ResidentStrength[]; preferences: ResidentPreference[]; reviews: StrengthPreferenceReview[]; safetyReviews: PreferenceSafetyReview[]; conflicts: PreferenceConflict[]; audit: StrengthPreferenceAuditEntry[]; events: StrengthPreferenceEvent[]; }
export const EMPTY_STRENGTH_PREFERENCE_STATE: StrengthPreferenceState = { strengths: [], preferences: [], reviews: [], safetyReviews: [], conflicts: [], audit: [], events: [] };

export interface StrengthPreferenceContext { userAccountId: string; staffMemberId?: string; nursingHomeId: string; wardId?: string; capabilities: string[]; occurredAt: string; correlationId: string; residentExists: (id: string) => boolean; residentBelongsToHome: (id: string, homeId: string) => boolean; sourceBelongsToResident?: (type: string, id: string, residentId: string, homeId: string) => boolean; }
export type CreateStrengthInput = Omit<ResidentStrength, "id" | "nursingHomeId" | "wardId" | "rltDomainKey" | "status" | "recordedByUserAccountId" | "recordedByStaffMemberId" | "createdAt" | "updatedAt" | "versionNumber" | "versionChainId" | "previousVersionId"> & { intentionalDuplicate?: boolean };
export type CreatePreferenceInput = Omit<ResidentPreference, "id" | "nursingHomeId" | "wardId" | "rltDomainKey" | "status" | "recordedByUserAccountId" | "recordedByStaffMemberId" | "createdAt" | "updatedAt" | "versionNumber" | "versionChainId" | "previousVersionId"> & { intentionalDuplicate?: boolean };

const clean = (value: string) => value.trim().toLowerCase().replace(/[^a-z0-9]+/g, " ").trim();
const stable = (value: string) => value.replace(/[^a-zA-Z0-9_-]+/g, "-").toLowerCase();
const validDate = (value?: string) => Boolean(value && Number.isFinite(Date.parse(value)));
const requireCapability = (context: StrengthPreferenceContext, capability: string) => { if (!context.capabilities.includes(capability)) throw new Error(`Missing capability: ${capability}`); };
const validateScope = (residentId: string, context: StrengthPreferenceContext) => { if (!context.residentExists(residentId)) throw new Error("Resident does not exist."); if (!context.residentBelongsToHome(residentId, context.nursingHomeId)) throw new Error("Cross-home record is prohibited."); };
const domainFor = (id: RltDomainId) => { const domain = RLT_DOMAIN_BY_ID[id]; if (!domain?.active) throw new Error("RLT domain is invalid or inactive."); return domain; };
const validateSourceReference = (input: { residentId: string; sourceEntityType?: string; sourceEntityId?: string }, context: StrengthPreferenceContext) => { if (Boolean(input.sourceEntityType) !== Boolean(input.sourceEntityId)) throw new Error("Source entity type and ID must be supplied together."); if (input.sourceEntityType && input.sourceEntityId && context.sourceBelongsToResident && !context.sourceBelongsToResident(input.sourceEntityType, input.sourceEntityId, input.residentId, context.nursingHomeId)) throw new Error("Source reference is outside the resident or home scope."); };
function append(state: StrengthPreferenceState, record: ResidentStrength | ResidentPreference, action: string, eventType: StrengthPreferenceEvent["eventType"], context: StrengthPreferenceContext, previousValue?: unknown) {
  const recordType = "abilityLevel" in record ? "strength" : "preference";
  state.audit.push({ id: `sp-audit:${record.id}:${state.audit.length + 1}`, recordType, recordId: record.id, action, residentId: record.residentId, nursingHomeId: record.nursingHomeId, rltDomainId: record.rltDomainId, previousValue, newValue: record, source: record.source, reason: record.changeReasonText || record.changeReasonCode, effectiveAt: record.effectiveFrom, recordedAt: context.occurredAt, actorUserAccountId: context.userAccountId });
  state.events.push({ id: `sp-event:${record.id}:${state.events.length + 1}`, eventType, eventVersion: 1, residentId: record.residentId, nursingHomeId: record.nursingHomeId, wardId: record.wardId, rltDomainId: record.rltDomainId, recordId: record.id, category: record.category, source: record.source, actorUserAccountId: context.userAccountId, occurredAt: context.occurredAt, recordedAt: context.occurredAt, correlationId: context.correlationId, safeSummary: `${recordType}:${record.category}:${action}` });
}
function contributorRequired(source: string) { return source === "family" || source === "nominated_representative"; }
function validateStrength(input: CreateStrengthInput, context: StrengthPreferenceContext) {
  validateScope(input.residentId, context); domainFor(input.rltDomainId); validateSourceReference(input, context);
  if (!STRENGTH_CATEGORIES.includes(input.category) || !ABILITY_LEVELS.includes(input.abilityLevel)) throw new Error("Strength category or ability level is invalid.");
  if (!input.title.trim() || !input.description.trim()) throw new Error("Strength title and description are required.");
  if (!validDate(input.effectiveFrom) || (input.reviewDate && !validDate(input.reviewDate))) throw new Error("Strength dates are invalid.");
  if (input.changeReasonCode === "other" && !input.changeReasonText?.trim()) throw new Error("Change reason text is required for other.");
  if (input.source === "other" && !input.contributorRelationship?.trim()) throw new Error("Other strength source requires details.");
  if (contributorRequired(input.source) && (!input.contributorName?.trim() || !input.contributorRelationship?.trim())) throw new Error("Contributor name and relationship are required.");
}
function validatePreference(input: CreatePreferenceInput, context: StrengthPreferenceContext) {
  validateScope(input.residentId, context); domainFor(input.rltDomainId); validateSourceReference(input, context);
  if (!PREFERENCE_CATEGORY_DOMAINS[input.category]?.includes(input.rltDomainId)) throw new Error("Preference category is not valid for this RLT domain.");
  if (!input.title.trim() || !input.preference.trim()) throw new Error("Preference title and detail are required.");
  if (!validDate(input.effectiveFrom) || (input.reviewDate && !validDate(input.reviewDate))) throw new Error("Preference dates are invalid.");
  if (input.residentOwnWords && !input.statedByResident) throw new Error("Resident's Own Words cannot contain third-party wording.");
  if (input.source === "resident" && !input.statedByResident) throw new Error("Resident-sourced preferences must be stated by the resident.");
  if ((contributorRequired(input.source) || !input.statedByResident) && (!input.contributorName?.trim() || !input.contributorRelationship?.trim())) throw new Error("Contributor name and relationship are required.");
  if (["partially_accommodated", "cannot_accommodate"].includes(input.accommodationStatus) && !input.accommodationReason?.trim()) throw new Error("Accommodation reason is required when not fully accommodated.");
  if (input.safetyReviewRequired && input.safetyReviewStatus === "not_required") throw new Error("Safety review status must reflect the required review.");
  if (input.category === "other" && !input.contextOrConditions?.trim()) throw new Error("Other preference category requires details.");
  if (input.source === "other" && !input.contributorRelationship?.trim()) throw new Error("Other preference source requires details.");
  if (input.changeReasonCode === "other" && !input.changeReasonText?.trim()) throw new Error("Change reason text is required for other.");
}
export function findProbableStrengthDuplicate(state: StrengthPreferenceState, input: CreateStrengthInput) { return state.strengths.find((item) => item.status === "current" && item.residentId === input.residentId && item.rltDomainId === input.rltDomainId && item.category === input.category && clean(item.title) === clean(input.title) && clean(item.description) === clean(input.description)); }
export function findProbablePreferenceDuplicate(state: StrengthPreferenceState, input: CreatePreferenceInput) { return state.preferences.find((item) => item.status === "current" && item.residentId === input.residentId && item.rltDomainId === input.rltDomainId && item.category === input.category && item.applicability === input.applicability && clean(item.title) === clean(input.title) && clean(item.preference) === clean(input.preference)); }

export function createResidentStrength(state: StrengthPreferenceState, input: CreateStrengthInput, context: StrengthPreferenceContext) {
  requireCapability(context, "resident_strength.create"); validateStrength(input, context);
  const duplicate = findProbableStrengthDuplicate(state, input); if (duplicate && !input.intentionalDuplicate) throw new Error(`Probable duplicate strength:${duplicate.id}`);
  const domain = domainFor(input.rltDomainId); const id = `strength:${stable(input.residentId)}:${domain.key}:${Date.parse(context.occurredAt)}:${state.strengths.length + 1}`;
  const record: ResidentStrength = { ...input, id, nursingHomeId: context.nursingHomeId, wardId: context.wardId, rltDomainKey: domain.key, status: "current", recordedByUserAccountId: context.userAccountId, recordedByStaffMemberId: context.staffMemberId, createdAt: context.occurredAt, updatedAt: context.occurredAt, versionNumber: 1, versionChainId: id };
  delete (record as ResidentStrength & { intentionalDuplicate?: boolean }).intentionalDuplicate; state.strengths.push(record); append(state, record, "created", "ResidentStrengthRecorded", context); return record;
}
export function updateResidentStrength(state: StrengthPreferenceState, id: string, input: CreateStrengthInput, context: StrengthPreferenceContext) {
  requireCapability(context, "resident_strength.edit"); validateStrength(input, context); const previous = state.strengths.find((item) => item.id === id && item.status === "current" && item.nursingHomeId === context.nursingHomeId); if (!previous) throw new Error("Current strength not found in scope.");
  previous.status = "superseded"; previous.effectiveTo = input.effectiveFrom; previous.updatedAt = context.occurredAt;
  const next: ResidentStrength = { ...previous, ...input, id: `strength:${stable(input.residentId)}:${previous.versionChainId}:${previous.versionNumber + 1}`, nursingHomeId: context.nursingHomeId, wardId: context.wardId, rltDomainKey: domainFor(input.rltDomainId).key, status: "current", effectiveTo: undefined, previousVersionId: previous.id, versionNumber: previous.versionNumber + 1, versionChainId: previous.versionChainId, recordedByUserAccountId: context.userAccountId, recordedByStaffMemberId: context.staffMemberId, createdAt: context.occurredAt, updatedAt: context.occurredAt };
  delete (next as ResidentStrength & { intentionalDuplicate?: boolean }).intentionalDuplicate; state.strengths.push(next); append(state, next, "updated", "ResidentStrengthChanged", context, previous); return next;
}
export function reviewResidentStrength(state: StrengthPreferenceState, id: string, input: { decision: "confirmed" | "updated" | "superseded" | "inactive"; comments?: string; nextReviewDate?: string }, context: StrengthPreferenceContext) {
  requireCapability(context, "resident_strength.review"); const record = state.strengths.find((item) => item.id === id && item.status === "current" && item.nursingHomeId === context.nursingHomeId); if (!record) throw new Error("Current strength not found in scope."); if (input.nextReviewDate && !validDate(input.nextReviewDate)) throw new Error("Review date is invalid.");
  state.reviews.push({ id: `sp-review:${id}:${state.reviews.length + 1}`, recordType: "strength", recordId: id, ...input, reviewedAt: context.occurredAt, reviewedByUserAccountId: context.userAccountId }); record.lastReviewedAt = context.occurredAt; record.reviewDate = input.nextReviewDate || record.reviewDate; record.updatedAt = context.occurredAt; if (input.decision === "inactive" || input.decision === "superseded") { record.status = input.decision === "inactive" ? "inactive" : "superseded"; record.effectiveTo = context.occurredAt; } append(state, record, "reviewed", input.decision === "superseded" ? "ResidentStrengthSuperseded" : "ResidentStrengthReviewed", context); return record;
}
export const supersedeResidentStrength = (state: StrengthPreferenceState, id: string, input: CreateStrengthInput, context: StrengthPreferenceContext) => updateResidentStrength(state, id, input, context);
export function inactivateResidentStrength(state: StrengthPreferenceState, id: string, reason: string, context: StrengthPreferenceContext) { if (!reason.trim()) throw new Error("Inactivation reason is required."); return reviewResidentStrength(state, id, { decision: "inactive", comments: reason }, context); }

export function createResidentPreference(state: StrengthPreferenceState, input: CreatePreferenceInput, context: StrengthPreferenceContext) {
  requireCapability(context, "resident_preference.create"); validatePreference(input, context); const duplicate = findProbablePreferenceDuplicate(state, input); if (duplicate && !input.intentionalDuplicate) throw new Error(`Probable duplicate preference:${duplicate.id}`);
  const domain = domainFor(input.rltDomainId); const id = `preference:${stable(input.residentId)}:${domain.key}:${Date.parse(context.occurredAt)}:${state.preferences.length + 1}`;
  const record: ResidentPreference = { ...input, id, nursingHomeId: context.nursingHomeId, wardId: context.wardId, rltDomainKey: domain.key, status: "current", recordedByUserAccountId: context.userAccountId, recordedByStaffMemberId: context.staffMemberId, createdAt: context.occurredAt, updatedAt: context.occurredAt, versionNumber: 1, versionChainId: id };
  delete (record as ResidentPreference & { intentionalDuplicate?: boolean }).intentionalDuplicate; state.preferences.push(record); append(state, record, "created", "ResidentPreferenceRecorded", context); return record;
}
export function updateResidentPreference(state: StrengthPreferenceState, id: string, input: CreatePreferenceInput, context: StrengthPreferenceContext) {
  requireCapability(context, "resident_preference.edit"); validatePreference(input, context); const previous = state.preferences.find((item) => item.id === id && item.status === "current" && item.nursingHomeId === context.nursingHomeId); if (!previous) throw new Error("Current preference not found in scope.");
  previous.status = "superseded"; previous.effectiveTo = input.effectiveFrom; previous.updatedAt = context.occurredAt;
  const next: ResidentPreference = { ...previous, ...input, id: `preference:${stable(input.residentId)}:${previous.versionChainId}:${previous.versionNumber + 1}`, nursingHomeId: context.nursingHomeId, wardId: context.wardId, rltDomainKey: domainFor(input.rltDomainId).key, status: "current", effectiveTo: undefined, previousVersionId: previous.id, versionNumber: previous.versionNumber + 1, versionChainId: previous.versionChainId, recordedByUserAccountId: context.userAccountId, recordedByStaffMemberId: context.staffMemberId, createdAt: context.occurredAt, updatedAt: context.occurredAt };
  delete (next as ResidentPreference & { intentionalDuplicate?: boolean }).intentionalDuplicate; state.preferences.push(next); append(state, next, "updated", "ResidentPreferenceChanged", context, previous); return next;
}
export function reviewResidentPreference(state: StrengthPreferenceState, id: string, input: { decision: "confirmed" | "updated" | "superseded" | "inactive"; comments?: string; accommodationStatus?: PreferenceAccommodationStatus; nextReviewDate?: string }, context: StrengthPreferenceContext) {
  requireCapability(context, "resident_preference.review"); const record = state.preferences.find((item) => item.id === id && item.status === "current" && item.nursingHomeId === context.nursingHomeId); if (!record) throw new Error("Current preference not found in scope.");
  state.reviews.push({ id: `sp-review:${id}:${state.reviews.length + 1}`, recordType: "preference", recordId: id, decision: input.decision, comments: input.comments, nextReviewDate: input.nextReviewDate, reviewedAt: context.occurredAt, reviewedByUserAccountId: context.userAccountId }); record.lastReviewedAt = context.occurredAt; record.reviewDate = input.nextReviewDate || record.reviewDate; if (input.accommodationStatus) record.accommodationStatus = input.accommodationStatus; if (input.decision === "inactive" || input.decision === "superseded") { record.status = input.decision === "inactive" ? "inactive" : "superseded"; record.effectiveTo = context.occurredAt; } record.updatedAt = context.occurredAt; append(state, record, "reviewed", input.decision === "superseded" ? "ResidentPreferenceSuperseded" : "ResidentPreferenceReviewed", context); return record;
}
export const supersedeResidentPreference = (state: StrengthPreferenceState, id: string, input: CreatePreferenceInput, context: StrengthPreferenceContext) => updateResidentPreference(state, id, input, context);
export function inactivateResidentPreference(state: StrengthPreferenceState, id: string, reason: string, context: StrengthPreferenceContext) { if (!reason.trim()) throw new Error("Inactivation reason is required."); return reviewResidentPreference(state, id, { decision: "inactive", comments: reason }, context); }

export function recordPreferenceAccommodation(state: StrengthPreferenceState, id: string, input: { status: PreferenceAccommodationStatus; reason?: string; agreedAlternative?: string; residentInvolved: boolean; representativeInvolved: boolean; reviewDate?: string }, context: StrengthPreferenceContext) {
  requireCapability(context, "resident_preference.manage_accommodation"); const record = state.preferences.find((item) => item.id === id && item.status === "current" && item.nursingHomeId === context.nursingHomeId); if (!record) throw new Error("Current preference not found in scope."); if (["partially_accommodated", "cannot_accommodate"].includes(input.status) && !input.reason?.trim()) throw new Error("Accommodation reason is required.");
  const previous = { status: record.accommodationStatus, reason: record.accommodationReason, alternative: record.agreedAlternative }; record.accommodationStatus = input.status; record.accommodationReason = input.reason; record.agreedAlternative = input.agreedAlternative; record.reviewDate = input.reviewDate || record.reviewDate; record.updatedAt = context.occurredAt; append(state, record, "accommodation_changed", "ResidentPreferenceAccommodationChanged", context, previous); return record;
}
export const updatePreferenceAccommodation = recordPreferenceAccommodation;
export function recordAgreedAlternative(state: StrengthPreferenceState, id: string, alternative: string, context: StrengthPreferenceContext) { const record = state.preferences.find((item) => item.id === id); if (!record) throw new Error("Preference not found."); return recordPreferenceAccommodation(state, id, { status: record.accommodationStatus, reason: record.accommodationReason, agreedAlternative: alternative, residentInvolved: true, representativeInvolved: false }, context); }
export function requestPreferenceSafetyReview(state: StrengthPreferenceState, id: string, input: { reason: string; clinicalConcern: string; residentInvolved: boolean; representativeInvolved: boolean; reviewDate?: string; linkedRiskId?: string; linkedCarePlanId?: string }, context: StrengthPreferenceContext) {
  requireCapability(context, "resident_preference.manage_safety_review"); const record = state.preferences.find((item) => item.id === id && item.status === "current" && item.nursingHomeId === context.nursingHomeId); if (!record) throw new Error("Current preference not found in scope."); if (!input.reason.trim() || !input.clinicalConcern.trim()) throw new Error("Safety-review reason and clinical concern are required.");
  const review: PreferenceSafetyReview = { id: `preference-safety:${id}:${state.safetyReviews.length + 1}`, preferenceId: id, residentId: record.residentId, nursingHomeId: record.nursingHomeId, status: "pending", requestedAt: context.occurredAt, ...input }; state.safetyReviews.push(review); record.safetyReviewRequired = true; record.safetyReviewStatus = "pending"; append(state, record, "safety_review_requested", "ResidentPreferenceSafetyReviewRequested", context); return review;
}
export function resolvePreferenceSafetyReview(state: StrengthPreferenceState, id: string, input: { decision: string; mitigation: string; residentInvolved: boolean; representativeInvolved: boolean; reviewDate?: string; cannotFullyAccommodate?: boolean }, context: StrengthPreferenceContext) {
  requireCapability(context, "resident_preference.manage_safety_review"); const review = state.safetyReviews.find((item) => item.id === id && item.status === "pending" && item.nursingHomeId === context.nursingHomeId); if (!review) throw new Error("Open safety review not found in scope."); if (!input.decision.trim() || !input.mitigation.trim()) throw new Error("Safety-review decision and mitigation are required."); const record = state.preferences.find((item) => item.id === review.preferenceId)!; Object.assign(review, input, { status: "resolved", resolvedAt: context.occurredAt, reviewerUserAccountId: context.userAccountId }); record.safetyReviewStatus = input.cannotFullyAccommodate ? "cannot_fully_accommodate" : "reviewed"; record.updatedAt = context.occurredAt; append(state, record, "safety_review_resolved", "ResidentPreferenceSafetyReviewResolved", context); return review;
}
export function createPreferenceConflict(state: StrengthPreferenceState, input: Omit<PreferenceConflict, "id" | "nursingHomeId" | "status" | "createdAt" | "createdByUserAccountId">, context: StrengthPreferenceContext) {
  requireCapability(context, "resident_preference.resolve_conflict"); validateScope(input.residentId, context); if (input.preferenceIds.length < 1 || !input.summary.trim()) throw new Error("Conflict preferences and summary are required."); const records = input.preferenceIds.map((id) => state.preferences.find((item) => item.id === id)); if (records.some((item) => !item || item.residentId !== input.residentId || item.nursingHomeId !== context.nursingHomeId)) throw new Error("Conflict preference is outside the resident or home scope.");
  const conflict: PreferenceConflict = { ...input, id: `preference-conflict:${stable(input.residentId)}:${state.conflicts.length + 1}`, nursingHomeId: context.nursingHomeId, status: "open", createdAt: context.occurredAt, createdByUserAccountId: context.userAccountId }; state.conflicts.push(conflict); const record = records[0]!; append(state, record!, "conflict_created", "ResidentPreferenceConflictRaised", context); return conflict;
}
export function resolvePreferenceConflict(state: StrengthPreferenceState, id: string, input: { resolutionSummary: string; agreedOutcome: string }, context: StrengthPreferenceContext) { requireCapability(context, "resident_preference.resolve_conflict"); const conflict = state.conflicts.find((item) => item.id === id && item.status !== "resolved" && item.nursingHomeId === context.nursingHomeId); if (!conflict) throw new Error("Open conflict not found in scope."); if (!input.resolutionSummary.trim() || !input.agreedOutcome.trim()) throw new Error("Conflict resolution and agreed outcome are required."); Object.assign(conflict, input, { status: "resolved", resolvedAt: context.occurredAt, resolvedByUserAccountId: context.userAccountId }); const record = state.preferences.find((item) => item.id === conflict.preferenceIds[0]); if (record) append(state, record, "conflict_resolved", "ResidentPreferenceConflictResolved", context); return conflict; }

const effective = (item: { effectiveFrom: string; effectiveTo?: string }, at: string) => Date.parse(item.effectiveFrom) <= Date.parse(at) && (!item.effectiveTo || Date.parse(item.effectiveTo) > Date.parse(at));
export function getCurrentResidentStrengths(state: StrengthPreferenceState, residentId: string, filters: { nursingHomeId: string; rltDomainId?: RltDomainId; category?: ResidentStrengthCategory; at?: string }) { const at = filters.at || new Date().toISOString(); return state.strengths.filter((item) => item.residentId === residentId && item.nursingHomeId === filters.nursingHomeId && item.status === "current" && effective(item, at) && (!filters.rltDomainId || item.rltDomainId === filters.rltDomainId) && (!filters.category || item.category === filters.category)).sort((a, b) => RLT_DOMAIN_BY_ID[a.rltDomainId].displayOrder - RLT_DOMAIN_BY_ID[b.rltDomainId].displayOrder || a.title.localeCompare(b.title)); }
export function getResidentStrengthsByDomain(state: StrengthPreferenceState, residentId: string, rltDomainId: RltDomainId, nursingHomeId: string) { return getCurrentResidentStrengths(state, residentId, { nursingHomeId, rltDomainId }); }
export function getResidentStrengthHistory(state: StrengthPreferenceState, residentId: string, filters: { nursingHomeId: string; rltDomainId?: RltDomainId } = { nursingHomeId: "" }, pagination = { offset: 0, limit: 50 }) { return state.strengths.filter((item) => item.residentId === residentId && item.nursingHomeId === filters.nursingHomeId && (!filters.rltDomainId || item.rltDomainId === filters.rltDomainId)).sort((a, b) => b.updatedAt.localeCompare(a.updatedAt)).slice(pagination.offset, pagination.offset + pagination.limit); }
function canSeePreference(item: ResidentPreference, capabilities: string[]) { return capabilities.includes("resident_preference.view") && (item.sensitivity === "standard" || (item.sensitivity === "sensitive" && capabilities.includes("resident_preference.view_sensitive")) || (item.sensitivity === "highly_sensitive" && capabilities.includes("resident_preference.view_highly_sensitive"))); }
export function getCurrentResidentPreferences(state: StrengthPreferenceState, residentId: string, filters: { nursingHomeId: string; capabilities: string[]; rltDomainId?: RltDomainId; category?: ResidentPreferenceCategory; importance?: PreferenceImportance; accommodationStatus?: PreferenceAccommodationStatus; at?: string }) { const at = filters.at || new Date().toISOString(); const rank = { essential: 0, important: 1, routine: 2 }; return state.preferences.filter((item) => item.residentId === residentId && item.nursingHomeId === filters.nursingHomeId && item.status === "current" && effective(item, at) && canSeePreference(item, filters.capabilities) && (!filters.rltDomainId || item.rltDomainId === filters.rltDomainId) && (!filters.category || item.category === filters.category) && (!filters.importance || item.importance === filters.importance) && (!filters.accommodationStatus || item.accommodationStatus === filters.accommodationStatus)).sort((a, b) => rank[a.importance] - rank[b.importance] || Number(b.safetyReviewStatus === "pending") - Number(a.safetyReviewStatus === "pending") || RLT_DOMAIN_BY_ID[a.rltDomainId].displayOrder - RLT_DOMAIN_BY_ID[b.rltDomainId].displayOrder || a.title.localeCompare(b.title)); }
export function getResidentPreferencesByDomain(state: StrengthPreferenceState, residentId: string, rltDomainId: RltDomainId, nursingHomeId: string, capabilities: string[]) { return getCurrentResidentPreferences(state, residentId, { nursingHomeId, capabilities, rltDomainId }); }
export function getResidentPreferenceHistory(state: StrengthPreferenceState, residentId: string, filters: { nursingHomeId: string; capabilities: string[]; rltDomainId?: RltDomainId }, pagination = { offset: 0, limit: 50 }) { requireHistoryCapability(filters.capabilities); return state.preferences.filter((item) => item.residentId === residentId && item.nursingHomeId === filters.nursingHomeId && canSeePreference(item, filters.capabilities) && (!filters.rltDomainId || item.rltDomainId === filters.rltDomainId)).sort((a, b) => b.updatedAt.localeCompare(a.updatedAt)).slice(pagination.offset, pagination.offset + pagination.limit); }
const requireHistoryCapability = (capabilities: string[]) => { if (!capabilities.includes("resident_preference.view_history")) throw new Error("Missing capability: resident_preference.view_history"); };

export interface ResidentStrengthPreferenceCareSummary { residentId: string; domainId: RltDomainId; strengths: Array<Pick<ResidentStrength, "id" | "title" | "description" | "abilityLevel" | "supportThatHelps">>; preferences: Array<Pick<ResidentPreference, "id" | "title" | "preference" | "importance" | "avoid" | "accommodationStatus">>; alerts: Array<{ type: "safety_review" | "not_accommodated" | "conflict"; label: string }>; }
export function getPointOfCarePreferences(state: StrengthPreferenceState, residentId: string, workType: "communication" | "eating_drinking" | "personal_care" | "mobilising" | "sleeping", context: { nursingHomeId: string; capabilities: string[] }) {
  const domains: Record<typeof workType, RltDomainId> = { communication: "communication", eating_drinking: "eating_drinking", personal_care: "personal_cleansing_dressing", mobilising: "mobilisation", sleeping: "sleeping" }; const domainId = domains[workType];
  const strengths = getResidentStrengthsByDomain(state, residentId, domainId, context.nursingHomeId).map(({ id, title, description, abilityLevel, supportThatHelps }) => ({ id, title, description, abilityLevel, supportThatHelps }));
  const preferences = getResidentPreferencesByDomain(state, residentId, domainId, context.nursingHomeId, context.capabilities).map(({ id, title, preference, importance, avoid, accommodationStatus }) => ({ id, title, preference, importance, avoid, accommodationStatus }));
  const ids = new Set(preferences.map((item) => item.id)); const alerts: ResidentStrengthPreferenceCareSummary["alerts"] = []; for (const item of state.preferences.filter((candidate) => ids.has(candidate.id))) { if (item.safetyReviewStatus === "pending") alerts.push({ type: "safety_review", label: "Safety review required" }); if (item.accommodationStatus === "cannot_accommodate") alerts.push({ type: "not_accommodated", label: "Preference cannot currently be accommodated" }); } if (state.conflicts.some((item) => item.residentId === residentId && item.status !== "resolved" && item.preferenceIds.some((id) => ids.has(id)))) alerts.push({ type: "conflict", label: "Preference conflict under review" }); return { residentId, domainId, strengths, preferences, alerts };
}
export interface ResidentStrengthPreferenceSummary { residentId: string; preferredName?: string; keyStrengths: Array<{ domainId: RltDomainId; title: string }>; essentialPreferences: Array<{ domainId: RltDomainId; title: string; preference: string }>; pleaseAvoid: string[]; reviewRequiredCount: number; safetyReviewRequiredCount: number; conflictCount: number; domainCounts: Array<{ domainId: RltDomainId; strengthCount: number; preferenceCount: number }>; }
export function getResidentStrengthPreferenceSummary(state: StrengthPreferenceState, residentId: string, nursingHomeId: string, capabilities: string[]): ResidentStrengthPreferenceSummary { const strengths = getCurrentResidentStrengths(state, residentId, { nursingHomeId }); const preferences = getCurrentResidentPreferences(state, residentId, { nursingHomeId, capabilities }); const preferredName = preferences.find((item) => item.category === "preferred_name")?.preference; return { residentId, preferredName, keyStrengths: strengths.slice(0, 6).map((item) => ({ domainId: item.rltDomainId, title: item.title })), essentialPreferences: preferences.filter((item) => item.importance === "essential").slice(0, 6).map((item) => ({ domainId: item.rltDomainId, title: item.title, preference: item.preference })), pleaseAvoid: preferences.flatMap((item) => item.avoid).slice(0, 8), reviewRequiredCount: [...strengths, ...preferences].filter((item) => item.reviewDate && Date.parse(item.reviewDate) <= Date.now()).length, safetyReviewRequiredCount: preferences.filter((item) => item.safetyReviewStatus === "pending").length, conflictCount: state.conflicts.filter((item) => item.residentId === residentId && item.nursingHomeId === nursingHomeId && item.status !== "resolved").length, domainCounts: RLT_DOMAINS.map((domain) => ({ domainId: domain.id, strengthCount: strengths.filter((item) => item.rltDomainId === domain.id).length, preferenceCount: preferences.filter((item) => item.rltDomainId === domain.id).length })) }; }

export function projectStrengthPreferenceToWorkItems(state: StrengthPreferenceState, now: string, timeZone: string): WorkItem[] { const make = (id: string, residentId: string, nursingHomeId: string, wardId: string | undefined, domainId: RltDomainId, title: string, sourceEntityType: string, priority: "important" | "urgent" = "important"): WorkItem => ({ id: `work:strength-preference:${id}`, workType: "documentation", title, source: { sourceType: "clinical_rule", sourceModule: "documentation", sourceEntityType, sourceEntityId: id, route: `/residents/${residentId}?rltDomainId=${domainId}`, completionOwner: "resident_strength_preference_service", recreationPolicy: "deterministic", createdAt: now }, nursingHomeId, wardId, residentId, schedule: { scheduleType: "triggered", dueAt: now, effectiveDueAt: now, originalDueAt: now, timeZone }, persistedStatus: "scheduled", assignment: { assignmentType: "role", assignedRoleKey: priority === "urgent" ? "cnm" : "nurse", assignedWardId: wardId, assignmentStatus: "active", assignedAt: now }, priority, careContext: { rltDomainId: domainId }, createdAt: now, updatedAt: now, schemaVersion: 1 }); const work: WorkItem[] = []; for (const review of state.safetyReviews.filter((item) => item.status === "pending")) { const p = state.preferences.find((item) => item.id === review.preferenceId); if (p) work.push(make(review.id, p.residentId, p.nursingHomeId, p.wardId, p.rltDomainId, "Review resident preference safety", "preference_safety_review", "urgent")); } for (const conflict of state.conflicts.filter((item) => item.status !== "resolved")) { const p = state.preferences.find((item) => item.id === conflict.preferenceIds[0]); if (p) work.push(make(conflict.id, p.residentId, p.nursingHomeId, p.wardId, p.rltDomainId, "Resolve resident preference conflict", "preference_conflict", "urgent")); } for (const p of state.preferences.filter((item) => item.status === "current" && item.importance === "essential" && item.accommodationStatus === "cannot_accommodate")) work.push(make(`unaccommodated:${p.id}`, p.residentId, p.nursingHomeId, p.wardId, p.rltDomainId, "Review unaccommodated essential preference", "resident_preference", "urgent")); return work; }

export function mapLegacyStrengthPreference(input: { id: string; residentId: string; nursingHomeId: string; text: string }) { const text = clean(input.text); if (/pureed diet|two staff transfer|required/.test(text)) return { status: "clinical_requirement" as const, sourceId: input.id }; if (/prefers to be called/.test(text)) return { status: "mapped" as const, recordType: "preference" as const, rltDomainId: "communication" as const, category: "preferred_name" as const, sourceId: input.id }; if (/likes porridge for breakfast/.test(text)) return { status: "mapped" as const, recordType: "preference" as const, rltDomainId: "eating_drinking" as const, category: "food" as const, sourceId: input.id }; if (/washes face independently/.test(text)) return { status: "mapped" as const, recordType: "strength" as const, rltDomainId: "personal_cleansing_dressing" as const, category: "self_care" as const, sourceId: input.id }; if (/likes to participate in transfer/.test(text)) return { status: "mapped" as const, recordType: "strength" as const, rltDomainId: "mobilisation" as const, category: "mobility" as const, sourceId: input.id }; return { status: "manual_review" as const, sourceId: input.id }; }

export function validateStrengthPreferenceState(state: StrengthPreferenceState, residentHomeById: Record<string, string>) { const issues: string[] = []; for (const item of [...state.strengths, ...state.preferences]) { if (residentHomeById[item.residentId] !== item.nursingHomeId) issues.push(`Invalid scope:${item.id}`); if (!RLT_DOMAIN_BY_ID[item.rltDomainId]?.active) issues.push(`Invalid domain:${item.id}`); } for (const chainId of new Set([...state.strengths, ...state.preferences].map((item) => item.versionChainId))) { const current = [...state.strengths, ...state.preferences].filter((item) => item.versionChainId === chainId && item.status === "current"); if (current.length > 1) issues.push(`Multiple current versions:${chainId}`); } for (const item of state.preferences) { if (!PREFERENCE_CATEGORY_DOMAINS[item.category].includes(item.rltDomainId)) issues.push(`Invalid preference category/domain:${item.id}`); if (["partially_accommodated", "cannot_accommodate"].includes(item.accommodationStatus) && !item.accommodationReason?.trim()) issues.push(`Missing accommodation reason:${item.id}`); if (item.residentOwnWords && !item.statedByResident) issues.push(`Third-party resident words:${item.id}`); } return { valid: issues.length === 0, issues, counts: { strengths: state.strengths.length, preferences: state.preferences.length, reviews: state.reviews.length, safetyReviews: state.safetyReviews.length, conflicts: state.conflicts.length, audit: state.audit.length, events: state.events.length } }; }
