import { getApprovedRltDomainsForAssessmentRecord } from "./assessmentRltMappings";
import { RLT_DEPENDENCY_LEVELS, type RltDependencyState } from "./rltDependency";
import { RLT_DOMAIN_BY_ID, getRltDomainForCarePlanProblem, getRltDomainsForRisk, type RltDomainId, type RltDomainKey } from "./rlt";
import type { StrengthPreferenceState } from "./residentStrengthPreferences";
import type { EndOfLifeState } from "./endOfLifePathway";
import type { Alert, Assessment, CarePlanProblem, ClinicalAlert, HandoverNote, Incident, ProblemEvaluation, ProblemHistoryEntry, ProblemIntervention, ProblemInterventionLog, ProblemReview, Resident, TimelineEvent } from "./types";

export type RltTimelineEventType = "assessment_completed" | "assessment_risk_changed" | "care_plan_created" | "care_plan_updated" | "care_plan_reviewed" | "care_plan_inactivated" | "care_action_completed" | "care_action_missed" | "dependency_changed" | "strength_changed" | "preference_changed" | "risk_opened" | "risk_escalated" | "risk_resolved" | "incident_recorded" | "observation_recorded" | "clinical_deterioration" | "clinical_improvement" | "hospital_transfer" | "hospital_return" | "handover_created" | "daily_care_exception" | "rule_issue_opened" | "rule_issue_resolved" | "other";
export type RltClinicalDirection = "improved" | "deteriorated" | "unchanged" | "new_issue" | "resolved" | "not_applicable";
export type RltTimelineSeverity = "information" | "low" | "medium" | "high" | "critical";
export interface RltTimelineDomainTag { rltDomainId: RltDomainId; rltDomainKey: RltDomainKey; displayName: string; mappingSource: "explicit" | "care_plan_domain" | "approved_assessment_mapping" | "approved_risk_mapping" | "manual_clinical_tag" | "legacy_mapping"; }
export interface RltTimelineItem { id: string; residentId: string; nursingHomeId: string; eventType: RltTimelineEventType; occurredAt: string; recordedAt?: string; title: string; summary: string; rltDomains: RltTimelineDomainTag[]; clinicalDirection?: RltClinicalDirection; severity?: RltTimelineSeverity; source: { sourceModule: string; sourceEntityType: string; sourceEntityId: string; route?: string }; actor?: { staffMemberId?: string; displayName?: string; roleLabel?: string }; correlationId?: string; sensitivity: "standard" | "sensitive" | "highly_sensitive"; importance: "routine" | "important" | "high"; }
export interface RltTimelineFilters { rltDomainIds?: RltDomainId[]; eventTypes?: RltTimelineEventType[]; clinicalDirection?: Exclude<RltClinicalDirection, "not_applicable">[]; severity?: RltTimelineSeverity[]; dateFrom?: string; dateTo?: string; sourceModules?: string[]; importantOnly?: boolean; }
export interface RltTimelinePage { items: RltTimelineItem[]; total: number; offset: number; limit: number; hasMore: boolean; }
export interface RltTimelineInclusionDecision { include: boolean; importance: "routine" | "important" | "high"; reason: string; }
export interface RltEventDomainTag { id: string; residentId: string; nursingHomeId: string; sourceEntityType: string; sourceEntityId: string; rltDomainId: RltDomainId; taggedByUserAccountId: string; taggedByStaffMemberId?: string; taggedAt: string; reason?: string; status: "active" | "removed"; }
export interface RltManualTagAudit { id: string; tagId: string; action: "tagged" | "removed"; residentId: string; nursingHomeId: string; actorUserAccountId: string; occurredAt: string; reason?: string; }
export interface RltTimelineTagState { tags: RltEventDomainTag[]; audit: RltManualTagAudit[]; }
export const EMPTY_RLT_TIMELINE_TAG_STATE: RltTimelineTagState = { tags: [], audit: [] };
export interface RltTimelineAuthorizationContext { nursingHomeId: string; capabilities: string[]; }
export interface RltTimelineTagContext extends RltTimelineAuthorizationContext { userAccountId: string; staffMemberId?: string; occurredAt: string; residentExists: (id: string) => boolean; residentBelongsToHome: (id: string, homeId: string) => boolean; }
export interface RltTimelineData { residents: Resident[]; assessments: Assessment[]; carePlanProblems: CarePlanProblem[]; interventions: ProblemIntervention[]; interventionLogs: ProblemInterventionLog[]; evaluations: ProblemEvaluation[]; reviews: ProblemReview[]; problemHistory: ProblemHistoryEntry[]; dependencyState: RltDependencyState; strengthPreferenceState: StrengthPreferenceState; endOfLifeState?: EndOfLifeState; incidents: Incident[]; alerts?: Alert[]; clinicalAlerts?: ClinicalAlert[]; handovers?: HandoverNote[]; timelineEvents?: TimelineEvent[]; manualTagState?: RltTimelineTagState; }

const concise = (value: string, length = 220) => value.length > length ? `${value.slice(0, length - 1).trim()}…` : value;
const stable = (value: string) => value.replace(/[^a-zA-Z0-9_-]+/g, "-").toLowerCase();
const titleCase = (value: string) => value.replace(/_/g, " ").replace(/\b\w/g, (character) => character.toUpperCase());
const domainTag = (domainId: RltDomainId, mappingSource: RltTimelineDomainTag["mappingSource"]): RltTimelineDomainTag => ({ rltDomainId: domainId, rltDomainKey: RLT_DOMAIN_BY_ID[domainId].key, displayName: RLT_DOMAIN_BY_ID[domainId].title, mappingSource });
const uniqueTags = (tags: RltTimelineDomainTag[]) => [...new Map(tags.map((tag) => [tag.rltDomainId, tag])).values()].sort((left, right) => RLT_DOMAIN_BY_ID[left.rltDomainId].displayOrder - RLT_DOMAIN_BY_ID[right.rltDomainId].displayOrder);
const severityForRisk = (value?: string): RltTimelineSeverity => value === "very_high" || value === "critical" ? "critical" : value === "high" ? "high" : value === "moderate" || value === "warning" ? "medium" : "low";
const dependencyDirection = (previous?: string, current?: string): RltClinicalDirection => { if (!previous || !current) return "new_issue"; const before = RLT_DEPENDENCY_LEVELS.indexOf(previous as never); const after = RLT_DEPENDENCY_LEVELS.indexOf(current as never); return after > before ? "deteriorated" : after < before ? "improved" : "unchanged"; };

export function decideRltTimelineInclusion(input: { eventType: RltTimelineEventType; priority?: string; outcome?: string; clinicallySignificant?: boolean; essentialPreference?: boolean; materialChange?: boolean }): RltTimelineInclusionDecision {
  if (["dependency_changed", "care_action_missed", "risk_escalated", "clinical_deterioration", "hospital_transfer", "hospital_return", "rule_issue_opened"].includes(input.eventType)) return { include: true, importance: "high", reason: "Material clinical change or required follow-up." };
  if (["assessment_completed", "assessment_risk_changed", "care_plan_created", "care_plan_updated", "care_plan_reviewed", "care_plan_inactivated", "strength_changed", "preference_changed", "risk_opened", "risk_resolved", "incident_recorded", "clinical_improvement", "rule_issue_resolved"].includes(input.eventType) && (input.materialChange !== false || input.essentialPreference)) return { include: true, importance: input.priority === "critical" || input.priority === "high" ? "high" : "important", reason: "Clinically meaningful source-record change." };
  if (input.eventType === "observation_recorded") return input.clinicallySignificant ? { include: true, importance: "high", reason: "Observation met an existing clinical-significance rule." } : { include: false, importance: "routine", reason: "Routine observation without a clinical-significance marker." };
  if (input.eventType === "care_action_completed") return input.clinicallySignificant || input.priority === "critical" || input.priority === "high" ? { include: true, importance: "important", reason: "High-priority Care Action completion." } : { include: false, importance: "routine", reason: "Routine Care Action completion." };
  if (input.eventType === "handover_created" || input.eventType === "daily_care_exception") return input.clinicallySignificant ? { include: true, importance: "important", reason: "Explicitly important clinical communication." } : { include: false, importance: "routine", reason: "Routine source record." };
  return { include: false, importance: "routine", reason: "No approved clinical inclusion rule." };
}

function manualTags(data: RltTimelineData, residentId: string, homeId: string, sourceEntityType: string, sourceEntityId: string, existing: RltTimelineDomainTag[]) {
  if (existing.length) return existing;
  return uniqueTags((data.manualTagState?.tags || []).filter((tag) => tag.status === "active" && tag.residentId === residentId && tag.nursingHomeId === homeId && tag.sourceEntityType === sourceEntityType && tag.sourceEntityId === sourceEntityId).map((tag) => domainTag(tag.rltDomainId, "manual_clinical_tag")));
}
function routeAllowed(capabilities: string[], capability: string, route: string) { return capabilities.includes(capability) ? route : undefined; }
function sensitiveAllowed(item: RltTimelineItem, capabilities: string[]) { return item.sensitivity === "standard" || item.sensitivity === "sensitive" && capabilities.includes("rlt_timeline.view_sensitive") || item.sensitivity === "highly_sensitive" && capabilities.includes("rlt_timeline.view_highly_sensitive"); }

export function projectResidentRltTimeline(data: RltTimelineData, residentId: string, authorization: RltTimelineAuthorizationContext): RltTimelineItem[] {
  if (!authorization.capabilities.includes("rlt_timeline.view")) throw new Error("Missing capability: rlt_timeline.view"); const resident = data.residents.find((item) => item.id === residentId); if (!resident) throw new Error("Resident not found."); const homeId = resident.facilityId || authorization.nursingHomeId; if (homeId !== authorization.nursingHomeId) throw new Error("Resident is outside the authorised nursing home.");
  const items: RltTimelineItem[] = [];
  const add = (item: Omit<RltTimelineItem, "id" | "importance"> & { eventId?: string; occurrenceId?: string; materialChange?: boolean; clinicallySignificant?: boolean; essentialPreference?: boolean }) => { const decision = decideRltTimelineInclusion({ eventType: item.eventType, priority: item.severity, materialChange: item.materialChange, clinicallySignificant: item.clinicallySignificant, essentialPreference: item.essentialPreference }); if (!decision.include || !item.rltDomains.length) return; const id = item.eventId || `rlt-timeline:${stable(item.source.sourceEntityType)}:${stable(item.source.sourceEntityId)}:${item.eventType}:${stable(item.occurrenceId || "source")}`; const projected: RltTimelineItem = { ...item, id, importance: decision.importance }; delete (projected as RltTimelineItem & { eventId?: string }).eventId; delete (projected as RltTimelineItem & { occurrenceId?: string }).occurrenceId; delete (projected as RltTimelineItem & { materialChange?: boolean }).materialChange; delete (projected as RltTimelineItem & { clinicallySignificant?: boolean }).clinicallySignificant; delete (projected as RltTimelineItem & { essentialPreference?: boolean }).essentialPreference; if (sensitiveAllowed(projected, authorization.capabilities)) items.push(projected); };
  for (const assessment of data.assessments.filter((item) => item.residentId === residentId && (!item.facilityId || item.facilityId === homeId) && !["deleted", "archived"].includes(item.status || ""))) {
    const tags = uniqueTags(getApprovedRltDomainsForAssessmentRecord(assessment).map((domain) => domainTag(domain.id, "approved_assessment_mapping"))); if (!tags.length) continue; const high = ["high", "very_high"].includes(assessment.riskLevel || "");
    add({ residentId, nursingHomeId: homeId, eventType: "assessment_completed", occurredAt: assessment.date, title: `${titleCase(assessment.type)} Assessment Completed`, summary: concise(`${assessment.interpretation}${assessment.riskLevel ? ` · ${titleCase(assessment.riskLevel)} risk` : ""}`), rltDomains: tags, clinicalDirection: high ? "new_issue" : "unchanged", severity: severityForRisk(assessment.riskLevel), source: { sourceModule: "assessments", sourceEntityType: "assessment", sourceEntityId: assessment.id, route: routeAllowed(authorization.capabilities, "assessment.view", `/assessments/${assessment.id}`) }, actor: { displayName: assessment.assessor }, sensitivity: "standard", materialChange: true });
  }
  for (const plan of data.carePlanProblems.filter((item) => item.residentId === residentId && (!item.facilityId || item.facilityId === homeId))) {
    const domain = getRltDomainForCarePlanProblem(plan); let tags = domain ? [domainTag(domain.id, "care_plan_domain")] : []; tags = manualTags(data, residentId, homeId, "care_plan_item", plan.id, tags); if (!tags.length) continue; const eventType: RltTimelineEventType = plan.status === "active" ? "care_plan_created" : "care_plan_inactivated";
    add({ residentId, nursingHomeId: homeId, eventType, occurredAt: plan.status === "active" ? plan.createdAt : plan.resolvedAt || plan.archivedAt || plan.createdAt, title: plan.status === "active" ? "Nursing Care Plan Created" : "Nursing Care Plan Inactivated", summary: concise(plan.problemStatement), rltDomains: tags, clinicalDirection: plan.status === "active" ? "new_issue" : "resolved", severity: severityForRisk(plan.riskLevel), source: { sourceModule: "care_plans", sourceEntityType: "care_plan_item", sourceEntityId: plan.id, route: routeAllowed(authorization.capabilities, "careplan.view", `/residents/${residentId}?carePlanProblemId=${plan.id}`) }, actor: { displayName: plan.createdBy }, sensitivity: tags.some((tag) => ["expressing_sexuality", "dying"].includes(tag.rltDomainId)) ? "sensitive" : "standard", materialChange: true });
  }
  for (const review of data.evaluations.filter((item) => data.carePlanProblems.some((plan) => plan.id === item.problemId && plan.residentId === residentId))) { const plan = data.carePlanProblems.find((item) => item.id === review.problemId)!; const domain = getRltDomainForCarePlanProblem(plan); if (!domain) continue; add({ residentId, nursingHomeId: homeId, eventType: "care_plan_reviewed", occurredAt: review.date, title: "Nursing Care Plan Reviewed", summary: concise(review.summary || titleCase(review.progress)), rltDomains: [domainTag(domain.id, "care_plan_domain")], clinicalDirection: review.progress === "improved" ? "improved" : review.progress === "deteriorated" || review.progress === "requires_revision" ? "deteriorated" : review.progress === "resolved" ? "resolved" : "unchanged", severity: review.progress === "deteriorated" ? "high" : "information", source: { sourceModule: "care_plans", sourceEntityType: "care_plan_review", sourceEntityId: review.id, route: routeAllowed(authorization.capabilities, "careplan.view", `/residents/${residentId}?carePlanProblemId=${plan.id}`) }, actor: { displayName: review.evaluatorName, roleLabel: review.role }, sensitivity: domain.id === "dying" || domain.id === "expressing_sexuality" ? "sensitive" : "standard", materialChange: true }); }
  for (const review of data.reviews.filter((item) => data.carePlanProblems.some((plan) => plan.id === item.problemId && plan.residentId === residentId))) { const plan = data.carePlanProblems.find((item) => item.id === review.problemId)!; const domain = getRltDomainForCarePlanProblem(plan); if (!domain) continue; add({ residentId, nursingHomeId: homeId, eventType: "care_plan_reviewed", occurredAt: review.reviewDate, title: "Nursing Care Plan Review Recorded", summary: concise(`${titleCase(review.outcome)}${review.comments ? ` · ${review.comments}` : ""}`), rltDomains: [domainTag(domain.id, "care_plan_domain")], clinicalDirection: review.outcome === "resolve" ? "resolved" : review.outcome === "escalate" ? "deteriorated" : "unchanged", severity: review.outcome === "escalate" ? "high" : "information", source: { sourceModule: "care_plans", sourceEntityType: "care_plan_review", sourceEntityId: review.id, route: routeAllowed(authorization.capabilities, "careplan.view", `/residents/${residentId}?carePlanProblemId=${plan.id}`) }, actor: { displayName: review.reviewedByName, roleLabel: review.role }, sensitivity: domain.id === "dying" || domain.id === "expressing_sexuality" ? "sensitive" : "standard", materialChange: true }); }
  for (const log of data.interventionLogs.filter((item) => item.residentId === residentId && ["missed", "escalated"].includes(item.outcome))) { const plan = data.carePlanProblems.find((item) => item.id === log.problemId); const intervention = data.interventions.find((item) => item.id === log.interventionId); const domain = getRltDomainForCarePlanProblem(plan); if (!plan || !domain) continue; add({ residentId, nursingHomeId: homeId, eventType: "care_action_missed", occurredAt: log.createdAt, title: log.outcome === "missed" ? "Care Action Missed" : "Care Action Escalated", summary: concise(`${intervention?.name || "Care Action"}${log.followUpRequired ? " · Follow-up required" : ""}`), rltDomains: [domainTag(domain.id, "care_plan_domain")], clinicalDirection: "deteriorated", severity: log.followUpRequired ? "high" : "medium", source: { sourceModule: "care_actions", sourceEntityType: "care_action_occurrence", sourceEntityId: log.id, route: routeAllowed(authorization.capabilities, "careplan.view", `/residents/${residentId}?carePlanProblemId=${plan.id}`) }, actor: { displayName: log.staffName, roleLabel: log.role }, occurrenceId: log.id, sensitivity: "standard", clinicallySignificant: true }); }
  for (const event of data.dependencyState.events.filter((item) => item.residentId === residentId && item.nursingHomeId === homeId)) add({ residentId, nursingHomeId: homeId, eventType: "dependency_changed", occurredAt: event.recordedAt, title: event.eventType === "RltDependencyReviewed" ? "Dependency Reviewed" : "Dependency Changed", summary: event.previousLevel ? `${titleCase(event.previousLevel)} → ${titleCase(event.currentLevel)}` : `Recorded as ${titleCase(event.currentLevel)}`, rltDomains: [domainTag(event.rltDomainId, "explicit")], clinicalDirection: dependencyDirection(event.previousLevel, event.currentLevel), severity: dependencyDirection(event.previousLevel, event.currentLevel) === "deteriorated" ? "high" : "information", source: { sourceModule: "rlt_dependency", sourceEntityType: "rlt_dependency", sourceEntityId: event.dependencyRecordId, route: `/residents/${residentId}?rltDomainId=${event.rltDomainId}` }, correlationId: event.correlationId, eventId: event.id, sensitivity: "standard", materialChange: true });
  for (const event of data.strengthPreferenceState.events.filter((item) => item.residentId === residentId && item.nursingHomeId === homeId)) { const preference = data.strengthPreferenceState.preferences.find((item) => item.id === event.recordId); const strength = data.strengthPreferenceState.strengths.find((item) => item.id === event.recordId); const isPreference = event.eventType.startsWith("ResidentPreference"); const material = isPreference ? preference?.importance === "essential" || ["ResidentPreferenceSafetyReviewRequested", "ResidentPreferenceSafetyReviewResolved", "ResidentPreferenceAccommodationChanged"].includes(event.eventType) : ["ResidentStrengthChanged", "ResidentStrengthSuperseded"].includes(event.eventType); if (!material || !event.rltDomainId) continue; add({ residentId, nursingHomeId: homeId, eventType: isPreference ? "preference_changed" : "strength_changed", occurredAt: event.occurredAt, recordedAt: event.recordedAt, title: isPreference ? "Important Resident Preference Changed" : "Resident Strength Changed", summary: isPreference ? `${preference?.title || "Preference"} · ${titleCase(event.eventType.replace("ResidentPreference", ""))}` : `${strength?.title || "Strength"} · ${titleCase(event.eventType.replace("ResidentStrength", ""))}`, rltDomains: [domainTag(event.rltDomainId, "explicit")], clinicalDirection: event.eventType.includes("Superseded") ? "resolved" : "not_applicable", severity: event.eventType.includes("SafetyReviewRequested") ? "high" : "information", source: { sourceModule: "resident_strength_preferences", sourceEntityType: isPreference ? "resident_preference" : "resident_strength", sourceEntityId: event.recordId, route: `/residents/${residentId}?rltDomainId=${event.rltDomainId}` }, actor: { displayName: event.actorUserAccountId }, correlationId: event.correlationId, eventId: event.id, sensitivity: preference?.sensitivity || (event.rltDomainId === "expressing_sexuality" ? "sensitive" : "standard"), essentialPreference: preference?.importance === "essential", materialChange: material }); }
  for (const incident of data.incidents.filter((item) => item.residentId === residentId && (!item.facilityId || item.facilityId === homeId) && item.recordStatus !== "deleted")) { let tags = uniqueTags(getRltDomainsForRisk(incident.type).map((domain) => domainTag(domain.id, "approved_risk_mapping"))); tags = manualTags(data, residentId, homeId, "incident", incident.id, tags); if (!tags.length) continue; add({ residentId, nursingHomeId: homeId, eventType: "incident_recorded", occurredAt: incident.date, title: `${titleCase(incident.type)} Incident Recorded`, summary: concise(`${titleCase(incident.severity)} severity · ${incident.followUpRequired ? "Follow-up required" : "No follow-up recorded"}`), rltDomains: tags, clinicalDirection: "new_issue", severity: incident.severity === "moderate" ? "medium" : incident.severity, source: { sourceModule: "incidents", sourceEntityType: "incident", sourceEntityId: incident.id, route: routeAllowed(authorization.capabilities, "incident.view", `/incidents`) }, actor: { displayName: incident.reportedBy }, sensitivity: incident.type === "behaviour" ? "sensitive" : "standard", materialChange: true }); }
  for (const alert of (data.clinicalAlerts || []).filter((item) => item.residentId === residentId && (!item.facilityId || item.facilityId === homeId))) { let tags = uniqueTags(getRltDomainsForRisk(alert.type).map((domain) => domainTag(domain.id, "approved_risk_mapping"))); tags = manualTags(data, residentId, homeId, "clinical_alert", alert.id, tags); if (!tags.length) continue; const resolved = Boolean(alert.resolvedAt || alert.dismissedAt); add({ residentId, nursingHomeId: homeId, eventType: resolved ? "risk_resolved" : "risk_opened", occurredAt: alert.updatedAt || alert.createdAt, title: resolved ? `${alert.title} Resolved` : alert.title, summary: resolved ? "Clinical alert reviewed and resolved." : concise(alert.message), rltDomains: tags, clinicalDirection: resolved ? "resolved" : "new_issue", severity: alert.severity === "warning" ? "medium" : alert.severity === "info" ? "information" : "critical", source: { sourceModule: "observations", sourceEntityType: "clinical_alert", sourceEntityId: alert.id, route: `/residents/${residentId}?careSection=vitals` }, sensitivity: "standard", clinicallySignificant: true, materialChange: true }); }
  for (const handover of (data.handovers || []).filter((item) => item.residentId === residentId && (!item.facilityId || item.facilityId === homeId) && item.handoverPriority !== "routine")) { const tags = manualTags(data, residentId, homeId, "handover", handover.id, []); if (!tags.length) continue; add({ residentId, nursingHomeId: homeId, eventType: "handover_created", occurredAt: handover.effectiveFrom || handover.date, title: "Important Clinical Handover", summary: concise(handover.summary), rltDomains: tags, clinicalDirection: "not_applicable", severity: handover.handoverPriority === "urgent" ? "high" : "medium", source: { sourceModule: "handovers", sourceEntityType: "handover", sourceEntityId: handover.id, route: "/handovers" }, actor: { displayName: handover.staff }, sensitivity: "sensitive", clinicallySignificant: true }); }
  for (const event of (data.endOfLifeState?.events || []).filter((item) => item.residentId === residentId && item.nursingHomeId === homeId)) { const deterioration = ["LastDaysOfLifeRecorded", "ResidentDeathRecorded"].includes(event.eventType); const completed = event.eventType === "AfterDeathCareCompleted"; add({ residentId, nursingHomeId: homeId, eventType: deterioration ? "clinical_deterioration" : completed ? "care_plan_inactivated" : "care_plan_updated", occurredAt: event.occurredAt, recordedAt: event.recordedAt, title: titleCase(event.eventType.replace(/([a-z])([A-Z])/g, "$1 $2")), summary: event.safeSummary, rltDomains: [domainTag("dying", "explicit")], clinicalDirection: deterioration ? "deteriorated" : completed ? "resolved" : "not_applicable", severity: event.eventType === "ResidentDeathRecorded" ? "critical" : deterioration ? "high" : "information", source: { sourceModule: "end_of_life", sourceEntityType: event.sourceEntityType, sourceEntityId: event.sourceEntityId, route: `/residents/${residentId}?rltDomainId=dying` }, actor: { displayName: event.actorUserAccountId }, correlationId: event.correlationId, eventId: event.id, sensitivity: event.eventType === "AdvanceCareDecisionLinked" ? "highly_sensitive" : "sensitive", materialChange: true }); }
  return [...new Map(items.map((item) => [item.id, item])).values()].sort((left, right) => right.occurredAt.localeCompare(left.occurredAt) || left.id.localeCompare(right.id));
}

export function getResidentRltTimeline(data: RltTimelineData, residentId: string, authorization: RltTimelineAuthorizationContext, filters: RltTimelineFilters = { importantOnly: true }, pagination = { offset: 0, limit: 30 }): RltTimelinePage { let items = projectResidentRltTimeline(data, residentId, authorization); if (filters.rltDomainIds?.length) items = items.filter((item) => item.rltDomains.some((tag) => filters.rltDomainIds!.includes(tag.rltDomainId))); if (filters.eventTypes?.length) items = items.filter((item) => filters.eventTypes!.includes(item.eventType)); if (filters.clinicalDirection?.length) items = items.filter((item) => item.clinicalDirection && filters.clinicalDirection!.includes(item.clinicalDirection as never)); if (filters.severity?.length) items = items.filter((item) => item.severity && filters.severity!.includes(item.severity)); if (filters.dateFrom) items = items.filter((item) => Date.parse(item.occurredAt) >= Date.parse(filters.dateFrom!)); if (filters.dateTo) items = items.filter((item) => Date.parse(item.occurredAt) <= Date.parse(filters.dateTo!)); if (filters.sourceModules?.length) items = items.filter((item) => filters.sourceModules!.includes(item.source.sourceModule)); if (filters.importantOnly !== false) items = items.filter((item) => item.importance !== "routine"); const page = items.slice(pagination.offset, pagination.offset + pagination.limit); return { items: page, total: items.length, offset: pagination.offset, limit: pagination.limit, hasMore: pagination.offset + pagination.limit < items.length }; }

export function addRltEventDomainTag(state: RltTimelineTagState, input: { residentId: string; sourceEntityType: string; sourceEntityId: string; rltDomainId: RltDomainId; reason?: string; explicitDomainAlreadyExists?: boolean }, context: RltTimelineTagContext) { if (!context.capabilities.includes("rlt_timeline.tag_event")) throw new Error("Missing capability: rlt_timeline.tag_event"); if (!context.residentExists(input.residentId) || !context.residentBelongsToHome(input.residentId, context.nursingHomeId)) throw new Error("Resident is outside the authorised nursing home."); if (input.explicitDomainAlreadyExists) throw new Error("Manual tags cannot override explicit RLT domain identity."); if (!RLT_DOMAIN_BY_ID[input.rltDomainId]?.active) throw new Error("RLT domain is invalid or inactive."); const existing = state.tags.find((item) => item.status === "active" && item.residentId === input.residentId && item.sourceEntityType === input.sourceEntityType && item.sourceEntityId === input.sourceEntityId && item.rltDomainId === input.rltDomainId); if (existing) return existing; const tag: RltEventDomainTag = { id: `rlt-event-tag:${stable(input.residentId)}:${stable(input.sourceEntityType)}:${stable(input.sourceEntityId)}:${input.rltDomainId}`, residentId: input.residentId, nursingHomeId: context.nursingHomeId, sourceEntityType: input.sourceEntityType, sourceEntityId: input.sourceEntityId, rltDomainId: input.rltDomainId, taggedByUserAccountId: context.userAccountId, taggedByStaffMemberId: context.staffMemberId, taggedAt: context.occurredAt, reason: input.reason, status: "active" }; state.tags.push(tag); state.audit.push({ id: `rlt-tag-audit:${tag.id}:${state.audit.length + 1}`, tagId: tag.id, action: "tagged", residentId: tag.residentId, nursingHomeId: tag.nursingHomeId, actorUserAccountId: context.userAccountId, occurredAt: context.occurredAt, reason: input.reason }); return tag; }
export function removeRltEventDomainTag(state: RltTimelineTagState, tagId: string, reason: string, context: RltTimelineTagContext) { if (!context.capabilities.includes("rlt_timeline.remove_manual_tag")) throw new Error("Missing capability: rlt_timeline.remove_manual_tag"); if (!reason.trim()) throw new Error("Tag removal reason is required."); const tag = state.tags.find((item) => item.id === tagId && item.status === "active" && item.nursingHomeId === context.nursingHomeId); if (!tag) throw new Error("Active manual tag not found in scope."); tag.status = "removed"; state.audit.push({ id: `rlt-tag-audit:${tag.id}:${state.audit.length + 1}`, tagId: tag.id, action: "removed", residentId: tag.residentId, nursingHomeId: tag.nursingHomeId, actorUserAccountId: context.userAccountId, occurredAt: context.occurredAt, reason }); return tag; }

export const RLT_OVERVIEW_QUERY_KEY = (residentId: string, nursingHomeId: string, capabilityVersion: string) => ["rlt-clinical-overview", 1, residentId, nursingHomeId, capabilityVersion] as const;
export const RLT_TIMELINE_QUERY_KEY = (residentId: string, nursingHomeId: string, capabilityVersion: string, filters: RltTimelineFilters, pagination: { offset: number; limit: number }) => ["rlt-timeline", 1, residentId, nursingHomeId, capabilityVersion, filters, pagination] as const;
export const RLT_READ_MODEL_INVALIDATION_EVENTS = ["AssessmentCompleted", "AssessmentRiskChanged", "AssessmentCorrected", "AssessmentVoided", "CarePlanCreated", "CarePlanReviewed", "CareActionCompleted", "CareActionMissed", "RltDependencyRecorded", "RltDependencyChanged", "RltDependencyReviewed", "ResidentStrengthRecorded", "ResidentStrengthChanged", "ResidentPreferenceRecorded", "ResidentPreferenceChanged", "IncidentRecorded", "ObservationRecorded", "ResidentReturnedFromHospital", "EndOfLifePathwayCreated", "EndOfLifeCareActivated", "LastDaysOfLifeRecorded", "EndOfLifeWishesChanged", "ResidentDeathRecorded", "AfterDeathCareCompleted"] as const;
