import type { TemperaturePoint, TemperatureRuleContext, TemperatureTrendCondition, TemperatureTrendEvaluation, TemperatureTrendRuleConfiguration } from "./temperatureTrendRuleTypes";

export function getEffectiveTemperatureRule(configurations: TemperatureTrendRuleConfiguration[], context: { nursingHomeId: string; enterpriseId?: string; effectiveAt: string }) { return configurations.filter((rule) => rule.status === "approved" && Boolean(rule.approvedAt) && rule.effectiveFrom <= context.effectiveAt && (!rule.effectiveTo || rule.effectiveTo > context.effectiveAt) && (rule.nursingHomeId === context.nursingHomeId || (!rule.nursingHomeId && rule.enterpriseId === context.enterpriseId))).sort((a, b) => b.version - a.version)[0]; }

export function evaluateTemperatureTrend(context: TemperatureRuleContext, rule: TemperatureTrendRuleConfiguration | undefined, residentId: string, nursingHomeId: string, evaluatedAt: string): TemperatureTrendEvaluation {
  if (!rule) return unavailable(residentId, nursingHomeId, evaluatedAt, "Temperature trend policy is not configured.");
  const points = temperaturePoints(context.records, residentId, nursingHomeId);
  if (!points.length) return unavailable(residentId, nursingHomeId, evaluatedAt, "No valid temperature observations are available.", rule);
  const current = points.at(-1)!; const previous = points.at(-2); const baseline = context.baseline?.baselineValue.valueType === "numeric" ? context.baseline : undefined;
  const matched = rule.conditions.filter((condition) => conditionMatches(condition, points, baseline));
  const isMatch = rule.combineWith === "all" ? matched.length === rule.conditions.length : matched.length > 0;
  const rise = previous ? +(current.valueCelsius - previous.valueCelsius).toFixed(2) : undefined;
  return { status: isMatch ? "matched" : "not_matched", residentId, nursingHomeId, wardId: context.records.find((record) => record.id === current.observationRecordId)?.wardId, evaluatedAt, current, previous, riseCelsius: rise, windowMinutes: previous ? Math.round((new Date(current.observedAt).getTime() - new Date(previous.observedAt).getTime()) / 60000) : undefined, matchedConditions: matched, baselineId: baseline?.id, baselineVersion: baseline?.versionNumber, news2: context.news2, ruleConfigurationId: rule.id, ruleVersion: rule.version, explanation: explain(rule, current, previous, matched, baseline), sourceObservationRecordIds: points.filter((point) => matched.some((condition) => withinWindow(point, current, condition.windowMinutes))).map((point) => point.observationRecordId) };
}

export function temperaturePoints(records: TemperatureRuleContext["records"], residentId: string, nursingHomeId: string): TemperaturePoint[] { return records.filter((record) => record.residentId === residentId && record.nursingHomeId === nursingHomeId && record.status === "completed").flatMap((record) => record.components.filter((component) => component.observationType === "temperature" && component.value !== undefined).map((component) => ({ observationRecordId: record.id, observedAt: record.observedAt, recordedAt: record.recordedAt, valueCelsius: component.value! }))).sort((a, b) => a.observedAt.localeCompare(b.observedAt) || a.observationRecordId.localeCompare(b.observationRecordId)); }
function conditionMatches(condition: TemperatureTrendCondition, points: TemperaturePoint[], baseline?: TemperatureRuleContext["baseline"]) { const current = points.at(-1)!; const window = points.filter((point) => withinWindow(point, current, condition.windowMinutes)); if (condition.method === "absolute_threshold") return (condition.minimumTemperature === undefined || current.valueCelsius >= condition.minimumTemperature) && (condition.maximumTemperature === undefined || current.valueCelsius <= condition.maximumTemperature); if (condition.method === "rise_over_window") { const first = window[0]; return Boolean(first && condition.minimumRiseCelsius !== undefined && current.valueCelsius - first.valueCelsius >= condition.minimumRiseCelsius); } if (condition.method === "sustained_readings") return window.filter((point) => (condition.minimumTemperature === undefined || point.valueCelsius >= condition.minimumTemperature) && (condition.maximumTemperature === undefined || point.valueCelsius <= condition.maximumTemperature)).length >= (condition.requiredReadings ?? Number.MAX_SAFE_INTEGER); if (condition.method === "outside_resident_baseline") { if (!baseline || baseline.baselineValue.valueType !== "numeric") return false; const value = baseline.baselineValue; return (value.expectedMinimum !== undefined && current.valueCelsius < value.expectedMinimum) || (value.expectedMaximum !== undefined && current.valueCelsius > value.expectedMaximum); } if (condition.method === "combined") return condition.minimumTemperature !== undefined && condition.minimumRiseCelsius !== undefined && current.valueCelsius >= condition.minimumTemperature && Boolean(window[0] && current.valueCelsius - window[0].valueCelsius >= condition.minimumRiseCelsius); return false; }
function withinWindow(point: TemperaturePoint, current: TemperaturePoint, minutes?: number) { return minutes === undefined || new Date(current.observedAt).getTime() - new Date(point.observedAt).getTime() <= minutes * 60000; }
function explain(rule: TemperatureTrendRuleConfiguration, current: TemperaturePoint, previous: TemperaturePoint | undefined, matched: TemperatureTrendCondition[], baseline?: TemperatureRuleContext["baseline"]) { const values = `Current ${current.valueCelsius} °C${previous ? `; previous ${previous.valueCelsius} °C at ${previous.observedAt}` : ""}.`; const baselineText = baseline ? ` Baseline ${baseline.id} version ${baseline.versionNumber} provided context only.` : ""; return `${rule.explanationTemplate} ${values}${baselineText} Rule ${rule.id} version ${rule.version}; matched ${matched.map((item) => item.method).join(", ") || "no conditions"}.`; }
function unavailable(residentId: string, nursingHomeId: string, evaluatedAt: string, explanation: string, rule?: TemperatureTrendRuleConfiguration): TemperatureTrendEvaluation { return { status: "unavailable", residentId, nursingHomeId, evaluatedAt, matchedConditions: [], ruleConfigurationId: rule?.id, ruleVersion: rule?.version, explanation, sourceObservationRecordIds: [] }; }
