import type { ResidentClinicalBaseline } from "@/domain/baselines/residentBaselineTypes";
import type { ResidentObservationRecord } from "@/domain/observations/observationTypes";
import type { PolicyNews2Result } from "@/domain/news2/news2PolicyTypes";

export type TemperatureTrendMethod = "absolute_threshold" | "rise_over_window" | "sustained_readings" | "outside_resident_baseline" | "combined";
export interface TemperatureTrendCondition { method: TemperatureTrendMethod; minimumTemperature?: number; maximumTemperature?: number; minimumRiseCelsius?: number; windowMinutes?: number; requiredReadings?: number; requireBaseline?: boolean }
export interface TemperatureTrendRuleConfiguration { id: string; name: string; version: number; status: "draft" | "pending_approval" | "approved" | "retired"; nursingHomeId?: string; enterpriseId?: string; effectiveFrom: string; effectiveTo?: string; conditions: TemperatureTrendCondition[]; combineWith: "any" | "all"; severity: "low" | "medium" | "high" | "critical"; explanationTemplate: string; repeatObservationAfterMinutes?: number; escalationTargets: string[]; createRuleIssue: boolean; createRepeatObservationWork: boolean; updateInfectionMonitoring: boolean; approvedAt?: string; sourcePolicyReference?: string }
export interface TemperaturePoint { observationRecordId: string; observedAt: string; recordedAt: string; valueCelsius: number }
export interface TemperatureTrendEvaluation { status: "matched" | "not_matched" | "unavailable"; residentId: string; nursingHomeId: string; wardId?: string; evaluatedAt: string; current?: TemperaturePoint; previous?: TemperaturePoint; riseCelsius?: number; windowMinutes?: number; matchedConditions: TemperatureTrendCondition[]; baselineId?: string; baselineVersion?: number; news2?: PolicyNews2Result; ruleConfigurationId?: string; ruleVersion?: number; explanation: string; sourceObservationRecordIds: string[] }
export interface TemperatureRuleIssueProjection { id: string; deduplicationKey: string; residentId: string; nursingHomeId: string; wardId?: string; status: "open" | "resolved"; severity: TemperatureTrendRuleConfiguration["severity"]; sourceObservationRecordIds: string[]; explanation: string; updatedAt: string; ruleConfigurationId: string; ruleVersion: number; repeatWorkItemId?: string }
export interface TemperatureRuleContext { records: ResidentObservationRecord[]; baseline?: ResidentClinicalBaseline; news2?: PolicyNews2Result }
