import { useMemo, useState } from "react";
import { useCare } from "@/lib/care/store";
import { canAssignBed, bedLabel } from "@/domain/maintenance/bedOccupancy";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";

export type AccommodationValue = { nursingHomeId: string; wingId: string; roomId: string; bedId: string };
export function AccommodationSelector({ value, onChange, allowAssignLater=true }:{value:AccommodationValue;onChange:(value:AccommodationValue)=>void;allowAssignLater?:boolean}){
  const care=useCare(); const [search,setSearch]=useState("");
  const facilities=care.facilities.filter(f=>f.id===care.activeFacilityId);
  const wings=care.wings.filter(w=>!w.facilityId||w.facilityId===value.nursingHomeId);
  const rooms=care.rooms.filter(r=>String(r.facilityId||r.nursingHomeId||care.activeFacilityId)===value.nursingHomeId&&(!value.wingId||r.wingId===value.wingId));
  const beds=useMemo(()=>care.beds.filter(b=>String(b.roomId)===value.roomId).filter(b=>canAssignBed(b,rooms.find(r=>String(r.id)===String(b.roomId)),care.bedAssignments,care.maintenanceWorkOrders,care.safetyInspections)).filter(b=>{const room=rooms.find(r=>String(r.id)===String(b.roomId));const wing=care.wings.find(w=>w.id===room?.wingId);return `${room?.number} ${b.identifier} ${b.label} ${wing?.name} ${b.bedType} ${b.mattressType}`.toLowerCase().includes(search.toLowerCase())}),[care,value.roomId,rooms,search]);
  const set=(patch:Partial<AccommodationValue>)=>onChange({...value,...patch});
  return <section className="rounded-xl border bg-muted/20 p-4"><h3 className="text-lg font-semibold">Accommodation</h3><p className="mb-4 text-sm text-muted-foreground">Select an eligible bed now, or assign one later.</p><div className="grid gap-3 sm:grid-cols-2"><Field label="Nursing Home"><select value={value.nursingHomeId} onChange={e=>set({nursingHomeId:e.target.value,wingId:"",roomId:"",bedId:""})}><option value="">Select Nursing Home</option>{facilities.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></Field><Field label="Wing / Unit"><select value={value.wingId} disabled={!value.nursingHomeId} onChange={e=>set({wingId:e.target.value,roomId:"",bedId:""})}><option value="">Select Wing / Unit</option>{wings.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select></Field><Field label="Room"><select value={value.roomId} disabled={!value.wingId} onChange={e=>set({roomId:e.target.value,bedId:""})}><option value="">{allowAssignLater?"Assign room later":"Select Room"}</option>{rooms.map(r=><option key={String(r.id)} value={String(r.id)}>Room {r.number} · {r.name||bedLabel(r.roomType)}</option>)}</select></Field><Field label="Search eligible beds"><Input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Room, bed, wing, bed or mattress type" disabled={!value.roomId}/></Field></div><div className="mt-3"><Label>Bed</Label><div className="mt-1 grid gap-2">{allowAssignLater&&<button type="button" onClick={()=>set({bedId:""})} className={`rounded-lg border p-3 text-left focus-visible:ring-2 focus-visible:ring-primary ${!value.bedId?"border-primary bg-primary/5":""}`}><strong>Assign Later</strong><div className="text-sm text-muted-foreground">Resident will show “Bed not yet assigned”.</div></button>}{beds.map(b=>{const room=rooms.find(r=>String(r.id)===String(b.roomId));const wing=care.wings.find(w=>w.id===room?.wingId);return <button type="button" key={String(b.id)} onClick={()=>set({bedId:String(b.id)})} className={`rounded-lg border p-3 text-left focus-visible:ring-2 focus-visible:ring-primary ${value.bedId===String(b.id)?"border-primary bg-primary/5":""}`}><strong>Room {room?.number} · {b.identifier||b.label}</strong><div className="text-sm">{wing?.name}</div><div className="text-sm text-muted-foreground">{bedLabel(String(b.bedType))} Bed · {bedLabel(String(b.mattressType))} Mattress</div><div className="text-sm font-medium text-emerald-700">Available and Ready</div></button>})}{value.roomId&&!beds.length&&<div className="rounded-lg border border-dashed p-3 text-sm text-muted-foreground">No eligible beds match this room and search.</div>}</div></div></section>
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block"><Label>{label}</Label><div className="mt-1 [&_select]:h-11 [&_select]:w-full [&_select]:rounded-md [&_select]:border [&_select]:bg-background [&_select]:px-3 [&_select]:text-base">{children}</div></label>}
