import { useMemo, useState } from "react";
import { Link, useNavigate } from "@tanstack/react-router";
import { AlertTriangle, CheckCircle2, ClipboardCheck, Plus, Search, X } from "lucide-react";
import { toast } from "sonner";
import { useCare } from "@/lib/care/store";
import { correctiveActionIsOverdue, correctiveActionPriorityFor, type CorrectiveAction, type CorrectiveActionPriority, type CorrectiveActionRisk, type CorrectiveActionSeverity, type CorrectiveActionStatus } from "@/domain/maintenance/correctiveActions";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

type Mode = "register" | "new" | "detail" | "edit";
const label = (value?: string) => value?.replaceAll("_", " ") || "—";
const badge = (value: string) => <Badge className={value === "CRITICAL" || value === "EXTREME" || value === "OVERDUE" ? "bg-red-100 text-red-800" : value === "HIGH" || value === "URGENT" ? "bg-amber-100 text-amber-800" : "bg-slate-100 text-slate-700"}>{label(value)}</Badge>;
const date = (value?: string) => value ? new Intl.DateTimeFormat(undefined, { dateStyle: "medium" }).format(new Date(`${value}T12:00:00`)) : "Not set";

export function CorrectiveActionManagement({ mode, actionId }: { mode: Mode; actionId?: string }) {
  const care = useCare(); const navigate = useNavigate();
  const actions = care.correctiveActions.filter((item) => item.homeId === care.activeFacilityId); const action = actions.find((item) => item.id === actionId);
  if ((mode === "detail" || mode === "edit") && !action) return <Empty message="Corrective action not found." />;
  if (mode === "new" || mode === "edit") return <ActionForm action={action} onDone={(id) => navigate({ to: "/maintenance/corrective-actions/$id", params: { id } })} />;
  if (mode === "detail" && action) return <ActionDetail action={action} />;
  return <Register />;
}

function Register() {
  const care = useCare(); const navigate = useNavigate(); const [search, setSearch] = useState(""); const [status, setStatus] = useState(""); const [overdue, setOverdue] = useState(false);
  const rows = useMemo(() => care.correctiveActions.filter((item) => item.homeId === care.activeFacilityId).filter((item) => !search || [item.referenceNumber, item.title, item.description, care.correctiveActionCategories.find((category) => category.id === item.categoryId)?.name].join(" ").toLowerCase().includes(search.trim().toLowerCase())).filter((item) => !status || item.status === status).filter((item) => !overdue || correctiveActionIsOverdue(item)).sort((a, b) => Number(correctiveActionIsOverdue(b)) - Number(correctiveActionIsOverdue(a)) || (a.dueDate || "9999").localeCompare(b.dueDate || "9999")), [care, search, status, overdue]);
  const active = rows.filter((item) => !["CLOSED", "CANCELLED"].includes(item.status)); const today = new Date().toISOString().slice(0, 10);
  return <div className="space-y-5 p-4 md:p-6"><header className="flex flex-wrap items-end justify-between gap-3"><div><div className="text-sm text-muted-foreground">Maintenance / Corrective Actions</div><h1 className="text-2xl font-semibold">Corrective Action Register</h1><p className="text-sm text-muted-foreground">Track ownership, risk and closure of corrective actions.</p></div><Button asChild><Link to="/maintenance/corrective-actions/new"><Plus className="mr-2 h-4 w-4" />Create corrective action</Link></Button></header><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Metric label="Total Active" value={active.length} /><Metric label="Open" value={active.filter((x) => x.status === "OPEN").length} /><Metric label="In Progress" value={active.filter((x) => x.status === "IN_PROGRESS").length} /><Metric label="Overdue" value={active.filter(correctiveActionIsOverdue).length} tone="red" /><Metric label="Critical" value={active.filter((x) => x.severity === "CRITICAL").length} tone="red" /></div><Card><CardContent className="pt-6"><div className="mb-4 flex flex-wrap gap-2"><div className="relative min-w-56 flex-1"><Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground" /><Input className="pl-9" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search reference, title or description" /></div><select className="rounded-md border bg-background px-3 text-sm" value={status} onChange={(event) => setStatus(event.target.value)}><option value="">All statuses</option>{["DRAFT","OPEN","IN_PROGRESS","AWAITING_VERIFICATION","CLOSED","CANCELLED"].map((x) => <option key={x}>{x}</option>)}</select><Button variant={overdue ? "default" : "outline"} onClick={() => setOverdue(!overdue)}>Overdue only</Button>{(search || status || overdue) && <Button variant="ghost" onClick={() => { setSearch(""); setStatus(""); setOverdue(false); }}><X className="mr-1 h-4 w-4" />Clear</Button>}</div>{rows.length ? <div className="overflow-x-auto"><table className="w-full min-w-[920px] text-sm"><thead className="border-b text-left text-xs uppercase text-muted-foreground"><tr>{["Reference","Title","Category","Severity","Risk","Priority","Status","Responsible person","Due date","Actions"].map((x) => <th key={x} className="p-3">{x}</th>)}</tr></thead><tbody>{rows.map((item) => <ActionRow key={item.id} item={item} />)}</tbody></table></div> : <Empty message="No corrective actions found. Create a corrective action or adjust your filters." />}</CardContent></Card></div>;
}

function ActionRow({ item }: { item: CorrectiveAction }) { const care = useCare(); const navigate = useNavigate(); const category = care.correctiveActionCategories.find((x) => x.id === item.categoryId); const user = care.users.find((x) => x.id === item.responsiblePersonId); const transition = (next: CorrectiveActionStatus) => { try { const reason = next === "CANCELLED" ? window.prompt("Cancellation reason") || "" : undefined; care.transitionCorrectiveAction(item.id, next, reason); toast.success(`Action ${label(next).toLowerCase()}.`); } catch (error) { toast.error(error instanceof Error ? error.message : "Unable to update action."); } };
 return <tr className="border-b last:border-0"><td className="p-3 font-medium">{item.referenceNumber}</td><td className="p-3"><button className="text-left font-medium hover:underline" onClick={() => navigate({ to: "/maintenance/corrective-actions/$id", params: { id: item.id } })}>{item.title}</button></td><td className="p-3">{category?.name || "Unknown"}</td><td className="p-3">{badge(item.severity)}</td><td className="p-3">{badge(item.riskLevel)}</td><td className="p-3">{badge(item.priority)}</td><td className="p-3">{badge(item.status)}</td><td className="p-3">{user?.name || "Unassigned"}</td><td className="p-3">{correctiveActionIsOverdue(item) ? <span className="font-medium text-red-700">Overdue · {date(item.dueDate)}</span> : date(item.dueDate)}</td><td className="p-3"><div className="flex gap-1"><Button size="sm" variant="outline" asChild><Link to="/maintenance/corrective-actions/$id" params={{ id: item.id }}>View</Link></Button>{!["CLOSED","CANCELLED"].includes(item.status) && <Button size="sm" variant="outline" asChild><Link to="/maintenance/corrective-actions/$id/edit" params={{ id: item.id }}>Edit</Link></Button>}{item.status === "OPEN" && <Button size="sm" onClick={() => transition("IN_PROGRESS")}>Start</Button>}{item.status === "IN_PROGRESS" && <Button size="sm" onClick={() => transition("AWAITING_VERIFICATION")}>Submit</Button>}{item.status === "AWAITING_VERIFICATION" && <Button size="sm" onClick={() => transition("CLOSED")}>Close</Button>}</div></td></tr>; }

function ActionForm({ action, onDone }: { action?: CorrectiveAction; onDone: (id: string) => void }) { const care = useCare(); const [form, setForm] = useState({ title: action?.title || "", description: action?.description || "", categoryId: action?.categoryId || care.correctiveActionCategories.find((x) => x.isActive)?.id || "", severity: action?.severity || "LOW" as CorrectiveActionSeverity, riskLevel: action?.riskLevel || "LOW" as CorrectiveActionRisk, priority: action?.priority || "NORMAL" as CorrectiveActionPriority, responsiblePersonId: action?.responsiblePersonId || "", dueDate: action?.dueDate || "" }); const update = <K extends keyof typeof form>(key: K, value: typeof form[K]) => setForm((current) => ({ ...current, [key]: value }));
 const save = (open: boolean) => { try { if (action) { care.updateCorrectiveAction(action.id, form, action.version); toast.success("Corrective action updated."); onDone(action.id); } else { const created = care.createCorrectiveAction({ ...form, homeId: care.activeFacilityId, sourceType: "MANUAL", status: open ? "OPEN" : "DRAFT" }); toast.success(open ? "Corrective action opened." : "Draft saved."); onDone(created.id); } } catch (error) { toast.error(error instanceof Error ? error.message : "Unable to save."); } };
 return <div className="space-y-5 p-4 md:p-6"><header><div className="text-sm text-muted-foreground">Maintenance / Corrective Actions</div><h1 className="text-2xl font-semibold">{action ? "Edit Corrective Action" : "Create Corrective Action"}</h1></header><Card><CardContent className="space-y-4 pt-6"><div className="grid gap-4 md:grid-cols-2"><Field label="Title" value={form.title} onChange={(v) => update("title", v)} /><Select label="Category" value={form.categoryId} onChange={(v) => update("categoryId", v)} options={care.correctiveActionCategories.filter((x) => x.isActive || x.id === action?.categoryId).map((x) => ({ value: x.id, label: x.name }))} /><Select label="Severity" value={form.severity} onChange={(v) => { update("severity", v as CorrectiveActionSeverity); if (!action) update("priority", correctiveActionPriorityFor(v as CorrectiveActionSeverity)); }} options={["LOW","MODERATE","HIGH","CRITICAL"].map((x) => ({ value: x, label: label(x) }))} /><Select label="Risk level" value={form.riskLevel} onChange={(v) => update("riskLevel", v as CorrectiveActionRisk)} options={["LOW","MEDIUM","HIGH","EXTREME"].map((x) => ({ value: x, label: label(x) }))} /><Select label="Priority" value={form.priority} onChange={(v) => update("priority", v as CorrectiveActionPriority)} options={["LOW","NORMAL","HIGH","URGENT"].map((x) => ({ value: x, label: label(x) }))} /><Select label="Responsible person" value={form.responsiblePersonId} onChange={(v) => update("responsiblePersonId", v)} options={[{ value: "", label: "Unassigned (draft only)" }, ...care.users.filter((x) => x.status === "active" && (x.facilityIds?.includes(care.activeFacilityId) || x.facilityId === care.activeFacilityId)).map((x) => ({ value: x.id, label: `${x.name} · ${x.role}` }))]} /><Field label="Due date" type="date" value={form.dueDate} onChange={(v) => update("dueDate", v)} /></div><div><label className="mb-1 block text-sm font-medium">Description</label><Textarea value={form.description} onChange={(event) => update("description", event.target.value)} rows={6} /></div><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={() => save(false)}>{action ? "Save changes" : "Save as draft"}</Button>{!action && <Button onClick={() => save(true)}>Create and open</Button>}<Button variant="ghost" asChild><Link to={action ? "/maintenance/corrective-actions/$id" : "/maintenance/corrective-actions"} params={action ? { id: action.id } : undefined}>Cancel</Link></Button></div></CardContent></Card></div>; }

function ActionDetail({ action }: { action: CorrectiveAction }) { const care = useCare(); const navigate = useNavigate(); const category = care.correctiveActionCategories.find((x) => x.id === action.categoryId); const assignee = care.users.find((x) => x.id === action.responsiblePersonId); const audit = care.auditLogs.filter((x) => x.entity === action.id).slice(0, 8); const transition = (status: CorrectiveActionStatus) => { try { care.transitionCorrectiveAction(action.id, status, status === "CANCELLED" ? window.prompt("Cancellation reason") || "" : undefined); toast.success("Status updated."); } catch (error) { toast.error(error instanceof Error ? error.message : "Unable to update status."); } };
 return <div className="space-y-5 p-4 md:p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="text-sm text-muted-foreground">{action.referenceNumber}</div><h1 className="text-2xl font-semibold">{action.title}</h1><div className="mt-2 flex flex-wrap gap-2">{badge(action.status)} {badge(action.severity)} {badge(action.riskLevel)} {badge(action.priority)} {correctiveActionIsOverdue(action) && <Badge className="bg-red-100 text-red-800">OVERDUE</Badge>}</div></div><div className="flex gap-2">{!["CLOSED","CANCELLED"].includes(action.status) && <Button variant="outline" onClick={() => navigate({ to: "/maintenance/corrective-actions/$id/edit", params: { id: action.id } })}>Edit</Button>}{action.status === "DRAFT" && <Button onClick={() => transition("OPEN")}>Open</Button>}{action.status === "OPEN" && <Button onClick={() => transition("IN_PROGRESS")}>Start</Button>}{action.status === "IN_PROGRESS" && <Button onClick={() => transition("AWAITING_VERIFICATION")}>Submit for verification</Button>}{action.status === "AWAITING_VERIFICATION" && <Button onClick={() => transition("CLOSED")}>Close</Button>}</div></div><div className="grid gap-4 lg:grid-cols-2"><Card><CardHeader><CardTitle>Action Information</CardTitle></CardHeader><CardContent className="space-y-4"><p className="whitespace-pre-wrap text-sm">{action.description}</p><Info label="Category" value={category?.name || "Unknown"} /><Info label="Source" value={label(action.sourceType)} /></CardContent></Card><Card><CardHeader><CardTitle>Assignment and dates</CardTitle></CardHeader><CardContent className="space-y-3"><Info label="Responsible person" value={assignee?.name || "Unassigned"} /><Info label="Due date" value={date(action.dueDate)} /><Info label="Created" value={date(action.createdAt.slice(0, 10))} /><Info label="Last updated" value={new Date(action.updatedAt).toLocaleString()} /></CardContent></Card><Card className="lg:col-span-2"><CardHeader><CardTitle>Activity summary</CardTitle></CardHeader><CardContent>{audit.length ? <div className="space-y-3">{audit.map((item) => <div key={item.id} className="flex items-start gap-3 border-b pb-3 text-sm last:border-0"><CheckCircle2 className="mt-0.5 h-4 w-4 text-emerald-600" /><div><div className="font-medium">{item.action}</div><div className="text-muted-foreground">{item.user} · {new Date(item.timestamp).toLocaleString()}{item.reason ? ` · ${item.reason}` : ""}</div></div></div>)}</div> : <p className="text-sm text-muted-foreground">No activity recorded.</p>}</CardContent></Card></div></div>; }
function Metric({ label, value, tone }: { label: string; value: number; tone?: "red" }) { return <Card><CardContent className="pt-5"><div className="text-sm text-muted-foreground">{label}</div><div className={tone ? "mt-1 text-3xl font-semibold text-red-700" : "mt-1 text-3xl font-semibold"}>{value}</div></CardContent></Card>; }
function Info({ label, value }: { label: string; value: string }) { return <div><div className="text-xs uppercase text-muted-foreground">{label}</div><div className="font-medium">{value}</div></div>; }
function Field({ label, value, onChange, type = "text" }: { label: string; value: string; onChange: (value: string) => void; type?: string }) { return <div><label className="mb-1 block text-sm font-medium">{label}</label><Input type={type} value={value} onChange={(event) => onChange(event.target.value)} /></div>; }
function Select({ label, value, onChange, options }: { label: string; value: string; onChange: (value: string) => void; options: { value: string; label: string }[] }) { return <div><label className="mb-1 block text-sm font-medium">{label}</label><select className="h-9 w-full rounded-md border bg-background px-3 text-sm" value={value} onChange={(event) => onChange(event.target.value)}>{options.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select></div>; }
function Empty({ message }: { message: string }) { return <div className="rounded-lg border border-dashed p-8 text-center text-sm text-muted-foreground"><AlertTriangle className="mx-auto mb-2 h-5 w-5" />{message}</div>; }
