import { useState } from "react";
import { Plus } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { archiveServiceTrade, loadPhase5AGovernance, persistPhase5AGovernance, restoreServiceTrade, saveServiceTrade, type ServiceTrade } from "@/domain/maintenance/phase5aGovernance";

export function ServicesTradesSettings() {
  const [data, setData] = useState(loadPhase5AGovernance);
  const [search, setSearch] = useState("");
  const [editing, setEditing] = useState<ServiceTrade>();
  const commit = (services: ServiceTrade[]) => { const next = { ...data, services }; setData(next); persistPhase5AGovernance(next); };
  const rows = data.services.filter((item) => `${item.name} ${item.description || ""} ${item.category}`.toLowerCase().includes(search.toLowerCase())).sort((a, b) => a.displayOrder - b.displayOrder);
  const blank = (): ServiceTrade => ({ id: `service-${Date.now()}`, tenantId: "tenant-oritas-demo", name: "", description: "", category: "Maintenance", active: true, displayOrder: data.services.length + 1, approvalRequired: true, requiredInsuranceTypes: [], requiredCertificateTypeIds: [], requiredDocumentTypes: [], nursingHomeApprovalRequired: true, internalVerificationRequired: false, assignmentOverridePermitted: false, riskClassification: "MEDIUM", updatedAt: new Date().toISOString() });
  return <><Card><CardHeader><div className="flex flex-wrap items-center justify-between gap-3"><div><CardTitle>Services &amp; Trades</CardTitle><p className="mt-1 text-sm text-muted-foreground">Configure assignment and compliance requirements. Archived services remain available in history.</p></div><Button onClick={() => setEditing(blank())}><Plus className="mr-2 h-4 w-4" />Add Service or Trade</Button></div></CardHeader><CardContent className="space-y-4"><Input className="max-w-md" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search services and trades" /><div className="space-y-3">{rows.map((item) => <div key={item.id} className="rounded-lg border p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="font-semibold">{item.name}</div><div className="text-sm text-muted-foreground">{item.category} · {item.active ? "Active" : "Archived"}</div><div className="mt-2 text-sm">{[...item.requiredInsuranceTypes, ...item.requiredCertificateTypeIds, ...item.requiredDocumentTypes].length ? `Requirements: ${[...item.requiredInsuranceTypes, ...item.requiredCertificateTypeIds, ...item.requiredDocumentTypes].join(", ")}` : "No additional document requirements"}</div></div><div className="flex gap-2"><Button size="sm" variant="outline" onClick={() => setEditing(item)}>Edit</Button>{item.active ? <Button size="sm" variant="outline" onClick={() => commit(archiveServiceTrade(data.services, item.id))}>Archive</Button> : <Button size="sm" variant="outline" onClick={() => commit(restoreServiceTrade(data.services, item.id))}>Restore</Button>}</div></div></div>)}{!rows.length && <div className="rounded-lg border border-dashed p-8 text-center text-muted-foreground">No Services or Trades have been configured.</div>}</div></CardContent></Card><ServiceDialog item={editing} onClose={() => setEditing(undefined)} onSave={(item) => { commit(saveServiceTrade(data.services, item)); setEditing(undefined); }} /></>;
}

function ServiceDialog({ item, onClose, onSave }: { item?: ServiceTrade; onClose: () => void; onSave: (item: ServiceTrade) => void }) { const [draft, setDraft] = useState<ServiceTrade | undefined>(item); if (item && draft?.id !== item.id) setDraft(item); if (!draft) return null; const set = (key: keyof ServiceTrade, value: any) => setDraft({ ...draft, [key]: value }); return <Dialog open onOpenChange={(open) => !open && onClose()}><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-2xl"><DialogHeader><DialogTitle>{dataTitle(draft.name)} Service or Trade</DialogTitle></DialogHeader><div className="grid gap-4 md:grid-cols-2"><Field label="Name"><Input value={draft.name} onChange={(event) => set("name", event.target.value)} /></Field><Field label="Category"><Input value={draft.category} onChange={(event) => set("category", event.target.value)} /></Field><div className="md:col-span-2"><Field label="Description"><Textarea value={draft.description || ""} onChange={(event) => set("description", event.target.value)} /></Field></div><Field label="Required insurance types"><Input value={draft.requiredInsuranceTypes.join(", ")} onChange={(event) => set("requiredInsuranceTypes", list(event.target.value))} placeholder="PUBLIC_LIABILITY, EMPLOYER_LIABILITY" /></Field><Field label="Required certificate type IDs"><Input value={draft.requiredCertificateTypeIds.join(", ")} onChange={(event) => set("requiredCertificateTypeIds", list(event.target.value))} /></Field><Field label="Required document types"><Input value={draft.requiredDocumentTypes.join(", ")} onChange={(event) => set("requiredDocumentTypes", list(event.target.value))} /></Field><Field label="Display order"><Input type="number" value={draft.displayOrder} onChange={(event) => set("displayOrder", Number(event.target.value))} /></Field><Field label="Risk classification"><select className="h-11 w-full rounded-md border bg-background px-3" value={draft.riskClassification} onChange={(event) => set("riskClassification", event.target.value)}>{["LOW","MEDIUM","HIGH","CRITICAL"].map((value) => <option key={value}>{value}</option>)}</select></Field><div className="space-y-2">{[["approvalRequired","Contractor approval required"],["nursingHomeApprovalRequired","Nursing Home approval required"],["internalVerificationRequired","Internal verification required"],["assignmentOverridePermitted","Authorised override permitted"]] .map(([key,label]) => <label key={key} className="flex min-h-10 items-center gap-2"><input type="checkbox" checked={Boolean(draft[key as keyof ServiceTrade])} onChange={(event) => set(key as keyof ServiceTrade, event.target.checked)} />{label}</label>)}</div></div><DialogFooter><Button variant="outline" onClick={onClose}>Cancel</Button><Button disabled={!draft.name.trim()} onClick={() => onSave(draft)}>Save Service</Button></DialogFooter></DialogContent></Dialog>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div className="space-y-1"><Label>{label}</Label>{children}</div>; }
function list(value: string) { return value.split(",").map((item) => item.trim()).filter(Boolean); }
function dataTitle(name: string) { return name ? "Edit" : "Add"; }
