import { createFileRoute, Link } from "@tanstack/react-router";
import { useMemo, useState } from "react";
import { Download, FileSearch, FolderArchive, Play, Search, TimerReset } from "lucide-react";
import { useCare } from "@/lib/care/store";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Badge } from "@/components/ui/badge";
import { toast } from "sonner";

export const Route = createFileRoute("/maintenance/reports")({
  head: () => ({ meta: [{ title: "Maintenance Reports - NuCare" }] }),
  component: MaintenanceReports,
});

type ReportDefinition = { key: string; name: string; category: string; description: string; formats: string[]; source: "workOrders" | "planned" | "assets" | "certificates" | "contractors" | "correctiveActions" | "housekeeping" | "audits" };
const reports: ReportDefinition[] = [
  { key: "work-order-register", name: "Work Order Register", category: "Work Orders", description: "Complete operational register with status, priority, due date and assigned owner.", formats: ["CSV", "Excel", "PDF"], source: "workOrders" },
  { key: "open-work-orders", name: "Open Work Orders", category: "Work Orders", description: "New, assigned, in-progress and waiting work requiring action.", formats: ["CSV", "Excel", "PDF"], source: "workOrders" },
  { key: "overdue-work-orders", name: "Overdue Work Orders", category: "Work Orders", description: "Open work orders past their due date.", formats: ["CSV", "Excel", "PDF"], source: "workOrders" },
  { key: "preventive-maintenance", name: "Preventive Maintenance Schedule", category: "Preventive Maintenance", description: "Scheduled maintenance occurrences and their due status.", formats: ["CSV", "Excel", "PDF"], source: "planned" },
  { key: "overdue-preventive", name: "Overdue Preventive Maintenance", category: "Preventive Maintenance", description: "Preventive maintenance tasks that have passed their due date.", formats: ["CSV", "Excel", "PDF"], source: "planned" },
  { key: "asset-register", name: "Asset Register", category: "Assets", description: "Asset identity, location, condition, warranty and operational status.", formats: ["CSV", "Excel", "PDF"], source: "assets" },
  { key: "asset-history", name: "Asset History", category: "Asset History", description: "Recorded asset movement and audit history.", formats: ["CSV", "Excel"], source: "audits" },
  { key: "fire-water-electrical", name: "Safety Inspection Register", category: "Fire, Water & Electrical", description: "Existing safety inspection records and completion status.", formats: ["CSV", "Excel", "PDF"], source: "audits" },
  { key: "housekeeping", name: "Housekeeping Task Completion", category: "Housekeeping", description: "Cleaning tasks, due dates, results and assigned staff.", formats: ["CSV", "Excel", "PDF"], source: "housekeeping" },
  { key: "certificate-register", name: "Certificate Register", category: "Certificates", description: "Certificate status, issue date, expiry and verification records.", formats: ["CSV", "Excel", "PDF"], source: "certificates" },
  { key: "contractor-register", name: "Contractor Register", category: "Contractors", description: "Approved contractor records and current status.", formats: ["CSV", "Excel"], source: "contractors" },
  { key: "corrective-action-register", name: "Corrective Action Register", category: "Corrective Actions", description: "Open, overdue and completed corrective actions.", formats: ["CSV", "Excel", "PDF"], source: "correctiveActions" },
  { key: "management-summary", name: "Maintenance Management Summary", category: "Management Summary", description: "Concise overview of open, overdue and due operational records.", formats: ["CSV", "Excel", "PDF"], source: "workOrders" },
];

function MaintenanceReports() {
  const care = useCare(); const data: any = care;
  const [tab, setTab] = useState("library"); const [query, setQuery] = useState(""); const [category, setCategory] = useState("all"); const [selected, setSelected] = useState<ReportDefinition | null>(null);
  const [facility, setFacility] = useState(care.activeFacilityId); const [status, setStatus] = useState("all"); const [from, setFrom] = useState(""); const [to, setTo] = useState(""); const [ranAt, setRanAt] = useState<string>();
  const permittedHomes = care.facilities.filter((item) => care.canAccess("permission.manage", { nursingHomeId: item.id }));
  const library = reports.filter((item) => (category === "all" || item.category === category) && `${item.name} ${item.description} ${item.category}`.toLowerCase().includes(query.toLowerCase()));
  const rows = useMemo(() => selected ? reportRows(selected, data, facility, status, from, to) : [], [selected, data, facility, status, from, to]);
  const columns = rows.length ? Object.keys(rows[0]) : [];
  const run = (definition: ReportDefinition) => { setSelected(definition); setRanAt(new Date().toLocaleString("en-IE")); setTab("results"); };
  const exportCsv = () => { if (!selected) return; const csv = [columns.join(","), ...rows.map((row: any) => columns.map((key) => csvValue(row[key])).join(","))].join("\n"); const url = URL.createObjectURL(new Blob([csv], { type: "text/csv;charset=utf-8" })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `${selected.key}-${new Date().toISOString().slice(0, 10)}.csv`; anchor.click(); URL.revokeObjectURL(url); toast.success("CSV export downloaded."); };
  if (!care.canAccess("permission.manage", { nursingHomeId: facility })) return <div className="p-6 text-sm">You do not have access to Maintenance Reports.</div>;
  return <div className="space-y-5 p-4 md:p-8"><div><h1 className="text-2xl font-semibold tracking-tight">Maintenance Reports</h1><p className="text-sm text-muted-foreground">Live reports use existing maintenance records and respect your facility access.</p></div>
    <Tabs value={tab} onValueChange={setTab}><TabsList className="flex-wrap h-auto"><TabsTrigger value="library">Report Library</TabsTrigger><TabsTrigger value="results" disabled={!selected}>Report Results</TabsTrigger><TabsTrigger value="scheduled">Scheduled Reports</TabsTrigger><TabsTrigger value="evidence">Evidence Packs</TabsTrigger><TabsTrigger value="exports">Export History</TabsTrigger></TabsList></Tabs>
    {tab === "library" && <><div className="grid gap-3 md:grid-cols-[1fr_14rem]"><div className="relative"><Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground"/><Input value={query} onChange={(e) => setQuery(e.target.value)} className="pl-9" placeholder="Search reports"/></div><Select value={category} onValueChange={setCategory}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">All categories</SelectItem>{[...new Set(reports.map((r) => r.category))].map((item) => <SelectItem key={item} value={item}>{item}</SelectItem>)}</SelectContent></Select></div><div className="divide-y rounded-lg border">{library.map((item) => <div key={item.key} className="flex flex-wrap items-center justify-between gap-3 p-4"><div><div className="font-medium">{item.name}</div><p className="text-sm text-muted-foreground">{item.description}</p><div className="mt-2 flex gap-1">{item.formats.map((format) => <Badge key={format} variant="outline">{format}</Badge>)}</div></div><Button onClick={() => run(item)}><Play className="mr-2 h-4 w-4"/>Run report</Button></div>)}</div></>}
    {tab === "results" && selected && <><Card><CardHeader><div className="flex flex-wrap items-start justify-between gap-3"><div><CardTitle>{selected.name}</CardTitle><p className="mt-1 text-sm text-muted-foreground">{selected.description}{ranAt ? ` · Refreshed ${ranAt}` : ""}</p></div><Button onClick={exportCsv}><Download className="mr-2 h-4 w-4"/>Export CSV</Button></div></CardHeader><CardContent className="grid gap-3 md:grid-cols-4"><div><Label>Facility</Label><Select value={facility} onValueChange={setFacility}><SelectTrigger className="mt-1"><SelectValue/></SelectTrigger><SelectContent>{permittedHomes.map((item) => <SelectItem key={item.id} value={item.id}>{item.name}</SelectItem>)}</SelectContent></Select></div><div><Label>Status</Label><Select value={status} onValueChange={setStatus}><SelectTrigger className="mt-1"><SelectValue placeholder="All statuses"/></SelectTrigger><SelectContent><SelectItem value="all">All statuses</SelectItem>{["ASSIGNED", "OPEN", "IN_PROGRESS", "ON_HOLD", "COMPLETED"].map((item) => <SelectItem key={item} value={item}>{item.replaceAll("_", " ")}</SelectItem>)}</SelectContent></Select></div><div><Label>Date from</Label><Input className="mt-1" type="date" value={from} onChange={(e) => setFrom(e.target.value)}/></div><div><Label>Date to</Label><Input className="mt-1" type="date" value={to} onChange={(e) => setTo(e.target.value)}/></div><div className="md:col-span-4 flex gap-2"><Button onClick={() => setRanAt(new Date().toLocaleString("en-IE"))}><FileSearch className="mr-2 h-4 w-4"/>Apply filters</Button><Button variant="outline" onClick={() => { setStatus("all"); setFrom(""); setTo(""); }}>Clear filters</Button></div></CardContent></Card><Card><CardHeader><CardTitle className="text-base">Results <span className="text-muted-foreground font-normal">({rows.length})</span></CardTitle></CardHeader><CardContent>{rows.length ? <div className="overflow-auto"><table className="w-full text-sm"><thead className="border-b bg-muted/40"><tr>{columns.map((column) => <th key={column} className="p-3 text-left">{column}</th>)}</tr></thead><tbody>{rows.slice(0, 100).map((row: any, index) => <tr key={index} className="border-b">{columns.map((column) => <td key={column} className="p-3">{row.link ? <Link className="text-primary underline" to={row.link as any}>{String(row[column] ?? "—")}</Link> : String(row[column] ?? "—")}</td>)}</tr>)}</tbody></table></div> : <p className="py-8 text-center text-sm text-muted-foreground">No records match the applied filters.</p>}</CardContent></Card></>}
    {tab === "scheduled" && <SimplePanel icon={TimerReset} title="Scheduled Reports" rows={[]} empty="Scheduling requires a saved report and delivery configuration. No schedules have been created."/>}{tab === "evidence" && <SimplePanel icon={FolderArchive} title="Evidence Packs" rows={[]} empty="Evidence packs are generated from authorised report results and attachments. No evidence packs have been generated."/>}{tab === "exports" && <SimplePanel icon={Download} title="Export History" rows={[]} empty="Completed exports will appear here for authorised users."/>}
  </div>;
}

function reportRows(report: ReportDefinition, data: any, facility: string, status: string, from: string, to: string): any[] { const today = new Date().toISOString().slice(0, 10); const home = (row: any) => String(row.homeId || row.facilityId || row.nursingHomeId || "") === facility; const dateOk = (value?: string) => (!from || (value || "") >= from) && (!to || (value || "") <= to); const filter = (rows: any[], date: (row: any) => string | undefined) => rows.filter(home).filter((row) => status === "all" || String(row.status || "").toLowerCase().includes(status.toLowerCase())).filter((row) => dateOk(date(row)));
  if (report.source === "workOrders") return filter(data.maintenanceWorkOrders || [], (r) => r.reportedAt).filter((r) => report.key !== "open-work-orders" || !["COMPLETED", "CLOSED", "CANCELLED", "ENTERED_IN_ERROR"].includes(r.status)).filter((r) => report.key !== "overdue-work-orders" || (r.dueAt?.slice(0, 10) < today && !["COMPLETED", "CLOSED", "CANCELLED"].includes(r.status))).map((r) => ({ "Work Order": r.workOrderNumber, Title: r.title, Priority: r.priority, Status: r.status, "Due Date": r.dueAt?.slice(0, 10), Location: r.exactLocation || r.areaName, "Reported Date": r.reportedAt?.slice(0, 10), Overdue: r.dueAt?.slice(0, 10) < today && !["COMPLETED", "CLOSED", "CANCELLED"].includes(r.status) ? "Yes" : "No", link: `/maintenance/work-orders/${r.id}` }));
  if (report.source === "planned") return filter(data.plannedMaintenanceOccurrences || [], (r) => r.dueDate).filter((r) => report.key !== "overdue-preventive" || (r.dueDate < today && !["Completed", "Cancelled"].includes(r.status))).map((r) => ({ "Due Date": r.dueDate, Status: r.status, "Completed Date": r.completedAt?.slice(0, 10), "Days Overdue": r.dueDate < today && !r.completedAt ? Math.floor((Date.now() - new Date(r.dueDate).getTime()) / 86400000) : 0 }));
  if (report.source === "assets") return filter(data.maintenanceAssets || [], (r) => r.createdAt).map((r) => ({ "Asset ID": r.assetNumber, Asset: r.assetName, Condition: r.condition, "Operational Status": r.operationalStatus, Criticality: r.criticality, Location: r.locationLabel, "Warranty Expiry": r.warrantyEndDate, link: "/maintenance/assets" }));
  if (report.source === "certificates") return filter(data.safetyCertificates || [], (r) => r.createdAt).map((r) => ({ Certificate: r.certificateNumber || r.name, Status: r.status, "Issue Date": r.issueDate, "Expiry Date": r.expiryDate, "Issued By": r.issuingOrganisation }));
  if (report.source === "contractors") return filter(data.maintenanceContractors || [], (r) => r.createdAt).map((r) => ({ Contractor: r.legalName, Reference: r.contractorReference, Status: r.status, "Approval Status": r.approvalStatus, Contact: r.primaryContactName, link: `/maintenance/contractors/${r.id}` }));
  if (report.source === "correctiveActions") return filter(data.correctiveActions || [], (r) => r.createdAt).map((r) => ({ Reference: r.referenceNumber, Title: r.title, Status: r.status, Risk: r.riskLevel, "Due Date": r.dueDate, "Created": r.createdAt?.slice(0, 10), link: `/maintenance/corrective-actions/${r.id}` }));
  if (report.source === "housekeeping") return filter(data.housekeepingTasks || [], (r) => r.plannedDate).map((r) => ({ Task: r.taskNumber, Title: r.title, Location: r.locationLabel, "Due Date": r.dueDate, Status: r.status, Result: r.overallResult }));
  return filter(data.auditLogs || [], (r) => r.timestamp).filter((r) => String(r.entityType || "").includes("maintenance") || String(r.action || "").toLowerCase().includes("safety")).map((r) => ({ Date: r.timestamp, Action: r.action, Entity: r.entityType, Record: r.entity, User: r.user })); }
function csvValue(value: unknown) { const text = String(value ?? ""); return /[",\n]/.test(text) ? `"${text.replaceAll('"', '""')}"` : text; }
function SimplePanel({ icon: Icon, title, rows, empty }: { icon: any; title: string; rows: string[]; empty: string }) { return <Card><CardHeader><CardTitle className="flex items-center gap-2"><Icon className="h-5 w-5"/>{title}</CardTitle></CardHeader><CardContent>{rows.length ? <div className="space-y-2">{rows.map((row) => <div key={row} className="rounded border p-3 text-sm">{row}</div>)}</div> : <p className="py-8 text-center text-sm text-muted-foreground">{empty}</p>}</CardContent></Card>; }
