import { OBSERVATION_UNIT_LABELS } from "@/domain/observations/observationTypes";
import type { ResidentBaselineAuthorization, ResidentBaselineEvent, ResidentBaselineSource, ResidentBaselineSummary, ResidentBaselineType, ResidentBaselineValue, ResidentClinicalBaseline } from "./residentBaselineTypes";

export interface BaselineRepository { baselines: ResidentClinicalBaseline[]; events: ResidentBaselineEvent[] }
export interface CreateBaselineInput { residentId: string; nursingHomeId: string; baselineType: ResidentBaselineType; baselineValue: ResidentBaselineValue; clinicalRationale: string; source: ResidentBaselineSource; sourceEntityType?: string; sourceEntityId?: string; sourceDocumentId?: string; effectiveFrom: string; effectiveTo?: string; reviewDate: string; createdByUserAccountId: string; createdByStaffMemberId?: string }

const requireCapability = (auth: ResidentBaselineAuthorization, capability: string) => { if (!auth.capabilities.includes(capability)) throw new Error("Resident baseline access is not authorised."); };
const requireScope = (residentId: string, homeId: string, auth: ResidentBaselineAuthorization) => { if (homeId !== auth.nursingHomeId || !auth.residentIds.includes(residentId)) throw new Error("Resident baseline scope is not authorised."); };

export function createResidentBaseline(input: CreateBaselineInput, auth: ResidentBaselineAuthorization, repository: BaselineRepository, createId: () => string, at: string, correlationId = createId()) {
  requireCapability(auth, "resident_baseline.create"); requireScope(input.residentId, input.nursingHomeId, auth); validateRequired(input);
  const record: ResidentClinicalBaseline = { ...input, id: createId(), status: "draft", versionNumber: 1, versionChainId: createId(), createdAt: at, updatedAt: at };
  repository.baselines.push(record); emit(repository, record, "ResidentBaselineCreated", input.createdByUserAccountId, at, correlationId, createId); return record;
}
export function submitResidentBaselineForApproval(record: ResidentClinicalBaseline, actorId: string, auth: ResidentBaselineAuthorization, repository: BaselineRepository, at: string, createId: () => string) {
  requireCapability(auth, "resident_baseline.submit_approval"); requireScope(record.residentId, record.nursingHomeId, auth); if (record.status !== "draft") throw new Error("Only a draft baseline can be submitted.");
  const updated = replace(repository, { ...record, status: "pending_approval", updatedAt: at }); emit(repository, updated, "ResidentBaselineSubmittedForApproval", actorId, at, createId(), createId); return updated;
}
export function approveResidentBaseline(record: ResidentClinicalBaseline, actor: { userAccountId: string; staffMemberId?: string; role?: string }, auth: ResidentBaselineAuthorization, repository: BaselineRepository, at: string, createId: () => string) {
  requireCapability(auth, "resident_baseline.approve"); requireScope(record.residentId, record.nursingHomeId, auth); if (record.status !== "pending_approval") throw new Error("Only a submitted baseline can be approved."); validateRequired(record);
  repository.baselines.filter((item) => item.id !== record.id && item.residentId === record.residentId && item.baselineType === record.baselineType && item.status === "active").forEach((item) => replace(repository, { ...item, status: "superseded", effectiveTo: at, updatedAt: at }));
  const updated = replace(repository, { ...record, status: "active", approvedByUserAccountId: actor.userAccountId, approvedByStaffMemberId: actor.staffMemberId, approvedByRole: actor.role, approvedAt: at, updatedAt: at }); emit(repository, updated, "ResidentBaselineApproved", actor.userAccountId, at, createId(), createId); return updated;
}
export function rejectResidentBaseline(record: ResidentClinicalBaseline, reason: string, actorId: string, auth: ResidentBaselineAuthorization, repository: BaselineRepository, at: string, createId: () => string) { requireCapability(auth, "resident_baseline.approve"); if (!reason.trim()) throw new Error("A rejection reason is required."); const updated = replace(repository, { ...record, status: "rejected", rejectionReason: reason, updatedAt: at }); emit(repository, updated, "ResidentBaselineRejected", actorId, at, createId(), createId); return updated; }
export function reviewResidentBaseline(record: ResidentClinicalBaseline, nextReviewDate: string, actorId: string, auth: ResidentBaselineAuthorization, repository: BaselineRepository, at: string, createId: () => string) { requireCapability(auth, "resident_baseline.review"); if (record.status !== "active") throw new Error("Only an active baseline can be reviewed."); const updated = replace(repository, { ...record, reviewDate: nextReviewDate, lastReviewedAt: at, updatedAt: at }); emit(repository, updated, "ResidentBaselineReviewed", actorId, at, createId(), createId); return updated; }
export function supersedeResidentBaseline(record: ResidentClinicalBaseline, replacement: CreateBaselineInput, reason: string, actorId: string, auth: ResidentBaselineAuthorization, repository: BaselineRepository, at: string, createId: () => string) { requireCapability(auth, "resident_baseline.supersede"); if (!reason.trim()) throw new Error("A change reason is required."); const closed = replace(repository, { ...record, status: "superseded", effectiveTo: at, statusReason: reason, updatedAt: at }); const next: ResidentClinicalBaseline = { ...replacement, id: createId(), status: "draft", supersedesBaselineId: record.id, versionNumber: record.versionNumber + 1, versionChainId: record.versionChainId, createdAt: at, updatedAt: at }; repository.baselines.push(next); emit(repository, closed, "ResidentBaselineSuperseded", actorId, at, createId(), createId); emit(repository, next, "ResidentBaselineChanged", actorId, at, createId(), createId); return { previous: closed, replacement: next }; }
export function revokeResidentBaseline(record: ResidentClinicalBaseline, reason: string, actorId: string, auth: ResidentBaselineAuthorization, repository: BaselineRepository, at: string, createId: () => string) { requireCapability(auth, "resident_baseline.revoke"); if (!reason.trim()) throw new Error("A revocation reason is required."); const updated = replace(repository, { ...record, status: "revoked", effectiveTo: at, statusReason: reason, updatedAt: at }); emit(repository, updated, "ResidentBaselineRevoked", actorId, at, createId(), createId); return updated; }
export function markResidentBaselineEnteredInError(record: ResidentClinicalBaseline, reason: string, actorId: string, auth: ResidentBaselineAuthorization, repository: BaselineRepository, at: string, createId: () => string) { requireCapability(auth, "resident_baseline.correct"); if (!reason.trim()) throw new Error("A correction reason is required."); const updated = replace(repository, { ...record, status: "entered_in_error", effectiveTo: at, statusReason: reason, updatedAt: at }); emit(repository, updated, "ResidentBaselineEnteredInError", actorId, at, createId(), createId); return updated; }

export function expireDueBaselines(repository: BaselineRepository, at: string, createId: () => string) { return repository.baselines.filter((item) => item.status === "active" && item.reviewDate < at.slice(0, 10)).map((item) => { const updated = replace(repository, { ...item, status: "expired" as const, effectiveTo: at, updatedAt: at }); emit(repository, updated, "ResidentBaselineExpired", "system", at, createId(), createId); return updated; }); }
export function getActiveResidentBaselines(records: ResidentClinicalBaseline[], residentId: string, effectiveAt: string, auth: ResidentBaselineAuthorization) { requireCapability(auth, "resident_baseline.view"); return records.filter((item) => item.residentId === residentId && item.nursingHomeId === auth.nursingHomeId && item.status === "active" && Boolean(item.approvedAt) && item.effectiveFrom <= effectiveAt && (!item.effectiveTo || item.effectiveTo > effectiveAt) && item.reviewDate >= effectiveAt.slice(0, 10)); }
export function getResidentBaselineHistory(records: ResidentClinicalBaseline[], residentId: string, auth: ResidentBaselineAuthorization, page: { cursor?: string; limit?: number } = {}) { requireCapability(auth, "resident_baseline.view_history"); requireScope(residentId, auth.nursingHomeId, auth); const sorted = records.filter((item) => item.residentId === residentId && item.nursingHomeId === auth.nursingHomeId).sort((a, b) => b.createdAt.localeCompare(a.createdAt) || b.id.localeCompare(a.id)); const start = page.cursor ? Math.max(0, sorted.findIndex((item) => item.id === page.cursor) + 1) : 0; const limit = Math.min(page.limit ?? 20, 100); const items = sorted.slice(start, start + limit); return { items, nextCursor: start + limit < sorted.length ? items.at(-1)?.id : undefined }; }
export function getResidentBaselineSummary(records: ResidentClinicalBaseline[], residentId: string, effectiveAt: string, auth: ResidentBaselineAuthorization): ResidentBaselineSummary { const current = getActiveResidentBaselines(records, residentId, effectiveAt, auth); return { residentId, baselines: current.map((item) => ({ baselineId: item.id, baselineType: item.baselineType, displayValue: displayBaselineValue(item.baselineValue), sourceLabel: auth.canViewSource ? item.source.replaceAll("_", " ") : "Approved clinical source", effectiveFrom: item.effectiveFrom, reviewDate: item.reviewDate, reviewState: reviewState(item.reviewDate, effectiveAt), route: auth.canViewSource && item.sourceEntityId ? `/records/${item.sourceEntityId}` : undefined })) }; }
export function displayBaselineValue(value: ResidentBaselineValue) { if (value.valueType === "numeric") { const unit = OBSERVATION_UNIT_LABELS[value.unit]; return value.expectedValue !== undefined ? `${value.expectedValue} ${unit}` : `${value.expectedMinimum ?? "?"}–${value.expectedMaximum ?? "?"} ${unit}`; } if (value.valueType === "coded") return value.expectedCode.replaceAll("_", " "); if (value.valueType === "oxygen") return value.normallyOnSupplementalOxygen ? `${value.usualDeliveryMethod?.replaceAll("_", " ") ?? "Prescribed oxygen"}${value.usualFlowRateLitresPerMinute !== undefined ? ` · ${value.usualFlowRateLitresPerMinute} L/min` : ""}` : "Room air"; return value.conciseBaselineSummary ?? [value.usualConsciousness?.replaceAll("_", " "), value.usualGcsTotal ? `GCS ${value.usualGcsTotal}` : undefined].filter(Boolean).join(" · "); }
function validateRequired(input: Pick<CreateBaselineInput, "clinicalRationale" | "source" | "reviewDate" | "effectiveFrom">) { if (!input.clinicalRationale.trim() || !input.source || !input.reviewDate || !input.effectiveFrom) throw new Error("Clinical rationale, source, effective date and review date are required."); }
function replace(repository: BaselineRepository, record: ResidentClinicalBaseline) { repository.baselines = repository.baselines.map((item) => item.id === record.id ? record : item); return record; }
function emit(repository: BaselineRepository, record: ResidentClinicalBaseline, eventName: ResidentBaselineEvent["eventName"], actorId: string, occurredAt: string, correlationId: string, createId: () => string) { repository.events.push({ eventId: createId(), eventName, baselineId: record.id, residentId: record.residentId, nursingHomeId: record.nursingHomeId, baselineType: record.baselineType, safeSummary: displayBaselineValue(record.baselineValue), effectiveFrom: record.effectiveFrom, reviewDate: record.reviewDate, sourceReference: record.sourceEntityId, actorId, correlationId, occurredAt }); }
function reviewState(reviewDate: string, at: string): "current" | "due_soon" | "due_today" | "overdue" { const today = at.slice(0, 10); if (reviewDate < today) return "overdue"; if (reviewDate === today) return "due_today"; return new Date(reviewDate).getTime() - new Date(today).getTime() <= 14 * 86400000 ? "due_soon" : "current"; }
