import { useState } from "react";
import { useCare } from "@/lib/care/store";
import type { Resident } from "@/lib/care/types";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Button } from "@/components/ui/button";
import { toast } from "sonner";

const residentTypes = ["Long-Term Resident", "Short-Term Resident", "Respite", "Convalescence", "Rehabilitation", "Day Care", "Assessment", "Palliative Care", "Other"];
const referredFrom = ["Home", "Acute Hospital", "Community Hospital", "Another Nursing Home", "Assisted Living", "Community", "GP Referral", "Public Health Nurse", "Family Referral", "Hospice", "Other"];
const referralSources = ["Hospital", "GP", "Public Health Nurse", "Family", "Social Worker", "Community Intervention Team", "Another Nursing Home", "Self Referral", "Other"];
const blank = { firstName: "", lastName: "", dob: "", gender: "", residentType: "", referredFrom: "", referralSource: "", proposedAdmissionDate: "", primaryContactName: "", primaryContactPhone: "" };

export function QuickPreAdmissionDialog({ open, onOpenChange }: { open: boolean; onOpenChange: (open: boolean) => void }) {
  const { addResident } = useCare(); const [form, setForm] = useState(blank); const update = (patch: Partial<typeof blank>) => setForm((current) => ({ ...current, ...patch }));
  const close = () => { setForm(blank); onOpenChange(false); };
  const save = () => { if (!form.firstName.trim() || !form.lastName.trim() || !form.dob || !form.gender || !form.residentType || !form.referredFrom) { toast.error("Please complete all required fields."); return; } addResident({ firstName: form.firstName.trim(), lastName: form.lastName.trim(), dob: form.dob, gender: form.gender as Resident["gender"], roomNumber: "", admissionDate: "", primaryDiagnosis: "", medicalHistory: "", allergies: "", gp: "", consultant: "", nextOfKin: form.primaryContactName, emergencyContact: form.primaryContactPhone, communicationNeeds: "", religion: "", preferredLanguage: "", mentalCapacity: "not_assessed", endOfLife: false, currentMedication: "", status: "pre_admission", preAdmission: { residentType: form.residentType, referredFrom: form.referredFrom, referralSource: form.referralSource || undefined, proposedAdmissionDate: form.proposedAdmissionDate || undefined, primaryContactName: form.primaryContactName || undefined, primaryContactPhone: form.primaryContactPhone || undefined, createdAt: new Date().toISOString() } }); toast.success("Pre-admission saved."); close(); };
  return <Dialog open={open} onOpenChange={(value) => value || close()}><DialogContent className="max-w-2xl"><DialogHeader><DialogTitle>Create Pre-Admission</DialogTitle></DialogHeader><div className="grid gap-3 md:grid-cols-2"><Field label="First Name *"><Input value={form.firstName} onChange={(e) => update({ firstName: e.target.value })} /></Field><Field label="Last Name *"><Input value={form.lastName} onChange={(e) => update({ lastName: e.target.value })} /></Field><Field label="Date of Birth *"><Input type="date" value={form.dob} onChange={(e) => update({ dob: e.target.value })} /></Field><Choice label="Gender *" value={form.gender} options={["female", "male", "other"]} onChange={(gender) => update({ gender })} /><Choice label="Resident Type *" value={form.residentType} options={residentTypes} onChange={(residentType) => update({ residentType })} /><Choice label="Referred From *" value={form.referredFrom} options={referredFrom} onChange={(value) => update({ referredFrom: value })} /><Choice label="Referral Source" value={form.referralSource} options={referralSources} onChange={(referralSource) => update({ referralSource })} /><Field label="Proposed Admission Date"><Input type="date" value={form.proposedAdmissionDate} onChange={(e) => update({ proposedAdmissionDate: e.target.value })} /></Field><Field label="Primary Contact Name"><Input value={form.primaryContactName} onChange={(e) => update({ primaryContactName: e.target.value })} /></Field><Field label="Primary Contact Phone"><Input type="tel" value={form.primaryContactPhone} onChange={(e) => update({ primaryContactPhone: e.target.value })} /></Field></div><DialogFooter><Button variant="outline" onClick={close}>Cancel</Button><Button onClick={save}>Save Pre-Admission</Button></DialogFooter></DialogContent></Dialog>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div className="space-y-1"><Label>{label}</Label>{children}</div>; }
function Choice({ label, value, options, onChange }: { label: string; value: string; options: string[]; onChange: (value: string) => void }) { return <Field label={label}><Select value={value} onValueChange={onChange}><SelectTrigger><SelectValue placeholder="Select option" /></SelectTrigger><SelectContent>{options.map((option) => <SelectItem key={option} value={option}>{option === "female" ? "Female" : option === "male" ? "Male" : option === "other" ? "Other" : option}</SelectItem>)}</SelectContent></Select></Field>; }
