import { useMemo, useState } from "react";
import { Activity, ArrowRight, CheckCircle2 } from "lucide-react";
import { Badge } from "@/components/ui/badge"; import { Button } from "@/components/ui/button"; import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { getResidentRecentClinicalChanges, type RecentChangesFilters, type ResidentRecentClinicalChangesViewModel } from "@/lib/care/residentRecentClinicalChanges";
import type { WorkItem } from "@/domain/work/workTypes"; import type { RltTimelineItem } from "@/lib/care/rltTimeline"; import type { Alert } from "@/lib/care/types";
export function ResidentRecentClinicalChanges({ residentId, nursingHomeId, timeline, workItems, alerts, capabilities, onOpen }: { residentId: string; nursingHomeId: string; timeline: RltTimelineItem[]; workItems: WorkItem[]; alerts: Alert[]; capabilities: string[]; onOpen: (route: string) => void }) {
  const [period, setPeriod] = useState<RecentChangesFilters["period"]>("7d"); const [direction, setDirection] = useState<RecentChangesFilters["direction"]>("all");
  const model: ResidentRecentClinicalChangesViewModel = useMemo(() => getResidentRecentClinicalChanges({ residentId, nursingHomeId, timeline, workItems, alerts, capabilities, filters: { period, direction } }), [residentId, nursingHomeId, timeline, workItems, alerts, capabilities, period, direction]);
  return <Card><CardHeader className="pb-3"><CardTitle className="flex items-center gap-2 text-base"><Activity className="h-4 w-4" />Recent Clinical Changes</CardTitle><p className="text-sm text-muted-foreground">Important clinical changes and events recorded during the selected period.</p></CardHeader><CardContent className="space-y-4">
    <div className="flex flex-wrap gap-2">{([['24h','24 Hours'],['7d','7 Days'],['30d','30 Days']] as const).map(([key,label]) => <Button key={key} size="sm" variant={period === key ? "secondary" : "outline"} onClick={() => setPeriod(key)}>{label}</Button>)}{([['all','All Types'],['deteriorating','Deteriorating'],['improving','Improving'],['new_issue','New Issues'],['resolved','Resolved']] as const).map(([key,label]) => <Button key={key} size="sm" variant={direction === key ? "secondary" : "ghost"} onClick={() => setDirection(key)}>{label}</Button>)}</div>
    <div className="grid grid-cols-2 gap-2 sm:grid-cols-5">{Object.entries({ Deteriorating: model.summary.deteriorating, Improving: model.summary.improving, "New Issues": model.summary.newIssues, Resolved: model.summary.resolved, "Action Required": model.summary.requiringAction }).map(([label,value]) => <div key={label} className="rounded-md border p-2"><div className="text-[11px] text-muted-foreground">{label}</div><div className="text-xl font-semibold">{value}</div></div>)}</div>
    {model.changes.length ? <div className="space-y-2">{model.changes.map((change) => <div key={change.id} className="rounded-lg border p-3"><div className="flex flex-col gap-3 sm:flex-row sm:justify-between"><div className="space-y-1"><div className="text-xs text-muted-foreground">{new Date(change.occurredAt).toLocaleString("en-IE")}</div><div className="font-medium">{change.title}</div><div className="flex flex-wrap gap-1"><Badge variant={change.severity === "critical" ? "destructive" : "outline"}>{change.direction.replace(/_/g," ")} · {change.severity}</Badge>{change.rltDomains.map((d) => <Badge key={d.rltDomainId} variant="secondary">{d.displayName}</Badge>)}</div><p className="text-sm text-muted-foreground">{change.conciseSummary}</p><p className="flex items-center gap-1 text-xs text-muted-foreground"><CheckCircle2 className="h-3.5 w-3.5" />{change.followUp.required && !change.followUp.completed ? "Follow-up remains outstanding" : "No outstanding linked follow-up"}</p></div>{change.source.route && <Button size="sm" variant="outline" onClick={() => onOpen(change.source.route!)}>Open Record<ArrowRight className="ml-1 h-3.5 w-3.5" /></Button>}</div></div>)}</div> : <p className="rounded-md border border-dashed p-3 text-sm text-muted-foreground">No important clinical changes have been recorded in the selected period.</p>}
  </CardContent></Card>;
}
