import { Activity, AlertTriangle, ArrowRight, ClipboardCheck, HeartHandshake, ListChecks, ShieldAlert, Sparkles, Stethoscope, TrendingUp } from "lucide-react";
import type { ReactNode } from "react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import type { ResidentClinicalOverview as Overview } from "@/lib/care/residentClinicalOverview";

const titleCase = (value: string) => value.replace(/_/g, " ").replace(/\b\w/g, (letter) => letter.toUpperCase());
const severityClass = (severity: string) => severity === "critical" ? "border-red-400 bg-red-50 text-red-900" : severity === "high" ? "border-orange-300 bg-orange-50 text-orange-900" : severity === "medium" ? "border-amber-300 bg-amber-50 text-amber-900" : "border-slate-200 bg-slate-50 text-slate-800";

export function ResidentClinicalOverview({ overview, onOpenSection }: { overview: Overview; onOpenSection: (section: string) => void }) {
  return <section className="space-y-4" aria-label="Resident Clinical Overview">
    <div className="grid gap-4 lg:grid-cols-[1.35fr_1fr]">
      <Card className="border-blue-200 bg-blue-50/30"><CardHeader className="pb-2"><CardTitle className="flex items-center gap-2 text-base"><Stethoscope className="h-4 w-4 text-blue-700" />Current Clinical Story <Badge variant="outline">{titleCase(overview.currentClinicalStory.clinicalDirection)}</Badge></CardTitle></CardHeader><CardContent className="space-y-3"><p className="text-lg font-medium leading-relaxed">{overview.currentClinicalStory.headline}</p>{overview.currentClinicalStory.summaryPoints.length ? <ul className="space-y-1 text-sm text-muted-foreground">{overview.currentClinicalStory.summaryPoints.map((point) => <li key={point} className="flex gap-2"><span aria-hidden>•</span><span>{point}</span></li>)}</ul> : <p className="text-sm text-muted-foreground">No important clinical changes recorded in the selected period.</p>}</CardContent></Card>
      <Card className={overview.currentPriorities.some((item) => ["critical", "urgent"].includes(item.priority)) ? "border-orange-300" : ""}><CardHeader className="pb-2"><CardTitle className="flex items-center gap-2 text-base"><ListChecks className="h-4 w-4" />What Requires Attention Now</CardTitle></CardHeader><CardContent className="space-y-2">{overview.currentPriorities.length ? overview.currentPriorities.slice(0, 5).map((item) => <button key={item.code} onClick={() => onOpenSection(item.route)} className="flex w-full items-start justify-between gap-3 rounded-md border p-2 text-left text-sm hover:bg-muted"><span><span className="font-medium">{item.label}</span><span className="block text-xs text-muted-foreground">{item.reason}</span></span><ArrowRight className="mt-1 h-3 w-3 shrink-0" /></button>) : <p className="text-sm text-muted-foreground">No current work is due for this resident.</p>}</CardContent></Card>
    </div>
    <Card><CardHeader className="pb-2"><CardTitle className="flex items-center gap-2 text-base"><ShieldAlert className="h-4 w-4" />Immediate Clinical Alerts</CardTitle></CardHeader><CardContent>{overview.immediateAlerts.length ? <div className="grid gap-2 md:grid-cols-2 xl:grid-cols-3">{overview.immediateAlerts.slice(0, 9).map((alert) => <button key={alert.id} onClick={() => alert.route && onOpenSection(alert.route)} className={`rounded-md border p-3 text-left ${severityClass(alert.severity)}`}><span className="flex items-center gap-2 font-medium"><AlertTriangle className="h-4 w-4" />{alert.label}</span>{alert.conciseExplanation && <span className="mt-1 block text-xs opacity-80">{alert.conciseExplanation}</span>}</button>)}</div> : <p className="text-sm text-muted-foreground">No immediate clinical alerts.</p>}</CardContent></Card>
    <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">
      <Summary icon={<ClipboardCheck className="h-4 w-4" />} title="Care Planning" action={() => onOpenSection("activities")} lines={[`${overview.carePlanning.activeCarePlanCount} active Nursing Care Plans`, overview.carePlanning.overdueCount ? `${overview.carePlanning.overdueCount} overdue reviews` : overview.carePlanning.dueTodayCount ? `${overview.carePlanning.dueTodayCount} reviews due today` : "No reviews overdue", overview.carePlanning.domainsWithPlans.slice(0, 4).join(" · ") || "No active Nursing Care Plans"]} />
      <Summary icon={<Activity className="h-4 w-4" />} title="Assessments and Observations" action={() => onOpenSection("assessments")} lines={[`${overview.assessments.overdueCount} assessments overdue · ${overview.assessments.dueCount} due`, overview.observations.latestNews2 ? `Latest NEWS2 ${overview.observations.latestNews2.score} · ${overview.observations.latestNews2.risk || "risk not classified"}` : "No current NEWS2 summary", `${overview.observations.attentionCount} observation alerts require attention`]} />
      <Summary icon={<ShieldAlert className="h-4 w-4" />} title="Active Risks" action={() => onOpenSection("alerts")} lines={overview.risks.length ? overview.risks.slice(0, 4).map((item) => `${item.label} · ${titleCase(item.level)}`) : ["No active risks available at your access level."]} />
      {overview.nutritionAndWeight && <Summary icon={<TrendingUp className="h-4 w-4" />} title="Nutrition and Weight" action={() => onOpenSection("vitals")} lines={[overview.nutritionAndWeight.latestWeightKg !== undefined ? `Latest weight ${overview.nutritionAndWeight.latestWeightKg} kg · ${overview.nutritionAndWeight.recordedAt}` : "Latest weight not recorded", overview.nutritionAndWeight.concern || "No source-recorded nutrition alert", overview.nutritionAndWeight.carePlanStatus ? `Care Plan: ${titleCase(overview.nutritionAndWeight.carePlanStatus)}` : "Eating and Drinking Care Plan status not recorded"]} />}
      <Summary icon={<Activity className="h-4 w-4" />} title="Mobility and Falls" action={() => onOpenSection("activities")} lines={[`Dependency: ${overview.mobilityAndFalls.dependency}`, overview.mobilityAndFalls.fallsRisk ? `Falls risk: ${titleCase(overview.mobilityAndFalls.fallsRisk)}` : "Falls risk not recorded", overview.mobilityAndFalls.recentFall ? `Latest recorded fall ${overview.mobilityAndFalls.recentFall.date}` : "No recent fall in available incident records"]} />
      <Summary icon={<ListChecks className="h-4 w-4" />} title="Current Work" action={() => onOpenSection("tasks")} lines={[`${overview.currentWork.overdue} overdue · ${overview.currentWork.dueToday} due today`, `${overview.currentWork.activeCount} active work items`, ...overview.currentWork.items.slice(0, 2).map((item) => item.title)]} />
      <Summary icon={<Sparkles className="h-4 w-4" />} title="Strengths and Preferences" action={() => onOpenSection("activities")} lines={[`Resident Can Do: ${overview.strengthsAndPreferences.canDo.join(" · ") || "Not yet recorded"}`, `Resident Prefers: ${overview.strengthsAndPreferences.prefers.join(" · ") || "Not yet recorded"}`, `Please Avoid: ${overview.strengthsAndPreferences.pleaseAvoid.join(" · ") || "Not yet recorded"}`]} />
      <Summary icon={<Stethoscope className="h-4 w-4" />} title="Incidents and Handover" action={() => onOpenSection("incidents")} lines={[`${overview.incidents.recentCount} incidents in the recent period`, `${overview.incidents.unresolvedFollowUpCount} unresolved follow-ups`, overview.handover.latestImportant ? `Handover: ${overview.handover.latestImportant.summary}` : "No current important handover"]} />
      {overview.endOfLife?.pathway && <Summary icon={<HeartHandshake className="h-4 w-4" />} title="End-of-Life" action={() => onOpenSection("dying")} lines={[`Pathway: ${titleCase(overview.endOfLife.pathway.status)}`, overview.endOfLife.comfortPriorities.length ? `Comfort: ${overview.endOfLife.comfortPriorities.map(titleCase).join(" · ")}` : "Comfort priorities not recorded", overview.endOfLife.gpPalliativeSummary, overview.endOfLife.familyCommunicationStatus]} />}
    </div>
    <Card><CardHeader className="pb-2"><CardTitle className="text-base">Recent Important Changes</CardTitle></CardHeader><CardContent>{overview.recentChanges.length ? <div className="grid gap-2 md:grid-cols-2">{overview.recentChanges.slice(0, 6).map((item) => <button key={item.id} onClick={() => item.route && onOpenSection(item.route)} className="rounded-md border p-2 text-left text-sm hover:bg-muted"><span className="font-medium">{item.label}</span><span className="block text-xs text-muted-foreground">{new Date(item.occurredAt).toLocaleString("en-IE")} · {titleCase(item.direction || "changed")}</span></button>)}</div> : <p className="text-sm text-muted-foreground">No important clinical changes recorded in the selected period.</p>}</CardContent></Card>
  </section>;
}

function Summary({ icon, title, lines, action }: { icon: ReactNode; title: string; lines: string[]; action: () => void }) { return <Card><CardHeader className="pb-2"><div className="flex items-center justify-between gap-2"><CardTitle className="flex items-center gap-2 text-sm">{icon}{title}</CardTitle><Button variant="ghost" size="sm" onClick={action}>Open</Button></div></CardHeader><CardContent className="space-y-1 text-sm">{lines.map((line, index) => <p key={`${line}:${index}`} className={index === 0 ? "font-medium" : "text-muted-foreground"}>{line}</p>)}</CardContent></Card>; }
