import type { DailyCareType } from "./dailyCareTypes";

export interface PersonalCareDetails { type: "personal_care"; careProvided: Array<"full_body_wash" | "partial_wash" | "shower" | "bath" | "bed_bath" | "face_and_hands" | "hair_care" | "shaving" | "nail_care" | "perineal_care" | "other">; preferredRoutineFollowed?: boolean; privacyMaintained?: boolean; sameGenderPreferenceMet?: boolean; productsUsed?: string[]; skinConcernsObserved?: boolean; linkedSkinObservationRecordId?: string }
export interface DressingCareDetails { type: "dressing"; dressingState: "day_clothes" | "night_clothes" | "changed_clothing" | "undressed" | "other"; residentChoseClothing?: boolean; assistanceAreas?: string[]; clothingAppropriateForTemperature?: boolean; footwearRecorded?: string; appearancePreferencesFollowed?: boolean }
export interface OralCareDetails { type: "oral_care"; oralCareProvided: Array<"teeth_brushed" | "dentures_cleaned" | "mouth_rinse" | "mouth_moisturised" | "lip_care" | "oral_inspection" | "other">; dentures: "not_applicable" | "in_place" | "removed" | "cleaned" | "not_worn" | "missing_or_damaged" | "not_recorded"; oralCondition?: Array<"healthy" | "dry_mouth" | "coated_tongue" | "sore_mouth" | "bleeding" | "ulceration" | "swallowing_concern" | "other">; followUpSuggested?: boolean }
export interface ToiletingCareDetails { type: "toileting"; toiletingMethod: "toilet" | "commode" | "bedpan" | "urinal" | "assisted_transfer" | "other"; outcome: "urine" | "bowel_motion" | "both" | "no_output" | "attempt_only" | "not_recorded"; assistanceProvided?: string[]; privacyMaintained?: boolean; prompted?: boolean; urgencyObserved?: boolean; discomfortObserved?: boolean }
export interface ContinenceCareDetails { type: "continence"; continenceState: "continent" | "urinary_incontinence" | "faecal_incontinence" | "double_incontinence" | "not_observed"; productUsed?: string; productChanged?: boolean; skinCareProvided?: boolean; leakageObserved?: boolean; odourOrAppearanceConcern?: boolean; residentComfortableAfterCare?: boolean; catheterOrStomaReferenceId?: string }
export interface RepositioningCareDetails { type: "repositioning"; fromPosition?: string; toPosition: string; technique?: string; equipmentUsed?: string[]; numberOfStaff?: number; pressureReliefApplied?: boolean; residentComfortAfter?: boolean; skinObserved?: boolean; skinConcernObserved?: boolean }
export interface FoodCareDetails { type: "food"; mealType: "breakfast" | "morning_snack" | "lunch" | "afternoon_snack" | "evening_meal" | "supper" | "other"; foodOffered?: string[]; portionOffered?: "small" | "standard" | "large" | "not_recorded"; intake: "none" | "quarter" | "half" | "three_quarters" | "all" | "not_recorded"; assistance: "independent" | "prompting" | "supervision" | "partial_assistance" | "full_assistance" | "not_recorded"; prescribedTextureReferenceId?: string; textureProvided?: string; adaptedEquipmentUsed?: string[]; diningLocation?: string; residentEnjoyedMeal?: boolean; swallowingConcernObserved?: boolean; reasonForReducedIntake?: string }
export interface FluidCareDetails { type: "fluids"; drinkType?: string; amountOfferedMl?: number; amountTakenMl?: number; intakeEstimate: "none" | "small_amount" | "half" | "most" | "all" | "measured" | "not_recorded"; assistance: "independent" | "prompting" | "supervision" | "partial_assistance" | "full_assistance" | "not_recorded"; prescribedConsistencyReferenceId?: string; consistencyProvided?: string; adaptedCupOrEquipment?: string[]; swallowingConcernObserved?: boolean; reasonForReducedIntake?: string }
export interface MobilityCareDetails { type: "mobility"; mobilityActivity: "walked" | "transferred" | "stood" | "wheelchair_mobility" | "bed_mobility" | "exercise" | "other"; distanceOrDuration?: string; assistance: "independent" | "prompting" | "supervision" | "one_person_assistance" | "two_person_assistance" | "full_support" | "not_recorded"; mobilityAidUsed?: string[]; transferEquipmentUsed?: string[]; residentTolerance?: "good" | "fair" | "poor" | "not_recorded"; painObserved?: boolean; breathlessnessObserved?: boolean; nearFallOrSafetyConcern?: boolean }
export interface ComfortCareDetails { type: "comfort"; comfortState: "comfortable" | "mild_discomfort" | "moderate_discomfort" | "severe_discomfort" | "unable_to_assess"; comfortMeasures: Array<"repositioned" | "blanket_or_temperature_adjustment" | "quiet_environment" | "reassurance" | "oral_care" | "toileting" | "music_or_activity" | "family_presence" | "other">; discomfortLocation?: string[]; nonVerbalSigns?: string[]; responseToComfortMeasures?: string; painAssessmentSuggested?: boolean }
export interface SleepCareDetails { type: "sleep"; state: "settled" | "asleep" | "awake" | "restless" | "frequently_waking" | "distressed" | "not_observed"; sleepStartAt?: string; wakeAt?: string; estimatedSleepDurationMinutes?: number; nightChecksCompleted?: number; interventionsProvided?: string[]; usualRoutineFollowed?: boolean; environmentalFactors?: string[]; reasonForPoorSleep?: string }
export interface MoodCareDetails { type: "mood"; observedMood: "content" | "calm" | "happy" | "low" | "anxious" | "tearful" | "angry" | "withdrawn" | "variable" | "unable_to_assess" | "other"; residentReportedMood?: string; contributingFactors?: string[]; supportiveActions?: string[]; responseToSupport?: string; significantChangeFromUsual?: boolean }
export interface BehaviourCareDetails { type: "behaviour"; behaviourObserved: string[]; possibleTriggers?: string[]; antecedentSummary?: string; responseProvided?: string[]; outcome?: string; riskToSelfOrOthers?: boolean; restrictivePracticeUsed?: boolean; restrictivePracticeRecordId?: string; behaviourIncidentRequired?: boolean }
export interface ActivityCareDetails { type: "activity"; activityType: "individual" | "group" | "social" | "recreational" | "religious_or_spiritual" | "exercise" | "outdoor" | "sensory" | "family_contact" | "other"; activityName: string; durationMinutes?: number; participation: "active" | "partial" | "observed" | "declined" | "unable_to_participate"; enjoyment: "enjoyed" | "neutral" | "did_not_enjoy" | "unable_to_assess" | "not_recorded"; supportProvided?: string[]; residentResponse?: string }
export interface RefusalCareDetails { type: "refusal"; refusedCareType: DailyCareType | "observation" | "assessment" | "care_action" | "medication" | "other"; refusedSourceEntityType?: string; refusedSourceEntityId?: string; refusalReason: "resident_choice" | "distress" | "pain" | "fatigue" | "confusion" | "did_not_want_staff_member" | "preferred_later_time" | "did_not_understand" | "other" | "not_provided"; refusalReasonText?: string; explanationProvided?: boolean; alternativesOffered?: string[]; alternativeAccepted?: boolean; riskExplained?: boolean; nurseInformed?: boolean; representativeInformed?: boolean; followUpRequired: boolean; retryAt?: string }
export interface SkinObservationCareDetails { type: "skin_observation"; bodyAreasObserved: string[]; skinState: Array<"intact" | "dry" | "redness" | "bruising" | "rash" | "broken_skin" | "swelling" | "moisture_damage" | "pressure_concern" | "other">; blanchingStatus?: "blanching" | "non_blanching" | "not_assessed" | "not_applicable"; discomfortObserved?: boolean; protectiveCareProvided?: string[]; photographReferenceId?: string; woundAssessmentRequired?: boolean; incidentRequired?: boolean }

export type DailyCareDetails =
  | PersonalCareDetails | DressingCareDetails | OralCareDetails | ToiletingCareDetails
  | ContinenceCareDetails | RepositioningCareDetails | FoodCareDetails | FluidCareDetails
  | MobilityCareDetails | ComfortCareDetails | SleepCareDetails | MoodCareDetails
  | BehaviourCareDetails | ActivityCareDetails | RefusalCareDetails | SkinObservationCareDetails;
