import { useMemo, useState } from "react";
import type { ReactNode } from "react";
import { Plus } from "lucide-react";
import type { RltDomain } from "@/lib/care/rlt";
import {
  ABILITY_LABELS,
  ABILITY_LEVELS,
  PREFERENCE_CATEGORY_DOMAINS,
  STRENGTH_CATEGORIES,
  type CreatePreferenceInput,
  type CreateStrengthInput,
  type ResidentAbilityLevel,
  type ResidentPreference,
  type ResidentPreferenceCategory,
  type ResidentStrength,
  type ResidentStrengthCategory,
} from "@/lib/care/residentStrengthPreferences";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";

const words = (value: string) => value.split(",").map((item) => item.trim()).filter(Boolean);
const label = (value: string) => value.replace(/_/g, " ").replace(/\b\w/g, (char) => char.toUpperCase());

export function StrengthPreferencePanel({ domain, residentId, strengths, preferences, canCreateStrength, canCreatePreference, onCreateStrength, onCreatePreference }: {
  domain: RltDomain; residentId: string; strengths: ResidentStrength[]; preferences: ResidentPreference[]; canCreateStrength: boolean; canCreatePreference: boolean;
  onCreateStrength: (input: CreateStrengthInput) => void; onCreatePreference: (input: CreatePreferenceInput) => void;
}) {
  return <div className="grid gap-3 md:grid-cols-2">
    <RecordSection title="Resident Strengths" empty="No strengths have been recorded for this Activity of Living." action={canCreateStrength ? <StrengthDialog domain={domain} residentId={residentId} onSave={onCreateStrength} /> : null}>
      {strengths.map((item) => <div key={item.id} className="rounded-md border p-2 text-sm"><div className="flex items-center justify-between gap-2"><span className="font-medium">{item.title}</span><Badge variant="outline">{ABILITY_LABELS[item.abilityLevel]}</Badge></div><p className="mt-1 text-xs text-muted-foreground">{item.description}</p>{item.supportThatHelps.length > 0 && <p className="mt-1 text-xs">Support that helps: {item.supportThatHelps.join(", ")}</p>}<p className="mt-1 text-[11px] text-muted-foreground">Source: {label(item.source)}{item.lastReviewedAt ? ` · Reviewed ${item.lastReviewedAt.slice(0, 10)}` : ""}</p></div>)}
    </RecordSection>
    <RecordSection title="Resident Preferences" empty="No preferences have been recorded for this Activity of Living." action={canCreatePreference ? <PreferenceDialog domain={domain} residentId={residentId} onSave={onCreatePreference} /> : null}>
      {preferences.map((item) => <div key={item.id} className="rounded-md border p-2 text-sm"><div className="flex items-center justify-between gap-2"><span className="font-medium">{item.title}</span><Badge variant="outline">{label(item.importance)}</Badge></div><p className="mt-1 text-xs text-muted-foreground">{item.preference}</p>{item.residentOwnWords && <p className="mt-1 text-xs italic">“{item.residentOwnWords}”</p>}<div className="mt-1 flex flex-wrap gap-1"><Badge variant="secondary">{label(item.accommodationStatus)}</Badge>{item.safetyReviewStatus === "pending" && <Badge variant="destructive">Safety Review Required</Badge>}</div><p className="mt-1 text-[11px] text-muted-foreground">Source: {label(item.source)}{item.lastReviewedAt ? ` · Reviewed ${item.lastReviewedAt.slice(0, 10)}` : ""}</p></div>)}
    </RecordSection>
  </div>;
}

function RecordSection({ title, empty, action, children }: { title: string; empty: string; action: ReactNode; children: ReactNode }) {
  const hasChildren = Array.isArray(children) ? children.length > 0 : Boolean(children);
  return <section className="rounded-md bg-muted/20 p-3"><div className="mb-2 flex items-center justify-between gap-2"><h3 className="text-sm font-medium">{title}</h3>{action}</div><div className="space-y-2">{hasChildren ? children : <p className="text-xs text-muted-foreground">{empty}</p>}</div></section>;
}

function StrengthDialog({ domain, residentId, onSave }: { domain: RltDomain; residentId: string; onSave: (input: CreateStrengthInput) => void }) {
  const [open, setOpen] = useState(false); const [category, setCategory] = useState<ResidentStrengthCategory>("physical_ability"); const [ability, setAbility] = useState<ResidentAbilityLevel>("independent"); const [title, setTitle] = useState(""); const [description, setDescription] = useState(""); const [ownWords, setOwnWords] = useState(""); const [independent, setIndependent] = useState(""); const [supported, setSupported] = useState(""); const [support, setSupport] = useState(""); const [equipment, setEquipment] = useState("");
  const save = () => { onSave({ residentId, rltDomainId: domain.id, category, title: title.trim(), description: description.trim(), residentOwnWords: ownWords.trim() || undefined, abilityLevel: ability, canDoIndependently: words(independent), canDoWithSupport: words(supported), supportThatHelps: words(support), equipmentOrAdaptations: words(equipment), source: "resident", effectiveFrom: new Date().toISOString(), changeReasonCode: "initial_record" }); setOpen(false); };
  return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button size="sm" variant="outline"><Plus className="mr-1 h-3 w-3" />Add Strength</Button></DialogTrigger><DialogContent className="max-h-[90vh] max-w-xl overflow-y-auto"><DialogHeader><DialogTitle>Add Resident Strength · {domain.title}</DialogTitle></DialogHeader><div className="space-y-4"><FormHeading>What the Resident Can Do</FormHeading><Field label="Title"><Input value={title} onChange={(e) => setTitle(e.target.value)} /></Field><Field label="Description"><Textarea value={description} onChange={(e) => setDescription(e.target.value)} /></Field><div className="grid gap-3 sm:grid-cols-2"><Field label="Category"><Select value={category} onValueChange={(v) => setCategory(v as ResidentStrengthCategory)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{STRENGTH_CATEGORIES.map((item) => <SelectItem key={item} value={item}>{label(item)}</SelectItem>)}</SelectContent></Select></Field><Field label="Ability Level"><Select value={ability} onValueChange={(v) => setAbility(v as ResidentAbilityLevel)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{ABILITY_LEVELS.map((item) => <SelectItem key={item} value={item}>{ABILITY_LABELS[item]}</SelectItem>)}</SelectContent></Select></Field></div><FormHeading>Independence and Support</FormHeading><Field label="Can Do Independently"><Input value={independent} onChange={(e) => setIndependent(e.target.value)} placeholder="Separate items with commas" /></Field><Field label="Can Do With Support"><Input value={supported} onChange={(e) => setSupported(e.target.value)} /></Field><Field label="Support That Helps"><Input value={support} onChange={(e) => setSupport(e.target.value)} /></Field><Field label="Equipment or Adaptations"><Input value={equipment} onChange={(e) => setEquipment(e.target.value)} /></Field><FormHeading>Source and Review</FormHeading><Field label="Resident’s Own Words"><Textarea maxLength={500} value={ownWords} onChange={(e) => setOwnWords(e.target.value)} /></Field><p className="text-xs text-muted-foreground">Source: Resident · Effective today. Contributor fields are required when another source is selected in the full review workflow.</p></div><DialogFooter><Button variant="outline" onClick={() => setOpen(false)}>Cancel</Button><Button disabled={!title.trim() || !description.trim()} onClick={save}>Save Strength</Button></DialogFooter></DialogContent></Dialog>;
}

function PreferenceDialog({ domain, residentId, onSave }: { domain: RltDomain; residentId: string; onSave: (input: CreatePreferenceInput) => void }) {
  const categories = useMemo(() => (Object.keys(PREFERENCE_CATEGORY_DOMAINS) as ResidentPreferenceCategory[]).filter((item) => PREFERENCE_CATEGORY_DOMAINS[item].includes(domain.id)), [domain.id]); const [open, setOpen] = useState(false); const [category, setCategory] = useState<ResidentPreferenceCategory>(categories[0] || "other"); const [title, setTitle] = useState(""); const [preference, setPreference] = useState(""); const [ownWords, setOwnWords] = useState(""); const [likes, setLikes] = useState(""); const [dislikes, setDislikes] = useState(""); const [avoid, setAvoid] = useState(""); const [importance, setImportance] = useState<"routine" | "important" | "essential">("important"); const [safety, setSafety] = useState(false); const [sensitivity, setSensitivity] = useState<"standard" | "sensitive" | "highly_sensitive">(domain.id === "expressing_sexuality" ? "sensitive" : "standard");
  const save = () => { onSave({ residentId, rltDomainId: domain.id, category, title: title.trim(), preference: preference.trim(), residentOwnWords: ownWords.trim() || undefined, importance, applicability: "when_possible", preferredOptions: words(likes), dislikedOptions: words(dislikes), avoid: words(avoid), source: "resident", statedByResident: true, safetyReviewRequired: safety, safetyReviewStatus: safety ? "pending" : "not_required", accommodationStatus: "not_reviewed", sensitivity, effectiveFrom: new Date().toISOString(), changeReasonCode: "initial_record" }); setOpen(false); };
  return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button size="sm" variant="outline"><Plus className="mr-1 h-3 w-3" />Add Preference</Button></DialogTrigger><DialogContent className="max-h-[90vh] max-w-xl overflow-y-auto"><DialogHeader><DialogTitle>Add Resident Preference · {domain.title}</DialogTitle></DialogHeader><div className="space-y-4"><FormHeading>What Matters to the Resident</FormHeading><Field label="Title"><Input value={title} onChange={(e) => setTitle(e.target.value)} /></Field><Field label="Preference"><Textarea value={preference} onChange={(e) => setPreference(e.target.value)} /></Field><Field label="Resident’s Own Words"><Textarea maxLength={500} value={ownWords} onChange={(e) => setOwnWords(e.target.value)} /></Field><div className="grid gap-3 sm:grid-cols-2"><Field label="Category"><Select value={category} onValueChange={(v) => setCategory(v as ResidentPreferenceCategory)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{categories.map((item) => <SelectItem key={item} value={item}>{label(item)}</SelectItem>)}</SelectContent></Select></Field><Field label="Importance"><Select value={importance} onValueChange={(v) => setImportance(v as typeof importance)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{["routine", "important", "essential"].map((item) => <SelectItem key={item} value={item}>{label(item)}</SelectItem>)}</SelectContent></Select></Field></div><FormHeading>Details</FormHeading><Field label="Likes"><Input value={likes} onChange={(e) => setLikes(e.target.value)} placeholder="Separate items with commas" /></Field><Field label="Dislikes"><Input value={dislikes} onChange={(e) => setDislikes(e.target.value)} /></Field><Field label="Please Avoid"><Input value={avoid} onChange={(e) => setAvoid(e.target.value)} /></Field><FormHeading>Accommodation and Safety</FormHeading><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={safety} onChange={(e) => setSafety(e.target.checked)} />Safety Review Required</label><Field label="Sensitivity"><Select value={sensitivity} onValueChange={(v) => setSensitivity(v as typeof sensitivity)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{["standard", "sensitive", "highly_sensitive"].map((item) => <SelectItem key={item} value={item}>{label(item)}</SelectItem>)}</SelectContent></Select></Field><p className="text-xs text-muted-foreground">Source: Resident · Stated by Resident · Accommodation: Not Reviewed. This preference does not update a Care Plan or Care Action.</p></div><DialogFooter><Button variant="outline" onClick={() => setOpen(false)}>Cancel</Button><Button disabled={!title.trim() || !preference.trim()} onClick={save}>Save Preference</Button></DialogFooter></DialogContent></Dialog>;
}

function Field({ label: text, children }: { label: string; children: ReactNode }) { return <div className="space-y-1"><Label>{text}</Label>{children}</div>; }
function FormHeading({ children }: { children: ReactNode }) { return <h3 className="border-b pb-1 text-sm font-medium">{children}</h3>; }
