import type { ConsciousnessLevel } from "@/domain/observations/observationTypes";

export type News2PolicyStatus = "draft" | "pending_approval" | "approved" | "retired";
export interface News2NumericScoreBand { minimum?: number; minimumInclusive?: boolean; maximum?: number; maximumInclusive?: boolean; score: number; label?: string }
export interface News2ScoringPolicy { respiratoryRateBands: News2NumericScoreBand[]; scale1Spo2Bands: News2NumericScoreBand[]; scale2Spo2Bands: News2NumericScoreBand[]; systolicBloodPressureBands: News2NumericScoreBand[]; pulseBands: News2NumericScoreBand[]; temperatureBands: News2NumericScoreBand[]; oxygenSupplementationScore: number; consciousnessScores: Array<{ consciousnessLevel: ConsciousnessLevel; score: number }> }
export interface News2EscalationRule { id: string; minimumScore?: number; maximumScore?: number; interpretation: "low" | "low_single_parameter" | "medium" | "high"; escalationRequired: boolean; repeatObservationAfterMinutes?: number; targetKeys: string[]; explanation: string }
export interface News2EscalationPolicy { totalScoreRules: News2EscalationRule[]; singleParameterRules: Array<{ id: string; componentScore: number; interpretation: "low_single_parameter"; escalationRequired: boolean; repeatObservationAfterMinutes?: number; targetKeys: string[]; explanation: string }>; clinicalOverrideAllowed: boolean; manualEscalationAllowed: boolean }
export interface News2Scale2EligibilityPolicy { requiresExplicitResidentAuthorisation: boolean; acceptedSourceTypes: string[] }
export interface News2IncompleteSetPolicy { allowManualScore: boolean; requireMissingComponentDisplay: boolean }
export interface News2RepeatObservationPolicy { createWorkItems: boolean; deduplicationWindowMinutes: number }
export interface News2Policy { id: string; name: string; version: number; status: News2PolicyStatus; nursingHomeId?: string; enterpriseId?: string; effectiveFrom: string; effectiveTo?: string; scoringPolicy: News2ScoringPolicy; escalationPolicy: News2EscalationPolicy; scale2EligibilityPolicy: News2Scale2EligibilityPolicy; incompleteSetPolicy: News2IncompleteSetPolicy; repeatObservationPolicy: News2RepeatObservationPolicy; approvedByUserAccountId?: string; approvedByStaffMemberId?: string; approvedAt?: string; sourceDocumentId?: string; sourcePolicyReference?: string; createdAt: string; updatedAt: string }
export interface News2ResidentConfiguration { requestedScale: "scale_1" | "scale_2"; scale2Authorisation?: { authorised: boolean; sourceType: string; sourceId: string; effectiveFrom: string; effectiveTo?: string } }
export interface PolicyNews2Result { status: "calculated" | "incomplete" | "unavailable" | "scale_not_authorised"; totalScore?: number; componentScores: { respirations?: number; spo2?: number; oxygenSupplementation?: number; systolicBloodPressure?: number; pulse?: number; consciousness?: number; temperature?: number }; scale?: "scale_1" | "scale_2"; interpretation?: "low" | "low_single_parameter" | "medium" | "high"; incompleteReason?: string; missingComponents: string[]; calculatedAt: string; policyId?: string; policyVersion?: number; calculationVersion: string; explanation: string }
