import type { DomainEventType } from "./eventTypes";

export interface EventCatalogueEntry {
  eventType: DomainEventType;
  eventVersion: 1;
  meaning: string;
  sourceModule: string;
  primaryEntity: string;
  requiredPayloadFields: string[];
  sensitiveFieldsProhibited: string[];
  emitsOnlyAfterPersistedChange: boolean;
}

function strengthPreferenceEventEntry(eventType: Extract<DomainEventType, `ResidentStrength${string}` | `ResidentPreference${string}`>, meaning: string): EventCatalogueEntry {
  return {
    eventType,
    eventVersion: 1,
    meaning,
    sourceModule: "resident_strength_preferences",
    primaryEntity: eventType.startsWith("ResidentStrength") ? "ResidentStrength" : "ResidentPreference",
    requiredPayloadFields: ["recordId", "residentId", "nursingHomeId", "actorUserAccountId", "safeSummary"],
    sensitiveFieldsProhibited: ["preference", "residentOwnWords", "description", "freeTextNarrative"],
    emitsOnlyAfterPersistedChange: true,
  };
}

export const EVENT_CATALOGUE: Record<DomainEventType, EventCatalogueEntry> = {
  ResidentAdmitted: {
    eventType: "ResidentAdmitted",
    eventVersion: 1,
    meaning: "A resident admission became active.",
    sourceModule: "resident_lifecycle",
    primaryEntity: "Admission",
    requiredPayloadFields: ["residentId", "admissionId", "admissionType", "admittedAt", "nursingHomeId"],
    sensitiveFieldsProhibited: ["fullCarePlan", "freeTextNarrative"],
    emitsOnlyAfterPersistedChange: true,
  },
  ResidentReturnedFromHospital: {
    eventType: "ResidentReturnedFromHospital",
    eventVersion: 1,
    meaning: "An active resident returned from a hospital-transfer absence.",
    sourceModule: "resident_lifecycle",
    primaryEntity: "AbsenceEpisode",
    requiredPayloadFields: ["residentId", "admissionId", "absenceEpisodeId", "returnedAt", "nursingHomeId"],
    sensitiveFieldsProhibited: ["dischargeSummary", "medicationList"],
    emitsOnlyAfterPersistedChange: true,
  },
  ObservationRecorded: {
    eventType: "ObservationRecorded",
    eventVersion: 1,
    meaning: "A new clinical observation was persisted.",
    sourceModule: "observations",
    primaryEntity: "ClinicalObservation",
    requiredPayloadFields: ["observationId", "residentId", "observationType", "observedAt", "values", "nursingHomeId"],
    sensitiveFieldsProhibited: ["note", "freeTextNarrative"],
    emitsOnlyAfterPersistedChange: true,
  },
  WeightRecorded: {
    eventType: "WeightRecorded",
    eventVersion: 1,
    meaning: "A weight measurement was persisted.",
    sourceModule: "observations",
    primaryEntity: "WeightRecord",
    requiredPayloadFields: ["residentId", "weightValue", "unit", "observedAt"],
    sensitiveFieldsProhibited: ["note", "freeTextNarrative"],
    emitsOnlyAfterPersistedChange: true,
  },
  AssessmentCompleted: {
    eventType: "AssessmentCompleted",
    eventVersion: 1,
    meaning: "An assessment changed into a clinically completed state.",
    sourceModule: "assessments",
    primaryEntity: "Assessment",
    requiredPayloadFields: ["assessmentId", "residentId", "assessmentType", "completedAt"],
    sensitiveFieldsProhibited: ["fullAssessmentAnswers", "freeTextNarrative"],
    emitsOnlyAfterPersistedChange: true,
  },
  AssessmentRiskChanged: {
    eventType: "AssessmentRiskChanged",
    eventVersion: 1,
    meaning: "A completed or reassessed assessment resulted in a meaningful risk-level change.",
    sourceModule: "assessments",
    primaryEntity: "Assessment",
    requiredPayloadFields: ["assessmentId", "residentId", "assessmentType", "currentRiskLevel"],
    sensitiveFieldsProhibited: ["fullAssessmentAnswers", "freeTextNarrative"],
    emitsOnlyAfterPersistedChange: true,
  },
  AssessmentCorrected: {
    eventType: "AssessmentCorrected",
    eventVersion: 1,
    meaning: "A persisted assessment was corrected with a reason.",
    sourceModule: "assessments",
    primaryEntity: "Assessment",
    requiredPayloadFields: ["assessmentId", "residentId", "assessmentType", "correctedAt", "correctionReason"],
    sensitiveFieldsProhibited: ["fullAssessmentAnswers", "freeTextNarrative"],
    emitsOnlyAfterPersistedChange: true,
  },
  AssessmentVoided: {
    eventType: "AssessmentVoided",
    eventVersion: 1,
    meaning: "A persisted assessment was voided with a reason.",
    sourceModule: "assessments",
    primaryEntity: "Assessment",
    requiredPayloadFields: ["assessmentId", "residentId", "assessmentType", "voidedAt", "voidReason"],
    sensitiveFieldsProhibited: ["fullAssessmentAnswers", "freeTextNarrative"],
    emitsOnlyAfterPersistedChange: true,
  },
  AssessmentGuidanceRecalculationRequested: {
    eventType: "AssessmentGuidanceRecalculationRequested",
    eventVersion: 1,
    meaning: "A bounded assessment care-guidance recalculation was requested.",
    sourceModule: "rules",
    primaryEntity: "Assessment",
    requiredPayloadFields: ["assessmentId", "residentId", "requestedAt", "reasonCode"],
    sensitiveFieldsProhibited: ["fullAssessmentAnswers", "freeTextNarrative"],
    emitsOnlyAfterPersistedChange: true,
  },
  CarePlanCreated: {
    eventType: "CarePlanCreated",
    eventVersion: 1,
    meaning: "A new nursing care-plan item was created under the resident unified care plan.",
    sourceModule: "care_plans",
    primaryEntity: "CarePlanProblem",
    requiredPayloadFields: ["carePlanId", "carePlanItemId", "residentId"],
    sensitiveFieldsProhibited: ["problemStatement", "notes", "freeTextNarrative"],
    emitsOnlyAfterPersistedChange: true,
  },
  CarePlanReviewed: {
    eventType: "CarePlanReviewed",
    eventVersion: 1,
    meaning: "A formal review was persisted for one nursing care-plan item.",
    sourceModule: "care_plans",
    primaryEntity: "ProblemEvaluation",
    requiredPayloadFields: ["reviewId", "carePlanId", "carePlanItemId", "residentId", "outcome"],
    sensitiveFieldsProhibited: ["summary", "freeTextNarrative"],
    emitsOnlyAfterPersistedChange: true,
  },
  RltDependencyRecorded: {
    eventType: "RltDependencyRecorded",
    eventVersion: 1,
    meaning: "A current resident dependency level was recorded for one RLT domain.",
    sourceModule: "rlt_dependency",
    primaryEntity: "ResidentRltDependency",
    requiredPayloadFields: ["dependencyRecordId", "residentId", "nursingHomeId", "rltDomainId", "currentLevel", "effectiveAt", "recordedAt", "actorUserAccountId", "reasonCode"],
    sensitiveFieldsProhibited: ["rationale", "fullEvidenceNarrative", "freeTextNarrative"],
    emitsOnlyAfterPersistedChange: true,
  },
  RltDependencyChanged: {
    eventType: "RltDependencyChanged",
    eventVersion: 1,
    meaning: "A resident dependency level changed for one RLT domain.",
    sourceModule: "rlt_dependency",
    primaryEntity: "ResidentRltDependency",
    requiredPayloadFields: ["dependencyRecordId", "residentId", "nursingHomeId", "rltDomainId", "previousLevel", "currentLevel", "effectiveAt", "recordedAt", "actorUserAccountId", "reasonCode"],
    sensitiveFieldsProhibited: ["rationale", "fullEvidenceNarrative", "freeTextNarrative"],
    emitsOnlyAfterPersistedChange: true,
  },
  RltDependencyReviewed: {
    eventType: "RltDependencyReviewed",
    eventVersion: 1,
    meaning: "A formal review confirmed the current dependency level for one RLT domain.",
    sourceModule: "rlt_dependency",
    primaryEntity: "ResidentRltDependencyReview",
    requiredPayloadFields: ["dependencyRecordId", "residentId", "nursingHomeId", "rltDomainId", "currentLevel", "effectiveAt", "recordedAt", "actorUserAccountId", "reasonCode"],
    sensitiveFieldsProhibited: ["rationale", "fullEvidenceNarrative", "freeTextNarrative"],
    emitsOnlyAfterPersistedChange: true,
  },
  RltDependencyCorrected: {
    eventType: "RltDependencyCorrected",
    eventVersion: 1,
    meaning: "A dependency record was corrected without altering its historical predecessor.",
    sourceModule: "rlt_dependency",
    primaryEntity: "ResidentRltDependency",
    requiredPayloadFields: ["dependencyRecordId", "residentId", "nursingHomeId", "rltDomainId", "previousLevel", "currentLevel", "effectiveAt", "recordedAt", "actorUserAccountId", "reasonCode"],
    sensitiveFieldsProhibited: ["rationale", "fullEvidenceNarrative", "freeTextNarrative"],
    emitsOnlyAfterPersistedChange: true,
  },
  ResidentStrengthRecorded: strengthPreferenceEventEntry("ResidentStrengthRecorded", "A resident strength was recorded."),
  ResidentStrengthChanged: strengthPreferenceEventEntry("ResidentStrengthChanged", "A resident strength gained a new version."),
  ResidentStrengthReviewed: strengthPreferenceEventEntry("ResidentStrengthReviewed", "A resident strength was formally reviewed."),
  ResidentStrengthSuperseded: strengthPreferenceEventEntry("ResidentStrengthSuperseded", "A resident strength was superseded."),
  ResidentPreferenceRecorded: strengthPreferenceEventEntry("ResidentPreferenceRecorded", "A resident preference was recorded."),
  ResidentPreferenceChanged: strengthPreferenceEventEntry("ResidentPreferenceChanged", "A resident preference gained a new version."),
  ResidentPreferenceReviewed: strengthPreferenceEventEntry("ResidentPreferenceReviewed", "A resident preference was formally reviewed."),
  ResidentPreferenceSuperseded: strengthPreferenceEventEntry("ResidentPreferenceSuperseded", "A resident preference was superseded."),
  ResidentPreferenceAccommodationChanged: strengthPreferenceEventEntry("ResidentPreferenceAccommodationChanged", "Preference accommodation was reviewed."),
  ResidentPreferenceSafetyReviewRequested: strengthPreferenceEventEntry("ResidentPreferenceSafetyReviewRequested", "A preference safety review was requested."),
  ResidentPreferenceSafetyReviewResolved: strengthPreferenceEventEntry("ResidentPreferenceSafetyReviewResolved", "A preference safety review was resolved."),
  ResidentPreferenceConflictRaised: strengthPreferenceEventEntry("ResidentPreferenceConflictRaised", "A preference conflict was raised."),
  ResidentPreferenceConflictResolved: strengthPreferenceEventEntry("ResidentPreferenceConflictResolved", "A preference conflict was resolved."),
  CareActionCompleted: {
    eventType: "CareActionCompleted",
    eventVersion: 1,
    meaning: "A scheduled or one-off care action was completed.",
    sourceModule: "care_actions",
    primaryEntity: "ProblemInterventionLog",
    requiredPayloadFields: ["careActionId", "residentId", "effectiveCompletedAt", "recordedAt", "outcome"],
    sensitiveFieldsProhibited: ["comments", "freeTextNarrative"],
    emitsOnlyAfterPersistedChange: true,
  },
  CareActionMissed: {
    eventType: "CareActionMissed",
    eventVersion: 1,
    meaning: "A care-action occurrence was explicitly or validly classified as missed.",
    sourceModule: "care_actions",
    primaryEntity: "ProblemInterventionLog",
    requiredPayloadFields: ["careActionId", "occurrenceId", "residentId", "dueAt", "missedAt", "missedReason"],
    sensitiveFieldsProhibited: ["comments", "freeTextNarrative"],
    emitsOnlyAfterPersistedChange: true,
  },
  MedicationRefused: {
    eventType: "MedicationRefused",
    eventVersion: 1,
    meaning: "A resident refused a scheduled medication dose.",
    sourceModule: "medication_integration",
    primaryEntity: "MedicationRecord",
    requiredPayloadFields: ["residentId", "medicationReferenceId", "scheduledDoseOccurrenceId", "refusedAt", "medicationNameOrCode"],
    sensitiveFieldsProhibited: ["fullMedicationAdministrationRecord", "freeTextNarrative"],
    emitsOnlyAfterPersistedChange: true,
  },
  IncidentRecorded: {
    eventType: "IncidentRecorded",
    eventVersion: 1,
    meaning: "An incident was initially persisted.",
    sourceModule: "incidents",
    primaryEntity: "Incident",
    requiredPayloadFields: ["incidentId", "incidentType", "occurredAt", "nursingHomeId"],
    sensitiveFieldsProhibited: ["description", "immediateAction", "freeTextNarrative"],
    emitsOnlyAfterPersistedChange: true,
  },
  HandoverCreated: {
    eventType: "HandoverCreated",
    eventVersion: 1,
    meaning: "A resident or ward handover was activated.",
    sourceModule: "handovers",
    primaryEntity: "HandoverNote",
    requiredPayloadFields: ["handoverId", "wardId", "scope", "category", "priority", "sourceShiftId", "targetShiftId", "effectiveFrom"],
    sensitiveFieldsProhibited: ["summary", "outstandingActions", "note", "freeTextNarrative"],
    emitsOnlyAfterPersistedChange: true,
  },
  DailyCareRecorded: {
    eventType: "DailyCareRecorded",
    eventVersion: 1,
    meaning: "A structured daily-care record was persisted.",
    sourceModule: "daily_care",
    primaryEntity: "DailyCareRecord",
    requiredPayloadFields: ["dailyCareRecordId", "residentId", "careType", "status", "occurredAt", "recordedAt"],
    sensitiveFieldsProhibited: ["observation", "freeTextNarrative"],
    emitsOnlyAfterPersistedChange: true,
  },
  DailyCareOutcomeRecorded: {
    eventType: "DailyCareOutcomeRecorded",
    eventVersion: 1,
    meaning: "A structured Daily Care outcome was recorded.",
    sourceModule: "daily_care",
    primaryEntity: "DailyCareRecord",
    requiredPayloadFields: ["dailyCareRecordId", "residentId", "careType", "outcome", "occurredAt", "recordedAt"],
    sensitiveFieldsProhibited: ["notes", "residentResponse", "freeTextNarrative"],
    emitsOnlyAfterPersistedChange: true,
  },
  DailyCarePartiallyCompleted: {
    eventType: "DailyCarePartiallyCompleted",
    eventVersion: 1,
    meaning: "A structured daily-care record was partially completed.",
    sourceModule: "daily_care",
    primaryEntity: "DailyCareRecord",
    requiredPayloadFields: ["dailyCareRecordId", "residentId", "careType", "outcome", "occurredAt", "recordedAt"],
    sensitiveFieldsProhibited: ["notes", "freeTextNarrative"],
    emitsOnlyAfterPersistedChange: true,
  },
  DailyCareRefused: {
    eventType: "DailyCareRefused",
    eventVersion: 1,
    meaning: "A resident refused a daily-care activity using the structured refusal workflow.",
    sourceModule: "daily_care",
    primaryEntity: "DailyCareRecord",
    requiredPayloadFields: ["dailyCareRecordId", "residentId", "careType", "outcome", "occurredAt", "recordedAt"],
    sensitiveFieldsProhibited: ["notes", "freeTextNarrative"],
    emitsOnlyAfterPersistedChange: true,
  },
  DailyCareUnable: {
    eventType: "DailyCareUnable",
    eventVersion: 1,
    meaning: "A daily-care activity could not be completed.",
    sourceModule: "daily_care",
    primaryEntity: "DailyCareRecord",
    requiredPayloadFields: ["dailyCareRecordId", "residentId", "careType", "outcome", "occurredAt", "recordedAt"],
    sensitiveFieldsProhibited: ["notes", "freeTextNarrative"],
    emitsOnlyAfterPersistedChange: true,
  },
  DailyCareNotRequired: {
    eventType: "DailyCareNotRequired",
    eventVersion: 1,
    meaning: "A daily-care activity was reviewed and recorded as not required.",
    sourceModule: "daily_care",
    primaryEntity: "DailyCareRecord",
    requiredPayloadFields: ["dailyCareRecordId", "residentId", "careType", "outcome", "occurredAt", "recordedAt"],
    sensitiveFieldsProhibited: ["notes", "freeTextNarrative"],
    emitsOnlyAfterPersistedChange: true,
  },
  DailyCareEscalated: {
    eventType: "DailyCareEscalated",
    eventVersion: 1,
    meaning: "A Daily Care outcome was escalated for clinical follow-up.",
    sourceModule: "daily_care",
    primaryEntity: "DailyCareRecord",
    requiredPayloadFields: ["dailyCareRecordId", "residentId", "careType", "outcome", "occurredAt", "recordedAt"],
    sensitiveFieldsProhibited: ["notes", "freeTextNarrative"],
    emitsOnlyAfterPersistedChange: true,
  },
  DailyCareNurseInformed: {
    eventType: "DailyCareNurseInformed",
    eventVersion: 1,
    meaning: "A nurse notification was recorded for Daily Care.",
    sourceModule: "daily_care",
    primaryEntity: "DailyCareRecord",
    requiredPayloadFields: ["dailyCareRecordId", "residentId", "careType", "outcome", "occurredAt", "recordedAt"],
    sensitiveFieldsProhibited: ["notes", "freeTextNarrative"],
    emitsOnlyAfterPersistedChange: true,
  },
  DailyCareFollowUpRequested: {
    eventType: "DailyCareFollowUpRequested",
    eventVersion: 1,
    meaning: "Daily Care was recorded with explicit follow-up required.",
    sourceModule: "daily_care",
    primaryEntity: "DailyCareRecord",
    requiredPayloadFields: ["dailyCareRecordId", "residentId", "careType", "status", "occurredAt", "recordedAt"],
    sensitiveFieldsProhibited: ["notes", "freeTextNarrative"],
    emitsOnlyAfterPersistedChange: true,
  },
  DailyCareMappedToRlt: {
    eventType: "DailyCareMappedToRlt",
    eventVersion: 1,
    meaning: "A Daily Care record was deterministically mapped to RLT domains.",
    sourceModule: "daily_care",
    primaryEntity: "DailyCareRecord",
    requiredPayloadFields: ["dailyCareRecordId", "residentId", "rltDomainIds", "correlationId"],
    sensitiveFieldsProhibited: ["notes", "freeTextNarrative"],
    emitsOnlyAfterPersistedChange: true,
  },
  DailyCareRltMappingChanged: {
    eventType: "DailyCareRltMappingChanged",
    eventVersion: 1,
    meaning: "A Daily Care RLT mapping changed through correction or controlled remapping.",
    sourceModule: "daily_care",
    primaryEntity: "DailyCareRecord",
    requiredPayloadFields: ["dailyCareRecordId", "residentId", "rltDomainIds", "correlationId"],
    sensitiveFieldsProhibited: ["notes", "freeTextNarrative"],
    emitsOnlyAfterPersistedChange: true,
  },
  DailyCareEnteredInError: {
    eventType: "DailyCareEnteredInError",
    eventVersion: 1,
    meaning: "A Daily Care record was marked entered in error.",
    sourceModule: "daily_care",
    primaryEntity: "DailyCareRecord",
    requiredPayloadFields: ["dailyCareRecordId", "residentId", "careType", "status", "occurredAt", "recordedAt"],
    sensitiveFieldsProhibited: ["notes", "freeTextNarrative"],
    emitsOnlyAfterPersistedChange: true,
  },
  DailyCareCorrected: {
    eventType: "DailyCareCorrected",
    eventVersion: 1,
    meaning: "A Daily Care record was corrected with a replacement record.",
    sourceModule: "daily_care",
    primaryEntity: "DailyCareRecord",
    requiredPayloadFields: ["dailyCareRecordId", "residentId", "careType", "status", "occurredAt", "recordedAt"],
    sensitiveFieldsProhibited: ["notes", "freeTextNarrative"],
    emitsOnlyAfterPersistedChange: true,
  },
};

export const SUPPORTED_EVENT_VERSIONS = Object.fromEntries(
  Object.keys(EVENT_CATALOGUE).map((eventType) => [eventType, [1]]),
) as Record<DomainEventType, number[]>;
