/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VitalsRouteImport } from './routes/vitals'
import { Route as VisitorsRouteImport } from './routes/visitors'
import { Route as TrainingDashboardRouteImport } from './routes/training-dashboard'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as StaffManagementRouteImport } from './routes/staff-management'
import { Route as RisksRouteImport } from './routes/risks'
import { Route as ResidentsRouteImport } from './routes/residents'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as QualityGovernanceRouteImport } from './routes/quality-governance'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OutingsRouteImport } from './routes/outings'
import { Route as OperationsRouteImport } from './routes/operations'
import { Route as MdtNotesRouteImport } from './routes/mdt-notes'
import { Route as MaintenanceHousekeepingRouteImport } from './routes/maintenance-housekeeping'
import { Route as InterventionsRouteImport } from './routes/interventions'
import { Route as IncidentsRouteImport } from './routes/incidents'
import { Route as HandoversRouteImport } from './routes/handovers'
import { Route as DailyNotesRouteImport } from './routes/daily-notes'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as CarePlansRouteImport } from './routes/care-plans'
import { Route as AuditLogsRouteImport } from './routes/audit-logs'
import { Route as AssessmentsRouteImport } from './routes/assessments'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AccountsDashboardRouteImport } from './routes/accounts-dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResidentsIndexRouteImport } from './routes/residents.index'
import { Route as AssessmentsIndexRouteImport } from './routes/assessments.index'
import { Route as WorkforceStaffRouteImport } from './routes/workforce.staff'
import { Route as VitalsAuditRouteImport } from './routes/vitals.audit'
import { Route as ResidentsIdRouteImport } from './routes/residents.$id'
import { Route as ReportsDailyCareRouteImport } from './routes/reports.daily-care'
import { Route as InspectionResidentIdRouteImport } from './routes/inspection.$residentId'
import { Route as ChartsResidentIdRouteImport } from './routes/charts.$residentId'
import { Route as CarePlansIdRouteImport } from './routes/care-plans.$id'
import { Route as AssessmentsReassessmentRouteImport } from './routes/assessments.reassessment'
import { Route as AssessmentsAssessmentIdRouteImport } from './routes/assessments.$assessmentId'
import { Route as WorkforceStaffStaffMemberIdRouteImport } from './routes/workforce.staff.$staffMemberId'
import { Route as ResidentsIdTimelineRouteImport } from './routes/residents.$id.timeline'
import { Route as ResidentsIdRecordRouteImport } from './routes/residents.$id.record'
import { Route as ResidentsIdQualityOfLifeRouteImport } from './routes/residents.$id.quality-of-life'
import { Route as ResidentsIdCarePlanRouteImport } from './routes/residents.$id.care-plan'
import { Route as ResidentsIdAssessmentsRouteImport } from './routes/residents.$id.assessments'
import { Route as AssessmentsNewResidentIdRouteImport } from './routes/assessments.new.$residentId'

const VitalsRoute = VitalsRouteImport.update({
  id: '/vitals',
  path: '/vitals',
  getParentRoute: () => rootRouteImport,
} as any)
const VisitorsRoute = VisitorsRouteImport.update({
  id: '/visitors',
  path: '/visitors',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingDashboardRoute = TrainingDashboardRouteImport.update({
  id: '/training-dashboard',
  path: '/training-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffManagementRoute = StaffManagementRouteImport.update({
  id: '/staff-management',
  path: '/staff-management',
  getParentRoute: () => rootRouteImport,
} as any)
const RisksRoute = RisksRouteImport.update({
  id: '/risks',
  path: '/risks',
  getParentRoute: () => rootRouteImport,
} as any)
const ResidentsRoute = ResidentsRouteImport.update({
  id: '/residents',
  path: '/residents',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const QualityGovernanceRoute = QualityGovernanceRouteImport.update({
  id: '/quality-governance',
  path: '/quality-governance',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OutingsRoute = OutingsRouteImport.update({
  id: '/outings',
  path: '/outings',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsRoute = OperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const MdtNotesRoute = MdtNotesRouteImport.update({
  id: '/mdt-notes',
  path: '/mdt-notes',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceHousekeepingRoute = MaintenanceHousekeepingRouteImport.update({
  id: '/maintenance-housekeeping',
  path: '/maintenance-housekeeping',
  getParentRoute: () => rootRouteImport,
} as any)
const InterventionsRoute = InterventionsRouteImport.update({
  id: '/interventions',
  path: '/interventions',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsRoute = IncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => rootRouteImport,
} as any)
const HandoversRoute = HandoversRouteImport.update({
  id: '/handovers',
  path: '/handovers',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyNotesRoute = DailyNotesRouteImport.update({
  id: '/daily-notes',
  path: '/daily-notes',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const CarePlansRoute = CarePlansRouteImport.update({
  id: '/care-plans',
  path: '/care-plans',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogsRoute = AuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentsRoute = AssessmentsRouteImport.update({
  id: '/assessments',
  path: '/assessments',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsDashboardRoute = AccountsDashboardRouteImport.update({
  id: '/accounts-dashboard',
  path: '/accounts-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResidentsIndexRoute = ResidentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ResidentsRoute,
} as any)
const AssessmentsIndexRoute = AssessmentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AssessmentsRoute,
} as any)
const WorkforceStaffRoute = WorkforceStaffRouteImport.update({
  id: '/workforce/staff',
  path: '/workforce/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const VitalsAuditRoute = VitalsAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => VitalsRoute,
} as any)
const ResidentsIdRoute = ResidentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ResidentsRoute,
} as any)
const ReportsDailyCareRoute = ReportsDailyCareRouteImport.update({
  id: '/daily-care',
  path: '/daily-care',
  getParentRoute: () => ReportsRoute,
} as any)
const InspectionResidentIdRoute = InspectionResidentIdRouteImport.update({
  id: '/inspection/$residentId',
  path: '/inspection/$residentId',
  getParentRoute: () => rootRouteImport,
} as any)
const ChartsResidentIdRoute = ChartsResidentIdRouteImport.update({
  id: '/charts/$residentId',
  path: '/charts/$residentId',
  getParentRoute: () => rootRouteImport,
} as any)
const CarePlansIdRoute = CarePlansIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CarePlansRoute,
} as any)
const AssessmentsReassessmentRoute = AssessmentsReassessmentRouteImport.update({
  id: '/reassessment',
  path: '/reassessment',
  getParentRoute: () => AssessmentsRoute,
} as any)
const AssessmentsAssessmentIdRoute = AssessmentsAssessmentIdRouteImport.update({
  id: '/$assessmentId',
  path: '/$assessmentId',
  getParentRoute: () => AssessmentsRoute,
} as any)
const WorkforceStaffStaffMemberIdRoute =
  WorkforceStaffStaffMemberIdRouteImport.update({
    id: '/$staffMemberId',
    path: '/$staffMemberId',
    getParentRoute: () => WorkforceStaffRoute,
  } as any)
const ResidentsIdTimelineRoute = ResidentsIdTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => ResidentsIdRoute,
} as any)
const ResidentsIdRecordRoute = ResidentsIdRecordRouteImport.update({
  id: '/record',
  path: '/record',
  getParentRoute: () => ResidentsIdRoute,
} as any)
const ResidentsIdQualityOfLifeRoute =
  ResidentsIdQualityOfLifeRouteImport.update({
    id: '/quality-of-life',
    path: '/quality-of-life',
    getParentRoute: () => ResidentsIdRoute,
  } as any)
const ResidentsIdCarePlanRoute = ResidentsIdCarePlanRouteImport.update({
  id: '/care-plan',
  path: '/care-plan',
  getParentRoute: () => ResidentsIdRoute,
} as any)
const ResidentsIdAssessmentsRoute = ResidentsIdAssessmentsRouteImport.update({
  id: '/assessments',
  path: '/assessments',
  getParentRoute: () => ResidentsIdRoute,
} as any)
const AssessmentsNewResidentIdRoute =
  AssessmentsNewResidentIdRouteImport.update({
    id: '/new/$residentId',
    path: '/new/$residentId',
    getParentRoute: () => AssessmentsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts-dashboard': typeof AccountsDashboardRoute
  '/alerts': typeof AlertsRoute
  '/assessments': typeof AssessmentsRouteWithChildren
  '/audit-logs': typeof AuditLogsRoute
  '/care-plans': typeof CarePlansRouteWithChildren
  '/compliance': typeof ComplianceRoute
  '/daily-notes': typeof DailyNotesRoute
  '/handovers': typeof HandoversRoute
  '/incidents': typeof IncidentsRoute
  '/interventions': typeof InterventionsRoute
  '/maintenance-housekeeping': typeof MaintenanceHousekeepingRoute
  '/mdt-notes': typeof MdtNotesRoute
  '/operations': typeof OperationsRoute
  '/outings': typeof OutingsRoute
  '/profile': typeof ProfileRoute
  '/quality-governance': typeof QualityGovernanceRoute
  '/reports': typeof ReportsRouteWithChildren
  '/residents': typeof ResidentsRouteWithChildren
  '/risks': typeof RisksRoute
  '/staff-management': typeof StaffManagementRoute
  '/tasks': typeof TasksRoute
  '/training-dashboard': typeof TrainingDashboardRoute
  '/visitors': typeof VisitorsRoute
  '/vitals': typeof VitalsRouteWithChildren
  '/assessments/$assessmentId': typeof AssessmentsAssessmentIdRoute
  '/assessments/reassessment': typeof AssessmentsReassessmentRoute
  '/care-plans/$id': typeof CarePlansIdRoute
  '/charts/$residentId': typeof ChartsResidentIdRoute
  '/inspection/$residentId': typeof InspectionResidentIdRoute
  '/reports/daily-care': typeof ReportsDailyCareRoute
  '/residents/$id': typeof ResidentsIdRouteWithChildren
  '/vitals/audit': typeof VitalsAuditRoute
  '/workforce/staff': typeof WorkforceStaffRouteWithChildren
  '/assessments/': typeof AssessmentsIndexRoute
  '/residents/': typeof ResidentsIndexRoute
  '/assessments/new/$residentId': typeof AssessmentsNewResidentIdRoute
  '/residents/$id/assessments': typeof ResidentsIdAssessmentsRoute
  '/residents/$id/care-plan': typeof ResidentsIdCarePlanRoute
  '/residents/$id/quality-of-life': typeof ResidentsIdQualityOfLifeRoute
  '/residents/$id/record': typeof ResidentsIdRecordRoute
  '/residents/$id/timeline': typeof ResidentsIdTimelineRoute
  '/workforce/staff/$staffMemberId': typeof WorkforceStaffStaffMemberIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts-dashboard': typeof AccountsDashboardRoute
  '/alerts': typeof AlertsRoute
  '/audit-logs': typeof AuditLogsRoute
  '/care-plans': typeof CarePlansRouteWithChildren
  '/compliance': typeof ComplianceRoute
  '/daily-notes': typeof DailyNotesRoute
  '/handovers': typeof HandoversRoute
  '/incidents': typeof IncidentsRoute
  '/interventions': typeof InterventionsRoute
  '/maintenance-housekeeping': typeof MaintenanceHousekeepingRoute
  '/mdt-notes': typeof MdtNotesRoute
  '/operations': typeof OperationsRoute
  '/outings': typeof OutingsRoute
  '/profile': typeof ProfileRoute
  '/quality-governance': typeof QualityGovernanceRoute
  '/reports': typeof ReportsRouteWithChildren
  '/risks': typeof RisksRoute
  '/staff-management': typeof StaffManagementRoute
  '/tasks': typeof TasksRoute
  '/training-dashboard': typeof TrainingDashboardRoute
  '/visitors': typeof VisitorsRoute
  '/vitals': typeof VitalsRouteWithChildren
  '/assessments/$assessmentId': typeof AssessmentsAssessmentIdRoute
  '/assessments/reassessment': typeof AssessmentsReassessmentRoute
  '/care-plans/$id': typeof CarePlansIdRoute
  '/charts/$residentId': typeof ChartsResidentIdRoute
  '/inspection/$residentId': typeof InspectionResidentIdRoute
  '/reports/daily-care': typeof ReportsDailyCareRoute
  '/residents/$id': typeof ResidentsIdRouteWithChildren
  '/vitals/audit': typeof VitalsAuditRoute
  '/workforce/staff': typeof WorkforceStaffRouteWithChildren
  '/assessments': typeof AssessmentsIndexRoute
  '/residents': typeof ResidentsIndexRoute
  '/assessments/new/$residentId': typeof AssessmentsNewResidentIdRoute
  '/residents/$id/assessments': typeof ResidentsIdAssessmentsRoute
  '/residents/$id/care-plan': typeof ResidentsIdCarePlanRoute
  '/residents/$id/quality-of-life': typeof ResidentsIdQualityOfLifeRoute
  '/residents/$id/record': typeof ResidentsIdRecordRoute
  '/residents/$id/timeline': typeof ResidentsIdTimelineRoute
  '/workforce/staff/$staffMemberId': typeof WorkforceStaffStaffMemberIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts-dashboard': typeof AccountsDashboardRoute
  '/alerts': typeof AlertsRoute
  '/assessments': typeof AssessmentsRouteWithChildren
  '/audit-logs': typeof AuditLogsRoute
  '/care-plans': typeof CarePlansRouteWithChildren
  '/compliance': typeof ComplianceRoute
  '/daily-notes': typeof DailyNotesRoute
  '/handovers': typeof HandoversRoute
  '/incidents': typeof IncidentsRoute
  '/interventions': typeof InterventionsRoute
  '/maintenance-housekeeping': typeof MaintenanceHousekeepingRoute
  '/mdt-notes': typeof MdtNotesRoute
  '/operations': typeof OperationsRoute
  '/outings': typeof OutingsRoute
  '/profile': typeof ProfileRoute
  '/quality-governance': typeof QualityGovernanceRoute
  '/reports': typeof ReportsRouteWithChildren
  '/residents': typeof ResidentsRouteWithChildren
  '/risks': typeof RisksRoute
  '/staff-management': typeof StaffManagementRoute
  '/tasks': typeof TasksRoute
  '/training-dashboard': typeof TrainingDashboardRoute
  '/visitors': typeof VisitorsRoute
  '/vitals': typeof VitalsRouteWithChildren
  '/assessments/$assessmentId': typeof AssessmentsAssessmentIdRoute
  '/assessments/reassessment': typeof AssessmentsReassessmentRoute
  '/care-plans/$id': typeof CarePlansIdRoute
  '/charts/$residentId': typeof ChartsResidentIdRoute
  '/inspection/$residentId': typeof InspectionResidentIdRoute
  '/reports/daily-care': typeof ReportsDailyCareRoute
  '/residents/$id': typeof ResidentsIdRouteWithChildren
  '/vitals/audit': typeof VitalsAuditRoute
  '/workforce/staff': typeof WorkforceStaffRouteWithChildren
  '/assessments/': typeof AssessmentsIndexRoute
  '/residents/': typeof ResidentsIndexRoute
  '/assessments/new/$residentId': typeof AssessmentsNewResidentIdRoute
  '/residents/$id/assessments': typeof ResidentsIdAssessmentsRoute
  '/residents/$id/care-plan': typeof ResidentsIdCarePlanRoute
  '/residents/$id/quality-of-life': typeof ResidentsIdQualityOfLifeRoute
  '/residents/$id/record': typeof ResidentsIdRecordRoute
  '/residents/$id/timeline': typeof ResidentsIdTimelineRoute
  '/workforce/staff/$staffMemberId': typeof WorkforceStaffStaffMemberIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts-dashboard'
    | '/alerts'
    | '/assessments'
    | '/audit-logs'
    | '/care-plans'
    | '/compliance'
    | '/daily-notes'
    | '/handovers'
    | '/incidents'
    | '/interventions'
    | '/maintenance-housekeeping'
    | '/mdt-notes'
    | '/operations'
    | '/outings'
    | '/profile'
    | '/quality-governance'
    | '/reports'
    | '/residents'
    | '/risks'
    | '/staff-management'
    | '/tasks'
    | '/training-dashboard'
    | '/visitors'
    | '/vitals'
    | '/assessments/$assessmentId'
    | '/assessments/reassessment'
    | '/care-plans/$id'
    | '/charts/$residentId'
    | '/inspection/$residentId'
    | '/reports/daily-care'
    | '/residents/$id'
    | '/vitals/audit'
    | '/workforce/staff'
    | '/assessments/'
    | '/residents/'
    | '/assessments/new/$residentId'
    | '/residents/$id/assessments'
    | '/residents/$id/care-plan'
    | '/residents/$id/quality-of-life'
    | '/residents/$id/record'
    | '/residents/$id/timeline'
    | '/workforce/staff/$staffMemberId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts-dashboard'
    | '/alerts'
    | '/audit-logs'
    | '/care-plans'
    | '/compliance'
    | '/daily-notes'
    | '/handovers'
    | '/incidents'
    | '/interventions'
    | '/maintenance-housekeeping'
    | '/mdt-notes'
    | '/operations'
    | '/outings'
    | '/profile'
    | '/quality-governance'
    | '/reports'
    | '/risks'
    | '/staff-management'
    | '/tasks'
    | '/training-dashboard'
    | '/visitors'
    | '/vitals'
    | '/assessments/$assessmentId'
    | '/assessments/reassessment'
    | '/care-plans/$id'
    | '/charts/$residentId'
    | '/inspection/$residentId'
    | '/reports/daily-care'
    | '/residents/$id'
    | '/vitals/audit'
    | '/workforce/staff'
    | '/assessments'
    | '/residents'
    | '/assessments/new/$residentId'
    | '/residents/$id/assessments'
    | '/residents/$id/care-plan'
    | '/residents/$id/quality-of-life'
    | '/residents/$id/record'
    | '/residents/$id/timeline'
    | '/workforce/staff/$staffMemberId'
  id:
    | '__root__'
    | '/'
    | '/accounts-dashboard'
    | '/alerts'
    | '/assessments'
    | '/audit-logs'
    | '/care-plans'
    | '/compliance'
    | '/daily-notes'
    | '/handovers'
    | '/incidents'
    | '/interventions'
    | '/maintenance-housekeeping'
    | '/mdt-notes'
    | '/operations'
    | '/outings'
    | '/profile'
    | '/quality-governance'
    | '/reports'
    | '/residents'
    | '/risks'
    | '/staff-management'
    | '/tasks'
    | '/training-dashboard'
    | '/visitors'
    | '/vitals'
    | '/assessments/$assessmentId'
    | '/assessments/reassessment'
    | '/care-plans/$id'
    | '/charts/$residentId'
    | '/inspection/$residentId'
    | '/reports/daily-care'
    | '/residents/$id'
    | '/vitals/audit'
    | '/workforce/staff'
    | '/assessments/'
    | '/residents/'
    | '/assessments/new/$residentId'
    | '/residents/$id/assessments'
    | '/residents/$id/care-plan'
    | '/residents/$id/quality-of-life'
    | '/residents/$id/record'
    | '/residents/$id/timeline'
    | '/workforce/staff/$staffMemberId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsDashboardRoute: typeof AccountsDashboardRoute
  AlertsRoute: typeof AlertsRoute
  AssessmentsRoute: typeof AssessmentsRouteWithChildren
  AuditLogsRoute: typeof AuditLogsRoute
  CarePlansRoute: typeof CarePlansRouteWithChildren
  ComplianceRoute: typeof ComplianceRoute
  DailyNotesRoute: typeof DailyNotesRoute
  HandoversRoute: typeof HandoversRoute
  IncidentsRoute: typeof IncidentsRoute
  InterventionsRoute: typeof InterventionsRoute
  MaintenanceHousekeepingRoute: typeof MaintenanceHousekeepingRoute
  MdtNotesRoute: typeof MdtNotesRoute
  OperationsRoute: typeof OperationsRoute
  OutingsRoute: typeof OutingsRoute
  ProfileRoute: typeof ProfileRoute
  QualityGovernanceRoute: typeof QualityGovernanceRoute
  ReportsRoute: typeof ReportsRouteWithChildren
  ResidentsRoute: typeof ResidentsRouteWithChildren
  RisksRoute: typeof RisksRoute
  StaffManagementRoute: typeof StaffManagementRoute
  TasksRoute: typeof TasksRoute
  TrainingDashboardRoute: typeof TrainingDashboardRoute
  VisitorsRoute: typeof VisitorsRoute
  VitalsRoute: typeof VitalsRouteWithChildren
  ChartsResidentIdRoute: typeof ChartsResidentIdRoute
  InspectionResidentIdRoute: typeof InspectionResidentIdRoute
  WorkforceStaffRoute: typeof WorkforceStaffRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vitals': {
      id: '/vitals'
      path: '/vitals'
      fullPath: '/vitals'
      preLoaderRoute: typeof VitalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visitors': {
      id: '/visitors'
      path: '/visitors'
      fullPath: '/visitors'
      preLoaderRoute: typeof VisitorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training-dashboard': {
      id: '/training-dashboard'
      path: '/training-dashboard'
      fullPath: '/training-dashboard'
      preLoaderRoute: typeof TrainingDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff-management': {
      id: '/staff-management'
      path: '/staff-management'
      fullPath: '/staff-management'
      preLoaderRoute: typeof StaffManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risks': {
      id: '/risks'
      path: '/risks'
      fullPath: '/risks'
      preLoaderRoute: typeof RisksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/residents': {
      id: '/residents'
      path: '/residents'
      fullPath: '/residents'
      preLoaderRoute: typeof ResidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quality-governance': {
      id: '/quality-governance'
      path: '/quality-governance'
      fullPath: '/quality-governance'
      preLoaderRoute: typeof QualityGovernanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outings': {
      id: '/outings'
      path: '/outings'
      fullPath: '/outings'
      preLoaderRoute: typeof OutingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations': {
      id: '/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof OperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mdt-notes': {
      id: '/mdt-notes'
      path: '/mdt-notes'
      fullPath: '/mdt-notes'
      preLoaderRoute: typeof MdtNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance-housekeeping': {
      id: '/maintenance-housekeeping'
      path: '/maintenance-housekeeping'
      fullPath: '/maintenance-housekeeping'
      preLoaderRoute: typeof MaintenanceHousekeepingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interventions': {
      id: '/interventions'
      path: '/interventions'
      fullPath: '/interventions'
      preLoaderRoute: typeof InterventionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents': {
      id: '/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof IncidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handovers': {
      id: '/handovers'
      path: '/handovers'
      fullPath: '/handovers'
      preLoaderRoute: typeof HandoversRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily-notes': {
      id: '/daily-notes'
      path: '/daily-notes'
      fullPath: '/daily-notes'
      preLoaderRoute: typeof DailyNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/care-plans': {
      id: '/care-plans'
      path: '/care-plans'
      fullPath: '/care-plans'
      preLoaderRoute: typeof CarePlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-logs': {
      id: '/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessments': {
      id: '/assessments'
      path: '/assessments'
      fullPath: '/assessments'
      preLoaderRoute: typeof AssessmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts-dashboard': {
      id: '/accounts-dashboard'
      path: '/accounts-dashboard'
      fullPath: '/accounts-dashboard'
      preLoaderRoute: typeof AccountsDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/residents/': {
      id: '/residents/'
      path: '/'
      fullPath: '/residents/'
      preLoaderRoute: typeof ResidentsIndexRouteImport
      parentRoute: typeof ResidentsRoute
    }
    '/assessments/': {
      id: '/assessments/'
      path: '/'
      fullPath: '/assessments/'
      preLoaderRoute: typeof AssessmentsIndexRouteImport
      parentRoute: typeof AssessmentsRoute
    }
    '/workforce/staff': {
      id: '/workforce/staff'
      path: '/workforce/staff'
      fullPath: '/workforce/staff'
      preLoaderRoute: typeof WorkforceStaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vitals/audit': {
      id: '/vitals/audit'
      path: '/audit'
      fullPath: '/vitals/audit'
      preLoaderRoute: typeof VitalsAuditRouteImport
      parentRoute: typeof VitalsRoute
    }
    '/residents/$id': {
      id: '/residents/$id'
      path: '/$id'
      fullPath: '/residents/$id'
      preLoaderRoute: typeof ResidentsIdRouteImport
      parentRoute: typeof ResidentsRoute
    }
    '/reports/daily-care': {
      id: '/reports/daily-care'
      path: '/daily-care'
      fullPath: '/reports/daily-care'
      preLoaderRoute: typeof ReportsDailyCareRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/inspection/$residentId': {
      id: '/inspection/$residentId'
      path: '/inspection/$residentId'
      fullPath: '/inspection/$residentId'
      preLoaderRoute: typeof InspectionResidentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charts/$residentId': {
      id: '/charts/$residentId'
      path: '/charts/$residentId'
      fullPath: '/charts/$residentId'
      preLoaderRoute: typeof ChartsResidentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/care-plans/$id': {
      id: '/care-plans/$id'
      path: '/$id'
      fullPath: '/care-plans/$id'
      preLoaderRoute: typeof CarePlansIdRouteImport
      parentRoute: typeof CarePlansRoute
    }
    '/assessments/reassessment': {
      id: '/assessments/reassessment'
      path: '/reassessment'
      fullPath: '/assessments/reassessment'
      preLoaderRoute: typeof AssessmentsReassessmentRouteImport
      parentRoute: typeof AssessmentsRoute
    }
    '/assessments/$assessmentId': {
      id: '/assessments/$assessmentId'
      path: '/$assessmentId'
      fullPath: '/assessments/$assessmentId'
      preLoaderRoute: typeof AssessmentsAssessmentIdRouteImport
      parentRoute: typeof AssessmentsRoute
    }
    '/workforce/staff/$staffMemberId': {
      id: '/workforce/staff/$staffMemberId'
      path: '/$staffMemberId'
      fullPath: '/workforce/staff/$staffMemberId'
      preLoaderRoute: typeof WorkforceStaffStaffMemberIdRouteImport
      parentRoute: typeof WorkforceStaffRoute
    }
    '/residents/$id/timeline': {
      id: '/residents/$id/timeline'
      path: '/timeline'
      fullPath: '/residents/$id/timeline'
      preLoaderRoute: typeof ResidentsIdTimelineRouteImport
      parentRoute: typeof ResidentsIdRoute
    }
    '/residents/$id/record': {
      id: '/residents/$id/record'
      path: '/record'
      fullPath: '/residents/$id/record'
      preLoaderRoute: typeof ResidentsIdRecordRouteImport
      parentRoute: typeof ResidentsIdRoute
    }
    '/residents/$id/quality-of-life': {
      id: '/residents/$id/quality-of-life'
      path: '/quality-of-life'
      fullPath: '/residents/$id/quality-of-life'
      preLoaderRoute: typeof ResidentsIdQualityOfLifeRouteImport
      parentRoute: typeof ResidentsIdRoute
    }
    '/residents/$id/care-plan': {
      id: '/residents/$id/care-plan'
      path: '/care-plan'
      fullPath: '/residents/$id/care-plan'
      preLoaderRoute: typeof ResidentsIdCarePlanRouteImport
      parentRoute: typeof ResidentsIdRoute
    }
    '/residents/$id/assessments': {
      id: '/residents/$id/assessments'
      path: '/assessments'
      fullPath: '/residents/$id/assessments'
      preLoaderRoute: typeof ResidentsIdAssessmentsRouteImport
      parentRoute: typeof ResidentsIdRoute
    }
    '/assessments/new/$residentId': {
      id: '/assessments/new/$residentId'
      path: '/new/$residentId'
      fullPath: '/assessments/new/$residentId'
      preLoaderRoute: typeof AssessmentsNewResidentIdRouteImport
      parentRoute: typeof AssessmentsRoute
    }
  }
}

interface AssessmentsRouteChildren {
  AssessmentsAssessmentIdRoute: typeof AssessmentsAssessmentIdRoute
  AssessmentsReassessmentRoute: typeof AssessmentsReassessmentRoute
  AssessmentsIndexRoute: typeof AssessmentsIndexRoute
  AssessmentsNewResidentIdRoute: typeof AssessmentsNewResidentIdRoute
}

const AssessmentsRouteChildren: AssessmentsRouteChildren = {
  AssessmentsAssessmentIdRoute: AssessmentsAssessmentIdRoute,
  AssessmentsReassessmentRoute: AssessmentsReassessmentRoute,
  AssessmentsIndexRoute: AssessmentsIndexRoute,
  AssessmentsNewResidentIdRoute: AssessmentsNewResidentIdRoute,
}

const AssessmentsRouteWithChildren = AssessmentsRoute._addFileChildren(
  AssessmentsRouteChildren,
)

interface CarePlansRouteChildren {
  CarePlansIdRoute: typeof CarePlansIdRoute
}

const CarePlansRouteChildren: CarePlansRouteChildren = {
  CarePlansIdRoute: CarePlansIdRoute,
}

const CarePlansRouteWithChildren = CarePlansRoute._addFileChildren(
  CarePlansRouteChildren,
)

interface ReportsRouteChildren {
  ReportsDailyCareRoute: typeof ReportsDailyCareRoute
}

const ReportsRouteChildren: ReportsRouteChildren = {
  ReportsDailyCareRoute: ReportsDailyCareRoute,
}

const ReportsRouteWithChildren =
  ReportsRoute._addFileChildren(ReportsRouteChildren)

interface ResidentsIdRouteChildren {
  ResidentsIdAssessmentsRoute: typeof ResidentsIdAssessmentsRoute
  ResidentsIdCarePlanRoute: typeof ResidentsIdCarePlanRoute
  ResidentsIdQualityOfLifeRoute: typeof ResidentsIdQualityOfLifeRoute
  ResidentsIdRecordRoute: typeof ResidentsIdRecordRoute
  ResidentsIdTimelineRoute: typeof ResidentsIdTimelineRoute
}

const ResidentsIdRouteChildren: ResidentsIdRouteChildren = {
  ResidentsIdAssessmentsRoute: ResidentsIdAssessmentsRoute,
  ResidentsIdCarePlanRoute: ResidentsIdCarePlanRoute,
  ResidentsIdQualityOfLifeRoute: ResidentsIdQualityOfLifeRoute,
  ResidentsIdRecordRoute: ResidentsIdRecordRoute,
  ResidentsIdTimelineRoute: ResidentsIdTimelineRoute,
}

const ResidentsIdRouteWithChildren = ResidentsIdRoute._addFileChildren(
  ResidentsIdRouteChildren,
)

interface ResidentsRouteChildren {
  ResidentsIdRoute: typeof ResidentsIdRouteWithChildren
  ResidentsIndexRoute: typeof ResidentsIndexRoute
}

const ResidentsRouteChildren: ResidentsRouteChildren = {
  ResidentsIdRoute: ResidentsIdRouteWithChildren,
  ResidentsIndexRoute: ResidentsIndexRoute,
}

const ResidentsRouteWithChildren = ResidentsRoute._addFileChildren(
  ResidentsRouteChildren,
)

interface VitalsRouteChildren {
  VitalsAuditRoute: typeof VitalsAuditRoute
}

const VitalsRouteChildren: VitalsRouteChildren = {
  VitalsAuditRoute: VitalsAuditRoute,
}

const VitalsRouteWithChildren =
  VitalsRoute._addFileChildren(VitalsRouteChildren)

interface WorkforceStaffRouteChildren {
  WorkforceStaffStaffMemberIdRoute: typeof WorkforceStaffStaffMemberIdRoute
}

const WorkforceStaffRouteChildren: WorkforceStaffRouteChildren = {
  WorkforceStaffStaffMemberIdRoute: WorkforceStaffStaffMemberIdRoute,
}

const WorkforceStaffRouteWithChildren = WorkforceStaffRoute._addFileChildren(
  WorkforceStaffRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsDashboardRoute: AccountsDashboardRoute,
  AlertsRoute: AlertsRoute,
  AssessmentsRoute: AssessmentsRouteWithChildren,
  AuditLogsRoute: AuditLogsRoute,
  CarePlansRoute: CarePlansRouteWithChildren,
  ComplianceRoute: ComplianceRoute,
  DailyNotesRoute: DailyNotesRoute,
  HandoversRoute: HandoversRoute,
  IncidentsRoute: IncidentsRoute,
  InterventionsRoute: InterventionsRoute,
  MaintenanceHousekeepingRoute: MaintenanceHousekeepingRoute,
  MdtNotesRoute: MdtNotesRoute,
  OperationsRoute: OperationsRoute,
  OutingsRoute: OutingsRoute,
  ProfileRoute: ProfileRoute,
  QualityGovernanceRoute: QualityGovernanceRoute,
  ReportsRoute: ReportsRouteWithChildren,
  ResidentsRoute: ResidentsRouteWithChildren,
  RisksRoute: RisksRoute,
  StaffManagementRoute: StaffManagementRoute,
  TasksRoute: TasksRoute,
  TrainingDashboardRoute: TrainingDashboardRoute,
  VisitorsRoute: VisitorsRoute,
  VitalsRoute: VitalsRouteWithChildren,
  ChartsResidentIdRoute: ChartsResidentIdRoute,
  InspectionResidentIdRoute: InspectionResidentIdRoute,
  WorkforceStaffRoute: WorkforceStaffRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
