/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VitalsRouteImport } from './routes/vitals'
import { Route as VisitorsRouteImport } from './routes/visitors'
import { Route as TrainingDashboardRouteImport } from './routes/training-dashboard'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as StaffManagementRouteImport } from './routes/staff-management'
import { Route as RisksRouteImport } from './routes/risks'
import { Route as ResidentsRouteImport } from './routes/residents'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as QualityGovernanceRouteImport } from './routes/quality-governance'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OutingsRouteImport } from './routes/outings'
import { Route as OperationsRouteImport } from './routes/operations'
import { Route as MdtNotesRouteImport } from './routes/mdt-notes'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as InterventionsRouteImport } from './routes/interventions'
import { Route as IncidentsRouteImport } from './routes/incidents'
import { Route as HandoversRouteImport } from './routes/handovers'
import { Route as DailyNotesRouteImport } from './routes/daily-notes'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as CarePlansRouteImport } from './routes/care-plans'
import { Route as AuditLogsRouteImport } from './routes/audit-logs'
import { Route as AssessmentsRouteImport } from './routes/assessments'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AccountsDashboardRouteImport } from './routes/accounts-dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResidentsIndexRouteImport } from './routes/residents.index'
import { Route as AssessmentsIndexRouteImport } from './routes/assessments.index'
import { Route as WorkforceVisaDocumentsRouteImport } from './routes/workforce.visa-documents'
import { Route as WorkforceTrainingRouteImport } from './routes/workforce.training'
import { Route as WorkforceStaffRouteImport } from './routes/workforce.staff'
import { Route as WorkforceRosteringRouteImport } from './routes/workforce.rostering'
import { Route as WorkforceRegistrationsRouteImport } from './routes/workforce.registrations'
import { Route as WorkforceRecruitmentRouteImport } from './routes/workforce.recruitment'
import { Route as WorkforceProbationRouteImport } from './routes/workforce.probation'
import { Route as WorkforceLeaveRouteImport } from './routes/workforce.leave'
import { Route as WorkforceEstablishmentRouteImport } from './routes/workforce.establishment'
import { Route as WorkforceEmploymentRouteImport } from './routes/workforce.employment'
import { Route as WorkforceCompetenciesRouteImport } from './routes/workforce.competencies'
import { Route as WorkforceAgencyRouteImport } from './routes/workforce.agency'
import { Route as VitalsAuditRouteImport } from './routes/vitals.audit'
import { Route as ResidentsIdRouteImport } from './routes/residents.$id'
import { Route as ReportsDailyCareRouteImport } from './routes/reports.daily-care'
import { Route as MaintenanceWorkOrdersRouteImport } from './routes/maintenance.work-orders'
import { Route as MaintenanceSettingsRouteImport } from './routes/maintenance.settings'
import { Route as MaintenanceSafetyComplianceRouteImport } from './routes/maintenance.safety-compliance'
import { Route as MaintenanceRoomsLocationsRouteImport } from './routes/maintenance.rooms-locations'
import { Route as MaintenanceReportsRouteImport } from './routes/maintenance.reports'
import { Route as MaintenancePlannedMaintenanceRouteImport } from './routes/maintenance.planned-maintenance'
import { Route as MaintenanceHousekeepingRouteImport } from './routes/maintenance.housekeeping'
import { Route as MaintenanceCorrectiveActionsRouteImport } from './routes/maintenance.corrective-actions'
import { Route as MaintenanceContractorsRouteImport } from './routes/maintenance.contractors'
import { Route as MaintenanceCertificatesRouteImport } from './routes/maintenance.certificates'
import { Route as MaintenanceAssetsRouteImport } from './routes/maintenance.assets'
import { Route as InspectionResidentIdRouteImport } from './routes/inspection.$residentId'
import { Route as ChartsResidentIdRouteImport } from './routes/charts.$residentId'
import { Route as AssessmentsReassessmentRouteImport } from './routes/assessments.reassessment'
import { Route as AssessmentsAssessmentIdRouteImport } from './routes/assessments.$assessmentId'
import { Route as WorkforceStaffStaffMemberIdRouteImport } from './routes/workforce.staff.$staffMemberId'
import { Route as WorkforceRosteringVacantRouteImport } from './routes/workforce.rostering.vacant'
import { Route as WorkforceRosteringTemplatesRouteImport } from './routes/workforce.rostering.templates'
import { Route as WorkforceRosteringSettingsRouteImport } from './routes/workforce.rostering.settings'
import { Route as WorkforceRosteringRequirementsRouteImport } from './routes/workforce.rostering.requirements'
import { Route as WorkforceRosteringReportsRouteImport } from './routes/workforce.rostering.reports'
import { Route as WorkforceRosteringPeriodsRouteImport } from './routes/workforce.rostering.periods'
import { Route as WorkforceRosteringPendingRouteImport } from './routes/workforce.rostering.pending'
import { Route as WorkforceRosteringCurrentRouteImport } from './routes/workforce.rostering.current'
import { Route as WorkforceRosteringConflictsRouteImport } from './routes/workforce.rostering.conflicts'
import { Route as WorkforceRosteringChangesRouteImport } from './routes/workforce.rostering.changes'
import { Route as WorkforceRosteringAvailabilityRouteImport } from './routes/workforce.rostering.availability'
import { Route as WorkforceRosteringAgencyRouteImport } from './routes/workforce.rostering.agency'
import { Route as ResidentsIdTimelineRouteImport } from './routes/residents.$id.timeline'
import { Route as ResidentsIdRecordRouteImport } from './routes/residents.$id.record'
import { Route as ResidentsIdQualityOfLifeRouteImport } from './routes/residents.$id.quality-of-life'
import { Route as ResidentsIdCarePlanRouteImport } from './routes/residents.$id.care-plan'
import { Route as ResidentsIdAssessmentsRouteImport } from './routes/residents.$id.assessments'
import { Route as MaintenanceWorkOrdersNewRouteImport } from './routes/maintenance.work-orders.new'
import { Route as MaintenanceWorkOrdersWorkOrderIdRouteImport } from './routes/maintenance.work-orders.$workOrderId'
import { Route as MaintenanceContractorsRegisterRouteImport } from './routes/maintenance.contractors.register'
import { Route as MaintenanceContractorsNewRouteImport } from './routes/maintenance.contractors.new'
import { Route as MaintenanceContractorsContractorIdRouteImport } from './routes/maintenance.contractors.$contractorId'
import { Route as MaintenanceCertificatesTypesRouteImport } from './routes/maintenance.certificates.types'
import { Route as MaintenanceCertificatesRequirementsRouteImport } from './routes/maintenance.certificates.requirements'
import { Route as MaintenanceCertificatesRegisterRouteImport } from './routes/maintenance.certificates.register'
import { Route as MaintenanceCertificatesNewRouteImport } from './routes/maintenance.certificates.new'
import { Route as MaintenanceCertificatesMissingRouteImport } from './routes/maintenance.certificates.missing'
import { Route as MaintenanceCertificatesExpiredRouteImport } from './routes/maintenance.certificates.expired'
import { Route as MaintenanceCertificatesDueSoonRouteImport } from './routes/maintenance.certificates.due-soon'
import { Route as MaintenanceCertificatesArchivedRouteImport } from './routes/maintenance.certificates.archived'
import { Route as MaintenanceCertificatesIdRouteImport } from './routes/maintenance.certificates.$id'
import { Route as AssessmentsNewResidentIdRouteImport } from './routes/assessments.new.$residentId'
import { Route as MaintenanceWorkOrdersWorkOrderIdEditRouteImport } from './routes/maintenance.work-orders.$workOrderId.edit'
import { Route as MaintenanceContractorsContractorIdEditRouteImport } from './routes/maintenance.contractors.$contractorId.edit'
import { Route as MaintenanceCertificatesIdRenewRouteImport } from './routes/maintenance.certificates.$id.renew'
import { Route as MaintenanceCertificatesIdEditRouteImport } from './routes/maintenance.certificates.$id.edit'

const VitalsRoute = VitalsRouteImport.update({
  id: '/vitals',
  path: '/vitals',
  getParentRoute: () => rootRouteImport,
} as any)
const VisitorsRoute = VisitorsRouteImport.update({
  id: '/visitors',
  path: '/visitors',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingDashboardRoute = TrainingDashboardRouteImport.update({
  id: '/training-dashboard',
  path: '/training-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffManagementRoute = StaffManagementRouteImport.update({
  id: '/staff-management',
  path: '/staff-management',
  getParentRoute: () => rootRouteImport,
} as any)
const RisksRoute = RisksRouteImport.update({
  id: '/risks',
  path: '/risks',
  getParentRoute: () => rootRouteImport,
} as any)
const ResidentsRoute = ResidentsRouteImport.update({
  id: '/residents',
  path: '/residents',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const QualityGovernanceRoute = QualityGovernanceRouteImport.update({
  id: '/quality-governance',
  path: '/quality-governance',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OutingsRoute = OutingsRouteImport.update({
  id: '/outings',
  path: '/outings',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsRoute = OperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const MdtNotesRoute = MdtNotesRouteImport.update({
  id: '/mdt-notes',
  path: '/mdt-notes',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const InterventionsRoute = InterventionsRouteImport.update({
  id: '/interventions',
  path: '/interventions',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsRoute = IncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => rootRouteImport,
} as any)
const HandoversRoute = HandoversRouteImport.update({
  id: '/handovers',
  path: '/handovers',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyNotesRoute = DailyNotesRouteImport.update({
  id: '/daily-notes',
  path: '/daily-notes',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const CarePlansRoute = CarePlansRouteImport.update({
  id: '/care-plans',
  path: '/care-plans',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogsRoute = AuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentsRoute = AssessmentsRouteImport.update({
  id: '/assessments',
  path: '/assessments',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsDashboardRoute = AccountsDashboardRouteImport.update({
  id: '/accounts-dashboard',
  path: '/accounts-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResidentsIndexRoute = ResidentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ResidentsRoute,
} as any)
const AssessmentsIndexRoute = AssessmentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AssessmentsRoute,
} as any)
const WorkforceVisaDocumentsRoute = WorkforceVisaDocumentsRouteImport.update({
  id: '/workforce/visa-documents',
  path: '/workforce/visa-documents',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkforceTrainingRoute = WorkforceTrainingRouteImport.update({
  id: '/workforce/training',
  path: '/workforce/training',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkforceStaffRoute = WorkforceStaffRouteImport.update({
  id: '/workforce/staff',
  path: '/workforce/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkforceRosteringRoute = WorkforceRosteringRouteImport.update({
  id: '/workforce/rostering',
  path: '/workforce/rostering',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkforceRegistrationsRoute = WorkforceRegistrationsRouteImport.update({
  id: '/workforce/registrations',
  path: '/workforce/registrations',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkforceRecruitmentRoute = WorkforceRecruitmentRouteImport.update({
  id: '/workforce/recruitment',
  path: '/workforce/recruitment',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkforceProbationRoute = WorkforceProbationRouteImport.update({
  id: '/workforce/probation',
  path: '/workforce/probation',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkforceLeaveRoute = WorkforceLeaveRouteImport.update({
  id: '/workforce/leave',
  path: '/workforce/leave',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkforceEstablishmentRoute = WorkforceEstablishmentRouteImport.update({
  id: '/workforce/establishment',
  path: '/workforce/establishment',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkforceEmploymentRoute = WorkforceEmploymentRouteImport.update({
  id: '/workforce/employment',
  path: '/workforce/employment',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkforceCompetenciesRoute = WorkforceCompetenciesRouteImport.update({
  id: '/workforce/competencies',
  path: '/workforce/competencies',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkforceAgencyRoute = WorkforceAgencyRouteImport.update({
  id: '/workforce/agency',
  path: '/workforce/agency',
  getParentRoute: () => rootRouteImport,
} as any)
const VitalsAuditRoute = VitalsAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => VitalsRoute,
} as any)
const ResidentsIdRoute = ResidentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ResidentsRoute,
} as any)
const ReportsDailyCareRoute = ReportsDailyCareRouteImport.update({
  id: '/daily-care',
  path: '/daily-care',
  getParentRoute: () => ReportsRoute,
} as any)
const MaintenanceWorkOrdersRoute = MaintenanceWorkOrdersRouteImport.update({
  id: '/work-orders',
  path: '/work-orders',
  getParentRoute: () => MaintenanceRoute,
} as any)
const MaintenanceSettingsRoute = MaintenanceSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => MaintenanceRoute,
} as any)
const MaintenanceSafetyComplianceRoute =
  MaintenanceSafetyComplianceRouteImport.update({
    id: '/safety-compliance',
    path: '/safety-compliance',
    getParentRoute: () => MaintenanceRoute,
  } as any)
const MaintenanceRoomsLocationsRoute =
  MaintenanceRoomsLocationsRouteImport.update({
    id: '/rooms-locations',
    path: '/rooms-locations',
    getParentRoute: () => MaintenanceRoute,
  } as any)
const MaintenanceReportsRoute = MaintenanceReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => MaintenanceRoute,
} as any)
const MaintenancePlannedMaintenanceRoute =
  MaintenancePlannedMaintenanceRouteImport.update({
    id: '/planned-maintenance',
    path: '/planned-maintenance',
    getParentRoute: () => MaintenanceRoute,
  } as any)
const MaintenanceHousekeepingRoute = MaintenanceHousekeepingRouteImport.update({
  id: '/housekeeping',
  path: '/housekeeping',
  getParentRoute: () => MaintenanceRoute,
} as any)
const MaintenanceCorrectiveActionsRoute =
  MaintenanceCorrectiveActionsRouteImport.update({
    id: '/corrective-actions',
    path: '/corrective-actions',
    getParentRoute: () => MaintenanceRoute,
  } as any)
const MaintenanceContractorsRoute = MaintenanceContractorsRouteImport.update({
  id: '/contractors',
  path: '/contractors',
  getParentRoute: () => MaintenanceRoute,
} as any)
const MaintenanceCertificatesRoute = MaintenanceCertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => MaintenanceRoute,
} as any)
const MaintenanceAssetsRoute = MaintenanceAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => MaintenanceRoute,
} as any)
const InspectionResidentIdRoute = InspectionResidentIdRouteImport.update({
  id: '/inspection/$residentId',
  path: '/inspection/$residentId',
  getParentRoute: () => rootRouteImport,
} as any)
const ChartsResidentIdRoute = ChartsResidentIdRouteImport.update({
  id: '/charts/$residentId',
  path: '/charts/$residentId',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentsReassessmentRoute = AssessmentsReassessmentRouteImport.update({
  id: '/reassessment',
  path: '/reassessment',
  getParentRoute: () => AssessmentsRoute,
} as any)
const AssessmentsAssessmentIdRoute = AssessmentsAssessmentIdRouteImport.update({
  id: '/$assessmentId',
  path: '/$assessmentId',
  getParentRoute: () => AssessmentsRoute,
} as any)
const WorkforceStaffStaffMemberIdRoute =
  WorkforceStaffStaffMemberIdRouteImport.update({
    id: '/$staffMemberId',
    path: '/$staffMemberId',
    getParentRoute: () => WorkforceStaffRoute,
  } as any)
const WorkforceRosteringVacantRoute =
  WorkforceRosteringVacantRouteImport.update({
    id: '/vacant',
    path: '/vacant',
    getParentRoute: () => WorkforceRosteringRoute,
  } as any)
const WorkforceRosteringTemplatesRoute =
  WorkforceRosteringTemplatesRouteImport.update({
    id: '/templates',
    path: '/templates',
    getParentRoute: () => WorkforceRosteringRoute,
  } as any)
const WorkforceRosteringSettingsRoute =
  WorkforceRosteringSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => WorkforceRosteringRoute,
  } as any)
const WorkforceRosteringRequirementsRoute =
  WorkforceRosteringRequirementsRouteImport.update({
    id: '/requirements',
    path: '/requirements',
    getParentRoute: () => WorkforceRosteringRoute,
  } as any)
const WorkforceRosteringReportsRoute =
  WorkforceRosteringReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => WorkforceRosteringRoute,
  } as any)
const WorkforceRosteringPeriodsRoute =
  WorkforceRosteringPeriodsRouteImport.update({
    id: '/periods',
    path: '/periods',
    getParentRoute: () => WorkforceRosteringRoute,
  } as any)
const WorkforceRosteringPendingRoute =
  WorkforceRosteringPendingRouteImport.update({
    id: '/pending',
    path: '/pending',
    getParentRoute: () => WorkforceRosteringRoute,
  } as any)
const WorkforceRosteringCurrentRoute =
  WorkforceRosteringCurrentRouteImport.update({
    id: '/current',
    path: '/current',
    getParentRoute: () => WorkforceRosteringRoute,
  } as any)
const WorkforceRosteringConflictsRoute =
  WorkforceRosteringConflictsRouteImport.update({
    id: '/conflicts',
    path: '/conflicts',
    getParentRoute: () => WorkforceRosteringRoute,
  } as any)
const WorkforceRosteringChangesRoute =
  WorkforceRosteringChangesRouteImport.update({
    id: '/changes',
    path: '/changes',
    getParentRoute: () => WorkforceRosteringRoute,
  } as any)
const WorkforceRosteringAvailabilityRoute =
  WorkforceRosteringAvailabilityRouteImport.update({
    id: '/availability',
    path: '/availability',
    getParentRoute: () => WorkforceRosteringRoute,
  } as any)
const WorkforceRosteringAgencyRoute =
  WorkforceRosteringAgencyRouteImport.update({
    id: '/agency',
    path: '/agency',
    getParentRoute: () => WorkforceRosteringRoute,
  } as any)
const ResidentsIdTimelineRoute = ResidentsIdTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => ResidentsIdRoute,
} as any)
const ResidentsIdRecordRoute = ResidentsIdRecordRouteImport.update({
  id: '/record',
  path: '/record',
  getParentRoute: () => ResidentsIdRoute,
} as any)
const ResidentsIdQualityOfLifeRoute =
  ResidentsIdQualityOfLifeRouteImport.update({
    id: '/quality-of-life',
    path: '/quality-of-life',
    getParentRoute: () => ResidentsIdRoute,
  } as any)
const ResidentsIdCarePlanRoute = ResidentsIdCarePlanRouteImport.update({
  id: '/care-plan',
  path: '/care-plan',
  getParentRoute: () => ResidentsIdRoute,
} as any)
const ResidentsIdAssessmentsRoute = ResidentsIdAssessmentsRouteImport.update({
  id: '/assessments',
  path: '/assessments',
  getParentRoute: () => ResidentsIdRoute,
} as any)
const MaintenanceWorkOrdersNewRoute =
  MaintenanceWorkOrdersNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => MaintenanceWorkOrdersRoute,
  } as any)
const MaintenanceWorkOrdersWorkOrderIdRoute =
  MaintenanceWorkOrdersWorkOrderIdRouteImport.update({
    id: '/$workOrderId',
    path: '/$workOrderId',
    getParentRoute: () => MaintenanceWorkOrdersRoute,
  } as any)
const MaintenanceContractorsRegisterRoute =
  MaintenanceContractorsRegisterRouteImport.update({
    id: '/register',
    path: '/register',
    getParentRoute: () => MaintenanceContractorsRoute,
  } as any)
const MaintenanceContractorsNewRoute =
  MaintenanceContractorsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => MaintenanceContractorsRoute,
  } as any)
const MaintenanceContractorsContractorIdRoute =
  MaintenanceContractorsContractorIdRouteImport.update({
    id: '/$contractorId',
    path: '/$contractorId',
    getParentRoute: () => MaintenanceContractorsRoute,
  } as any)
const MaintenanceCertificatesTypesRoute =
  MaintenanceCertificatesTypesRouteImport.update({
    id: '/types',
    path: '/types',
    getParentRoute: () => MaintenanceCertificatesRoute,
  } as any)
const MaintenanceCertificatesRequirementsRoute =
  MaintenanceCertificatesRequirementsRouteImport.update({
    id: '/requirements',
    path: '/requirements',
    getParentRoute: () => MaintenanceCertificatesRoute,
  } as any)
const MaintenanceCertificatesRegisterRoute =
  MaintenanceCertificatesRegisterRouteImport.update({
    id: '/register',
    path: '/register',
    getParentRoute: () => MaintenanceCertificatesRoute,
  } as any)
const MaintenanceCertificatesNewRoute =
  MaintenanceCertificatesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => MaintenanceCertificatesRoute,
  } as any)
const MaintenanceCertificatesMissingRoute =
  MaintenanceCertificatesMissingRouteImport.update({
    id: '/missing',
    path: '/missing',
    getParentRoute: () => MaintenanceCertificatesRoute,
  } as any)
const MaintenanceCertificatesExpiredRoute =
  MaintenanceCertificatesExpiredRouteImport.update({
    id: '/expired',
    path: '/expired',
    getParentRoute: () => MaintenanceCertificatesRoute,
  } as any)
const MaintenanceCertificatesDueSoonRoute =
  MaintenanceCertificatesDueSoonRouteImport.update({
    id: '/due-soon',
    path: '/due-soon',
    getParentRoute: () => MaintenanceCertificatesRoute,
  } as any)
const MaintenanceCertificatesArchivedRoute =
  MaintenanceCertificatesArchivedRouteImport.update({
    id: '/archived',
    path: '/archived',
    getParentRoute: () => MaintenanceCertificatesRoute,
  } as any)
const MaintenanceCertificatesIdRoute =
  MaintenanceCertificatesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => MaintenanceCertificatesRoute,
  } as any)
const AssessmentsNewResidentIdRoute =
  AssessmentsNewResidentIdRouteImport.update({
    id: '/new/$residentId',
    path: '/new/$residentId',
    getParentRoute: () => AssessmentsRoute,
  } as any)
const MaintenanceWorkOrdersWorkOrderIdEditRoute =
  MaintenanceWorkOrdersWorkOrderIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => MaintenanceWorkOrdersWorkOrderIdRoute,
  } as any)
const MaintenanceContractorsContractorIdEditRoute =
  MaintenanceContractorsContractorIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => MaintenanceContractorsContractorIdRoute,
  } as any)
const MaintenanceCertificatesIdRenewRoute =
  MaintenanceCertificatesIdRenewRouteImport.update({
    id: '/renew',
    path: '/renew',
    getParentRoute: () => MaintenanceCertificatesIdRoute,
  } as any)
const MaintenanceCertificatesIdEditRoute =
  MaintenanceCertificatesIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => MaintenanceCertificatesIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts-dashboard': typeof AccountsDashboardRoute
  '/alerts': typeof AlertsRoute
  '/assessments': typeof AssessmentsRouteWithChildren
  '/audit-logs': typeof AuditLogsRoute
  '/care-plans': typeof CarePlansRoute
  '/compliance': typeof ComplianceRoute
  '/daily-notes': typeof DailyNotesRoute
  '/handovers': typeof HandoversRoute
  '/incidents': typeof IncidentsRoute
  '/interventions': typeof InterventionsRoute
  '/maintenance': typeof MaintenanceRouteWithChildren
  '/mdt-notes': typeof MdtNotesRoute
  '/operations': typeof OperationsRoute
  '/outings': typeof OutingsRoute
  '/profile': typeof ProfileRoute
  '/quality-governance': typeof QualityGovernanceRoute
  '/reports': typeof ReportsRouteWithChildren
  '/residents': typeof ResidentsRouteWithChildren
  '/risks': typeof RisksRoute
  '/staff-management': typeof StaffManagementRoute
  '/tasks': typeof TasksRoute
  '/training-dashboard': typeof TrainingDashboardRoute
  '/visitors': typeof VisitorsRoute
  '/vitals': typeof VitalsRouteWithChildren
  '/assessments/$assessmentId': typeof AssessmentsAssessmentIdRoute
  '/assessments/reassessment': typeof AssessmentsReassessmentRoute
  '/charts/$residentId': typeof ChartsResidentIdRoute
  '/inspection/$residentId': typeof InspectionResidentIdRoute
  '/maintenance/assets': typeof MaintenanceAssetsRoute
  '/maintenance/certificates': typeof MaintenanceCertificatesRouteWithChildren
  '/maintenance/contractors': typeof MaintenanceContractorsRouteWithChildren
  '/maintenance/corrective-actions': typeof MaintenanceCorrectiveActionsRoute
  '/maintenance/housekeeping': typeof MaintenanceHousekeepingRoute
  '/maintenance/planned-maintenance': typeof MaintenancePlannedMaintenanceRoute
  '/maintenance/reports': typeof MaintenanceReportsRoute
  '/maintenance/rooms-locations': typeof MaintenanceRoomsLocationsRoute
  '/maintenance/safety-compliance': typeof MaintenanceSafetyComplianceRoute
  '/maintenance/settings': typeof MaintenanceSettingsRoute
  '/maintenance/work-orders': typeof MaintenanceWorkOrdersRouteWithChildren
  '/reports/daily-care': typeof ReportsDailyCareRoute
  '/residents/$id': typeof ResidentsIdRouteWithChildren
  '/vitals/audit': typeof VitalsAuditRoute
  '/workforce/agency': typeof WorkforceAgencyRoute
  '/workforce/competencies': typeof WorkforceCompetenciesRoute
  '/workforce/employment': typeof WorkforceEmploymentRoute
  '/workforce/establishment': typeof WorkforceEstablishmentRoute
  '/workforce/leave': typeof WorkforceLeaveRoute
  '/workforce/probation': typeof WorkforceProbationRoute
  '/workforce/recruitment': typeof WorkforceRecruitmentRoute
  '/workforce/registrations': typeof WorkforceRegistrationsRoute
  '/workforce/rostering': typeof WorkforceRosteringRouteWithChildren
  '/workforce/staff': typeof WorkforceStaffRouteWithChildren
  '/workforce/training': typeof WorkforceTrainingRoute
  '/workforce/visa-documents': typeof WorkforceVisaDocumentsRoute
  '/assessments/': typeof AssessmentsIndexRoute
  '/residents/': typeof ResidentsIndexRoute
  '/assessments/new/$residentId': typeof AssessmentsNewResidentIdRoute
  '/maintenance/certificates/$id': typeof MaintenanceCertificatesIdRouteWithChildren
  '/maintenance/certificates/archived': typeof MaintenanceCertificatesArchivedRoute
  '/maintenance/certificates/due-soon': typeof MaintenanceCertificatesDueSoonRoute
  '/maintenance/certificates/expired': typeof MaintenanceCertificatesExpiredRoute
  '/maintenance/certificates/missing': typeof MaintenanceCertificatesMissingRoute
  '/maintenance/certificates/new': typeof MaintenanceCertificatesNewRoute
  '/maintenance/certificates/register': typeof MaintenanceCertificatesRegisterRoute
  '/maintenance/certificates/requirements': typeof MaintenanceCertificatesRequirementsRoute
  '/maintenance/certificates/types': typeof MaintenanceCertificatesTypesRoute
  '/maintenance/contractors/$contractorId': typeof MaintenanceContractorsContractorIdRouteWithChildren
  '/maintenance/contractors/new': typeof MaintenanceContractorsNewRoute
  '/maintenance/contractors/register': typeof MaintenanceContractorsRegisterRoute
  '/maintenance/work-orders/$workOrderId': typeof MaintenanceWorkOrdersWorkOrderIdRouteWithChildren
  '/maintenance/work-orders/new': typeof MaintenanceWorkOrdersNewRoute
  '/residents/$id/assessments': typeof ResidentsIdAssessmentsRoute
  '/residents/$id/care-plan': typeof ResidentsIdCarePlanRoute
  '/residents/$id/quality-of-life': typeof ResidentsIdQualityOfLifeRoute
  '/residents/$id/record': typeof ResidentsIdRecordRoute
  '/residents/$id/timeline': typeof ResidentsIdTimelineRoute
  '/workforce/rostering/agency': typeof WorkforceRosteringAgencyRoute
  '/workforce/rostering/availability': typeof WorkforceRosteringAvailabilityRoute
  '/workforce/rostering/changes': typeof WorkforceRosteringChangesRoute
  '/workforce/rostering/conflicts': typeof WorkforceRosteringConflictsRoute
  '/workforce/rostering/current': typeof WorkforceRosteringCurrentRoute
  '/workforce/rostering/pending': typeof WorkforceRosteringPendingRoute
  '/workforce/rostering/periods': typeof WorkforceRosteringPeriodsRoute
  '/workforce/rostering/reports': typeof WorkforceRosteringReportsRoute
  '/workforce/rostering/requirements': typeof WorkforceRosteringRequirementsRoute
  '/workforce/rostering/settings': typeof WorkforceRosteringSettingsRoute
  '/workforce/rostering/templates': typeof WorkforceRosteringTemplatesRoute
  '/workforce/rostering/vacant': typeof WorkforceRosteringVacantRoute
  '/workforce/staff/$staffMemberId': typeof WorkforceStaffStaffMemberIdRoute
  '/maintenance/certificates/$id/edit': typeof MaintenanceCertificatesIdEditRoute
  '/maintenance/certificates/$id/renew': typeof MaintenanceCertificatesIdRenewRoute
  '/maintenance/contractors/$contractorId/edit': typeof MaintenanceContractorsContractorIdEditRoute
  '/maintenance/work-orders/$workOrderId/edit': typeof MaintenanceWorkOrdersWorkOrderIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts-dashboard': typeof AccountsDashboardRoute
  '/alerts': typeof AlertsRoute
  '/audit-logs': typeof AuditLogsRoute
  '/care-plans': typeof CarePlansRoute
  '/compliance': typeof ComplianceRoute
  '/daily-notes': typeof DailyNotesRoute
  '/handovers': typeof HandoversRoute
  '/incidents': typeof IncidentsRoute
  '/interventions': typeof InterventionsRoute
  '/maintenance': typeof MaintenanceRouteWithChildren
  '/mdt-notes': typeof MdtNotesRoute
  '/operations': typeof OperationsRoute
  '/outings': typeof OutingsRoute
  '/profile': typeof ProfileRoute
  '/quality-governance': typeof QualityGovernanceRoute
  '/reports': typeof ReportsRouteWithChildren
  '/risks': typeof RisksRoute
  '/staff-management': typeof StaffManagementRoute
  '/tasks': typeof TasksRoute
  '/training-dashboard': typeof TrainingDashboardRoute
  '/visitors': typeof VisitorsRoute
  '/vitals': typeof VitalsRouteWithChildren
  '/assessments/$assessmentId': typeof AssessmentsAssessmentIdRoute
  '/assessments/reassessment': typeof AssessmentsReassessmentRoute
  '/charts/$residentId': typeof ChartsResidentIdRoute
  '/inspection/$residentId': typeof InspectionResidentIdRoute
  '/maintenance/assets': typeof MaintenanceAssetsRoute
  '/maintenance/certificates': typeof MaintenanceCertificatesRouteWithChildren
  '/maintenance/contractors': typeof MaintenanceContractorsRouteWithChildren
  '/maintenance/corrective-actions': typeof MaintenanceCorrectiveActionsRoute
  '/maintenance/housekeeping': typeof MaintenanceHousekeepingRoute
  '/maintenance/planned-maintenance': typeof MaintenancePlannedMaintenanceRoute
  '/maintenance/reports': typeof MaintenanceReportsRoute
  '/maintenance/rooms-locations': typeof MaintenanceRoomsLocationsRoute
  '/maintenance/safety-compliance': typeof MaintenanceSafetyComplianceRoute
  '/maintenance/settings': typeof MaintenanceSettingsRoute
  '/maintenance/work-orders': typeof MaintenanceWorkOrdersRouteWithChildren
  '/reports/daily-care': typeof ReportsDailyCareRoute
  '/residents/$id': typeof ResidentsIdRouteWithChildren
  '/vitals/audit': typeof VitalsAuditRoute
  '/workforce/agency': typeof WorkforceAgencyRoute
  '/workforce/competencies': typeof WorkforceCompetenciesRoute
  '/workforce/employment': typeof WorkforceEmploymentRoute
  '/workforce/establishment': typeof WorkforceEstablishmentRoute
  '/workforce/leave': typeof WorkforceLeaveRoute
  '/workforce/probation': typeof WorkforceProbationRoute
  '/workforce/recruitment': typeof WorkforceRecruitmentRoute
  '/workforce/registrations': typeof WorkforceRegistrationsRoute
  '/workforce/rostering': typeof WorkforceRosteringRouteWithChildren
  '/workforce/staff': typeof WorkforceStaffRouteWithChildren
  '/workforce/training': typeof WorkforceTrainingRoute
  '/workforce/visa-documents': typeof WorkforceVisaDocumentsRoute
  '/assessments': typeof AssessmentsIndexRoute
  '/residents': typeof ResidentsIndexRoute
  '/assessments/new/$residentId': typeof AssessmentsNewResidentIdRoute
  '/maintenance/certificates/$id': typeof MaintenanceCertificatesIdRouteWithChildren
  '/maintenance/certificates/archived': typeof MaintenanceCertificatesArchivedRoute
  '/maintenance/certificates/due-soon': typeof MaintenanceCertificatesDueSoonRoute
  '/maintenance/certificates/expired': typeof MaintenanceCertificatesExpiredRoute
  '/maintenance/certificates/missing': typeof MaintenanceCertificatesMissingRoute
  '/maintenance/certificates/new': typeof MaintenanceCertificatesNewRoute
  '/maintenance/certificates/register': typeof MaintenanceCertificatesRegisterRoute
  '/maintenance/certificates/requirements': typeof MaintenanceCertificatesRequirementsRoute
  '/maintenance/certificates/types': typeof MaintenanceCertificatesTypesRoute
  '/maintenance/contractors/$contractorId': typeof MaintenanceContractorsContractorIdRouteWithChildren
  '/maintenance/contractors/new': typeof MaintenanceContractorsNewRoute
  '/maintenance/contractors/register': typeof MaintenanceContractorsRegisterRoute
  '/maintenance/work-orders/$workOrderId': typeof MaintenanceWorkOrdersWorkOrderIdRouteWithChildren
  '/maintenance/work-orders/new': typeof MaintenanceWorkOrdersNewRoute
  '/residents/$id/assessments': typeof ResidentsIdAssessmentsRoute
  '/residents/$id/care-plan': typeof ResidentsIdCarePlanRoute
  '/residents/$id/quality-of-life': typeof ResidentsIdQualityOfLifeRoute
  '/residents/$id/record': typeof ResidentsIdRecordRoute
  '/residents/$id/timeline': typeof ResidentsIdTimelineRoute
  '/workforce/rostering/agency': typeof WorkforceRosteringAgencyRoute
  '/workforce/rostering/availability': typeof WorkforceRosteringAvailabilityRoute
  '/workforce/rostering/changes': typeof WorkforceRosteringChangesRoute
  '/workforce/rostering/conflicts': typeof WorkforceRosteringConflictsRoute
  '/workforce/rostering/current': typeof WorkforceRosteringCurrentRoute
  '/workforce/rostering/pending': typeof WorkforceRosteringPendingRoute
  '/workforce/rostering/periods': typeof WorkforceRosteringPeriodsRoute
  '/workforce/rostering/reports': typeof WorkforceRosteringReportsRoute
  '/workforce/rostering/requirements': typeof WorkforceRosteringRequirementsRoute
  '/workforce/rostering/settings': typeof WorkforceRosteringSettingsRoute
  '/workforce/rostering/templates': typeof WorkforceRosteringTemplatesRoute
  '/workforce/rostering/vacant': typeof WorkforceRosteringVacantRoute
  '/workforce/staff/$staffMemberId': typeof WorkforceStaffStaffMemberIdRoute
  '/maintenance/certificates/$id/edit': typeof MaintenanceCertificatesIdEditRoute
  '/maintenance/certificates/$id/renew': typeof MaintenanceCertificatesIdRenewRoute
  '/maintenance/contractors/$contractorId/edit': typeof MaintenanceContractorsContractorIdEditRoute
  '/maintenance/work-orders/$workOrderId/edit': typeof MaintenanceWorkOrdersWorkOrderIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts-dashboard': typeof AccountsDashboardRoute
  '/alerts': typeof AlertsRoute
  '/assessments': typeof AssessmentsRouteWithChildren
  '/audit-logs': typeof AuditLogsRoute
  '/care-plans': typeof CarePlansRoute
  '/compliance': typeof ComplianceRoute
  '/daily-notes': typeof DailyNotesRoute
  '/handovers': typeof HandoversRoute
  '/incidents': typeof IncidentsRoute
  '/interventions': typeof InterventionsRoute
  '/maintenance': typeof MaintenanceRouteWithChildren
  '/mdt-notes': typeof MdtNotesRoute
  '/operations': typeof OperationsRoute
  '/outings': typeof OutingsRoute
  '/profile': typeof ProfileRoute
  '/quality-governance': typeof QualityGovernanceRoute
  '/reports': typeof ReportsRouteWithChildren
  '/residents': typeof ResidentsRouteWithChildren
  '/risks': typeof RisksRoute
  '/staff-management': typeof StaffManagementRoute
  '/tasks': typeof TasksRoute
  '/training-dashboard': typeof TrainingDashboardRoute
  '/visitors': typeof VisitorsRoute
  '/vitals': typeof VitalsRouteWithChildren
  '/assessments/$assessmentId': typeof AssessmentsAssessmentIdRoute
  '/assessments/reassessment': typeof AssessmentsReassessmentRoute
  '/charts/$residentId': typeof ChartsResidentIdRoute
  '/inspection/$residentId': typeof InspectionResidentIdRoute
  '/maintenance/assets': typeof MaintenanceAssetsRoute
  '/maintenance/certificates': typeof MaintenanceCertificatesRouteWithChildren
  '/maintenance/contractors': typeof MaintenanceContractorsRouteWithChildren
  '/maintenance/corrective-actions': typeof MaintenanceCorrectiveActionsRoute
  '/maintenance/housekeeping': typeof MaintenanceHousekeepingRoute
  '/maintenance/planned-maintenance': typeof MaintenancePlannedMaintenanceRoute
  '/maintenance/reports': typeof MaintenanceReportsRoute
  '/maintenance/rooms-locations': typeof MaintenanceRoomsLocationsRoute
  '/maintenance/safety-compliance': typeof MaintenanceSafetyComplianceRoute
  '/maintenance/settings': typeof MaintenanceSettingsRoute
  '/maintenance/work-orders': typeof MaintenanceWorkOrdersRouteWithChildren
  '/reports/daily-care': typeof ReportsDailyCareRoute
  '/residents/$id': typeof ResidentsIdRouteWithChildren
  '/vitals/audit': typeof VitalsAuditRoute
  '/workforce/agency': typeof WorkforceAgencyRoute
  '/workforce/competencies': typeof WorkforceCompetenciesRoute
  '/workforce/employment': typeof WorkforceEmploymentRoute
  '/workforce/establishment': typeof WorkforceEstablishmentRoute
  '/workforce/leave': typeof WorkforceLeaveRoute
  '/workforce/probation': typeof WorkforceProbationRoute
  '/workforce/recruitment': typeof WorkforceRecruitmentRoute
  '/workforce/registrations': typeof WorkforceRegistrationsRoute
  '/workforce/rostering': typeof WorkforceRosteringRouteWithChildren
  '/workforce/staff': typeof WorkforceStaffRouteWithChildren
  '/workforce/training': typeof WorkforceTrainingRoute
  '/workforce/visa-documents': typeof WorkforceVisaDocumentsRoute
  '/assessments/': typeof AssessmentsIndexRoute
  '/residents/': typeof ResidentsIndexRoute
  '/assessments/new/$residentId': typeof AssessmentsNewResidentIdRoute
  '/maintenance/certificates/$id': typeof MaintenanceCertificatesIdRouteWithChildren
  '/maintenance/certificates/archived': typeof MaintenanceCertificatesArchivedRoute
  '/maintenance/certificates/due-soon': typeof MaintenanceCertificatesDueSoonRoute
  '/maintenance/certificates/expired': typeof MaintenanceCertificatesExpiredRoute
  '/maintenance/certificates/missing': typeof MaintenanceCertificatesMissingRoute
  '/maintenance/certificates/new': typeof MaintenanceCertificatesNewRoute
  '/maintenance/certificates/register': typeof MaintenanceCertificatesRegisterRoute
  '/maintenance/certificates/requirements': typeof MaintenanceCertificatesRequirementsRoute
  '/maintenance/certificates/types': typeof MaintenanceCertificatesTypesRoute
  '/maintenance/contractors/$contractorId': typeof MaintenanceContractorsContractorIdRouteWithChildren
  '/maintenance/contractors/new': typeof MaintenanceContractorsNewRoute
  '/maintenance/contractors/register': typeof MaintenanceContractorsRegisterRoute
  '/maintenance/work-orders/$workOrderId': typeof MaintenanceWorkOrdersWorkOrderIdRouteWithChildren
  '/maintenance/work-orders/new': typeof MaintenanceWorkOrdersNewRoute
  '/residents/$id/assessments': typeof ResidentsIdAssessmentsRoute
  '/residents/$id/care-plan': typeof ResidentsIdCarePlanRoute
  '/residents/$id/quality-of-life': typeof ResidentsIdQualityOfLifeRoute
  '/residents/$id/record': typeof ResidentsIdRecordRoute
  '/residents/$id/timeline': typeof ResidentsIdTimelineRoute
  '/workforce/rostering/agency': typeof WorkforceRosteringAgencyRoute
  '/workforce/rostering/availability': typeof WorkforceRosteringAvailabilityRoute
  '/workforce/rostering/changes': typeof WorkforceRosteringChangesRoute
  '/workforce/rostering/conflicts': typeof WorkforceRosteringConflictsRoute
  '/workforce/rostering/current': typeof WorkforceRosteringCurrentRoute
  '/workforce/rostering/pending': typeof WorkforceRosteringPendingRoute
  '/workforce/rostering/periods': typeof WorkforceRosteringPeriodsRoute
  '/workforce/rostering/reports': typeof WorkforceRosteringReportsRoute
  '/workforce/rostering/requirements': typeof WorkforceRosteringRequirementsRoute
  '/workforce/rostering/settings': typeof WorkforceRosteringSettingsRoute
  '/workforce/rostering/templates': typeof WorkforceRosteringTemplatesRoute
  '/workforce/rostering/vacant': typeof WorkforceRosteringVacantRoute
  '/workforce/staff/$staffMemberId': typeof WorkforceStaffStaffMemberIdRoute
  '/maintenance/certificates/$id/edit': typeof MaintenanceCertificatesIdEditRoute
  '/maintenance/certificates/$id/renew': typeof MaintenanceCertificatesIdRenewRoute
  '/maintenance/contractors/$contractorId/edit': typeof MaintenanceContractorsContractorIdEditRoute
  '/maintenance/work-orders/$workOrderId/edit': typeof MaintenanceWorkOrdersWorkOrderIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts-dashboard'
    | '/alerts'
    | '/assessments'
    | '/audit-logs'
    | '/care-plans'
    | '/compliance'
    | '/daily-notes'
    | '/handovers'
    | '/incidents'
    | '/interventions'
    | '/maintenance'
    | '/mdt-notes'
    | '/operations'
    | '/outings'
    | '/profile'
    | '/quality-governance'
    | '/reports'
    | '/residents'
    | '/risks'
    | '/staff-management'
    | '/tasks'
    | '/training-dashboard'
    | '/visitors'
    | '/vitals'
    | '/assessments/$assessmentId'
    | '/assessments/reassessment'
    | '/charts/$residentId'
    | '/inspection/$residentId'
    | '/maintenance/assets'
    | '/maintenance/certificates'
    | '/maintenance/contractors'
    | '/maintenance/corrective-actions'
    | '/maintenance/housekeeping'
    | '/maintenance/planned-maintenance'
    | '/maintenance/reports'
    | '/maintenance/rooms-locations'
    | '/maintenance/safety-compliance'
    | '/maintenance/settings'
    | '/maintenance/work-orders'
    | '/reports/daily-care'
    | '/residents/$id'
    | '/vitals/audit'
    | '/workforce/agency'
    | '/workforce/competencies'
    | '/workforce/employment'
    | '/workforce/establishment'
    | '/workforce/leave'
    | '/workforce/probation'
    | '/workforce/recruitment'
    | '/workforce/registrations'
    | '/workforce/rostering'
    | '/workforce/staff'
    | '/workforce/training'
    | '/workforce/visa-documents'
    | '/assessments/'
    | '/residents/'
    | '/assessments/new/$residentId'
    | '/maintenance/certificates/$id'
    | '/maintenance/certificates/archived'
    | '/maintenance/certificates/due-soon'
    | '/maintenance/certificates/expired'
    | '/maintenance/certificates/missing'
    | '/maintenance/certificates/new'
    | '/maintenance/certificates/register'
    | '/maintenance/certificates/requirements'
    | '/maintenance/certificates/types'
    | '/maintenance/contractors/$contractorId'
    | '/maintenance/contractors/new'
    | '/maintenance/contractors/register'
    | '/maintenance/work-orders/$workOrderId'
    | '/maintenance/work-orders/new'
    | '/residents/$id/assessments'
    | '/residents/$id/care-plan'
    | '/residents/$id/quality-of-life'
    | '/residents/$id/record'
    | '/residents/$id/timeline'
    | '/workforce/rostering/agency'
    | '/workforce/rostering/availability'
    | '/workforce/rostering/changes'
    | '/workforce/rostering/conflicts'
    | '/workforce/rostering/current'
    | '/workforce/rostering/pending'
    | '/workforce/rostering/periods'
    | '/workforce/rostering/reports'
    | '/workforce/rostering/requirements'
    | '/workforce/rostering/settings'
    | '/workforce/rostering/templates'
    | '/workforce/rostering/vacant'
    | '/workforce/staff/$staffMemberId'
    | '/maintenance/certificates/$id/edit'
    | '/maintenance/certificates/$id/renew'
    | '/maintenance/contractors/$contractorId/edit'
    | '/maintenance/work-orders/$workOrderId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts-dashboard'
    | '/alerts'
    | '/audit-logs'
    | '/care-plans'
    | '/compliance'
    | '/daily-notes'
    | '/handovers'
    | '/incidents'
    | '/interventions'
    | '/maintenance'
    | '/mdt-notes'
    | '/operations'
    | '/outings'
    | '/profile'
    | '/quality-governance'
    | '/reports'
    | '/risks'
    | '/staff-management'
    | '/tasks'
    | '/training-dashboard'
    | '/visitors'
    | '/vitals'
    | '/assessments/$assessmentId'
    | '/assessments/reassessment'
    | '/charts/$residentId'
    | '/inspection/$residentId'
    | '/maintenance/assets'
    | '/maintenance/certificates'
    | '/maintenance/contractors'
    | '/maintenance/corrective-actions'
    | '/maintenance/housekeeping'
    | '/maintenance/planned-maintenance'
    | '/maintenance/reports'
    | '/maintenance/rooms-locations'
    | '/maintenance/safety-compliance'
    | '/maintenance/settings'
    | '/maintenance/work-orders'
    | '/reports/daily-care'
    | '/residents/$id'
    | '/vitals/audit'
    | '/workforce/agency'
    | '/workforce/competencies'
    | '/workforce/employment'
    | '/workforce/establishment'
    | '/workforce/leave'
    | '/workforce/probation'
    | '/workforce/recruitment'
    | '/workforce/registrations'
    | '/workforce/rostering'
    | '/workforce/staff'
    | '/workforce/training'
    | '/workforce/visa-documents'
    | '/assessments'
    | '/residents'
    | '/assessments/new/$residentId'
    | '/maintenance/certificates/$id'
    | '/maintenance/certificates/archived'
    | '/maintenance/certificates/due-soon'
    | '/maintenance/certificates/expired'
    | '/maintenance/certificates/missing'
    | '/maintenance/certificates/new'
    | '/maintenance/certificates/register'
    | '/maintenance/certificates/requirements'
    | '/maintenance/certificates/types'
    | '/maintenance/contractors/$contractorId'
    | '/maintenance/contractors/new'
    | '/maintenance/contractors/register'
    | '/maintenance/work-orders/$workOrderId'
    | '/maintenance/work-orders/new'
    | '/residents/$id/assessments'
    | '/residents/$id/care-plan'
    | '/residents/$id/quality-of-life'
    | '/residents/$id/record'
    | '/residents/$id/timeline'
    | '/workforce/rostering/agency'
    | '/workforce/rostering/availability'
    | '/workforce/rostering/changes'
    | '/workforce/rostering/conflicts'
    | '/workforce/rostering/current'
    | '/workforce/rostering/pending'
    | '/workforce/rostering/periods'
    | '/workforce/rostering/reports'
    | '/workforce/rostering/requirements'
    | '/workforce/rostering/settings'
    | '/workforce/rostering/templates'
    | '/workforce/rostering/vacant'
    | '/workforce/staff/$staffMemberId'
    | '/maintenance/certificates/$id/edit'
    | '/maintenance/certificates/$id/renew'
    | '/maintenance/contractors/$contractorId/edit'
    | '/maintenance/work-orders/$workOrderId/edit'
  id:
    | '__root__'
    | '/'
    | '/accounts-dashboard'
    | '/alerts'
    | '/assessments'
    | '/audit-logs'
    | '/care-plans'
    | '/compliance'
    | '/daily-notes'
    | '/handovers'
    | '/incidents'
    | '/interventions'
    | '/maintenance'
    | '/mdt-notes'
    | '/operations'
    | '/outings'
    | '/profile'
    | '/quality-governance'
    | '/reports'
    | '/residents'
    | '/risks'
    | '/staff-management'
    | '/tasks'
    | '/training-dashboard'
    | '/visitors'
    | '/vitals'
    | '/assessments/$assessmentId'
    | '/assessments/reassessment'
    | '/charts/$residentId'
    | '/inspection/$residentId'
    | '/maintenance/assets'
    | '/maintenance/certificates'
    | '/maintenance/contractors'
    | '/maintenance/corrective-actions'
    | '/maintenance/housekeeping'
    | '/maintenance/planned-maintenance'
    | '/maintenance/reports'
    | '/maintenance/rooms-locations'
    | '/maintenance/safety-compliance'
    | '/maintenance/settings'
    | '/maintenance/work-orders'
    | '/reports/daily-care'
    | '/residents/$id'
    | '/vitals/audit'
    | '/workforce/agency'
    | '/workforce/competencies'
    | '/workforce/employment'
    | '/workforce/establishment'
    | '/workforce/leave'
    | '/workforce/probation'
    | '/workforce/recruitment'
    | '/workforce/registrations'
    | '/workforce/rostering'
    | '/workforce/staff'
    | '/workforce/training'
    | '/workforce/visa-documents'
    | '/assessments/'
    | '/residents/'
    | '/assessments/new/$residentId'
    | '/maintenance/certificates/$id'
    | '/maintenance/certificates/archived'
    | '/maintenance/certificates/due-soon'
    | '/maintenance/certificates/expired'
    | '/maintenance/certificates/missing'
    | '/maintenance/certificates/new'
    | '/maintenance/certificates/register'
    | '/maintenance/certificates/requirements'
    | '/maintenance/certificates/types'
    | '/maintenance/contractors/$contractorId'
    | '/maintenance/contractors/new'
    | '/maintenance/contractors/register'
    | '/maintenance/work-orders/$workOrderId'
    | '/maintenance/work-orders/new'
    | '/residents/$id/assessments'
    | '/residents/$id/care-plan'
    | '/residents/$id/quality-of-life'
    | '/residents/$id/record'
    | '/residents/$id/timeline'
    | '/workforce/rostering/agency'
    | '/workforce/rostering/availability'
    | '/workforce/rostering/changes'
    | '/workforce/rostering/conflicts'
    | '/workforce/rostering/current'
    | '/workforce/rostering/pending'
    | '/workforce/rostering/periods'
    | '/workforce/rostering/reports'
    | '/workforce/rostering/requirements'
    | '/workforce/rostering/settings'
    | '/workforce/rostering/templates'
    | '/workforce/rostering/vacant'
    | '/workforce/staff/$staffMemberId'
    | '/maintenance/certificates/$id/edit'
    | '/maintenance/certificates/$id/renew'
    | '/maintenance/contractors/$contractorId/edit'
    | '/maintenance/work-orders/$workOrderId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsDashboardRoute: typeof AccountsDashboardRoute
  AlertsRoute: typeof AlertsRoute
  AssessmentsRoute: typeof AssessmentsRouteWithChildren
  AuditLogsRoute: typeof AuditLogsRoute
  CarePlansRoute: typeof CarePlansRoute
  ComplianceRoute: typeof ComplianceRoute
  DailyNotesRoute: typeof DailyNotesRoute
  HandoversRoute: typeof HandoversRoute
  IncidentsRoute: typeof IncidentsRoute
  InterventionsRoute: typeof InterventionsRoute
  MaintenanceRoute: typeof MaintenanceRouteWithChildren
  MdtNotesRoute: typeof MdtNotesRoute
  OperationsRoute: typeof OperationsRoute
  OutingsRoute: typeof OutingsRoute
  ProfileRoute: typeof ProfileRoute
  QualityGovernanceRoute: typeof QualityGovernanceRoute
  ReportsRoute: typeof ReportsRouteWithChildren
  ResidentsRoute: typeof ResidentsRouteWithChildren
  RisksRoute: typeof RisksRoute
  StaffManagementRoute: typeof StaffManagementRoute
  TasksRoute: typeof TasksRoute
  TrainingDashboardRoute: typeof TrainingDashboardRoute
  VisitorsRoute: typeof VisitorsRoute
  VitalsRoute: typeof VitalsRouteWithChildren
  ChartsResidentIdRoute: typeof ChartsResidentIdRoute
  InspectionResidentIdRoute: typeof InspectionResidentIdRoute
  WorkforceAgencyRoute: typeof WorkforceAgencyRoute
  WorkforceCompetenciesRoute: typeof WorkforceCompetenciesRoute
  WorkforceEmploymentRoute: typeof WorkforceEmploymentRoute
  WorkforceEstablishmentRoute: typeof WorkforceEstablishmentRoute
  WorkforceLeaveRoute: typeof WorkforceLeaveRoute
  WorkforceProbationRoute: typeof WorkforceProbationRoute
  WorkforceRecruitmentRoute: typeof WorkforceRecruitmentRoute
  WorkforceRegistrationsRoute: typeof WorkforceRegistrationsRoute
  WorkforceRosteringRoute: typeof WorkforceRosteringRouteWithChildren
  WorkforceStaffRoute: typeof WorkforceStaffRouteWithChildren
  WorkforceTrainingRoute: typeof WorkforceTrainingRoute
  WorkforceVisaDocumentsRoute: typeof WorkforceVisaDocumentsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vitals': {
      id: '/vitals'
      path: '/vitals'
      fullPath: '/vitals'
      preLoaderRoute: typeof VitalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visitors': {
      id: '/visitors'
      path: '/visitors'
      fullPath: '/visitors'
      preLoaderRoute: typeof VisitorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training-dashboard': {
      id: '/training-dashboard'
      path: '/training-dashboard'
      fullPath: '/training-dashboard'
      preLoaderRoute: typeof TrainingDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff-management': {
      id: '/staff-management'
      path: '/staff-management'
      fullPath: '/staff-management'
      preLoaderRoute: typeof StaffManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risks': {
      id: '/risks'
      path: '/risks'
      fullPath: '/risks'
      preLoaderRoute: typeof RisksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/residents': {
      id: '/residents'
      path: '/residents'
      fullPath: '/residents'
      preLoaderRoute: typeof ResidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quality-governance': {
      id: '/quality-governance'
      path: '/quality-governance'
      fullPath: '/quality-governance'
      preLoaderRoute: typeof QualityGovernanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outings': {
      id: '/outings'
      path: '/outings'
      fullPath: '/outings'
      preLoaderRoute: typeof OutingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations': {
      id: '/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof OperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mdt-notes': {
      id: '/mdt-notes'
      path: '/mdt-notes'
      fullPath: '/mdt-notes'
      preLoaderRoute: typeof MdtNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interventions': {
      id: '/interventions'
      path: '/interventions'
      fullPath: '/interventions'
      preLoaderRoute: typeof InterventionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents': {
      id: '/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof IncidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handovers': {
      id: '/handovers'
      path: '/handovers'
      fullPath: '/handovers'
      preLoaderRoute: typeof HandoversRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily-notes': {
      id: '/daily-notes'
      path: '/daily-notes'
      fullPath: '/daily-notes'
      preLoaderRoute: typeof DailyNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/care-plans': {
      id: '/care-plans'
      path: '/care-plans'
      fullPath: '/care-plans'
      preLoaderRoute: typeof CarePlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-logs': {
      id: '/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessments': {
      id: '/assessments'
      path: '/assessments'
      fullPath: '/assessments'
      preLoaderRoute: typeof AssessmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts-dashboard': {
      id: '/accounts-dashboard'
      path: '/accounts-dashboard'
      fullPath: '/accounts-dashboard'
      preLoaderRoute: typeof AccountsDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/residents/': {
      id: '/residents/'
      path: '/'
      fullPath: '/residents/'
      preLoaderRoute: typeof ResidentsIndexRouteImport
      parentRoute: typeof ResidentsRoute
    }
    '/assessments/': {
      id: '/assessments/'
      path: '/'
      fullPath: '/assessments/'
      preLoaderRoute: typeof AssessmentsIndexRouteImport
      parentRoute: typeof AssessmentsRoute
    }
    '/workforce/visa-documents': {
      id: '/workforce/visa-documents'
      path: '/workforce/visa-documents'
      fullPath: '/workforce/visa-documents'
      preLoaderRoute: typeof WorkforceVisaDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workforce/training': {
      id: '/workforce/training'
      path: '/workforce/training'
      fullPath: '/workforce/training'
      preLoaderRoute: typeof WorkforceTrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workforce/staff': {
      id: '/workforce/staff'
      path: '/workforce/staff'
      fullPath: '/workforce/staff'
      preLoaderRoute: typeof WorkforceStaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workforce/rostering': {
      id: '/workforce/rostering'
      path: '/workforce/rostering'
      fullPath: '/workforce/rostering'
      preLoaderRoute: typeof WorkforceRosteringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workforce/registrations': {
      id: '/workforce/registrations'
      path: '/workforce/registrations'
      fullPath: '/workforce/registrations'
      preLoaderRoute: typeof WorkforceRegistrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workforce/recruitment': {
      id: '/workforce/recruitment'
      path: '/workforce/recruitment'
      fullPath: '/workforce/recruitment'
      preLoaderRoute: typeof WorkforceRecruitmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workforce/probation': {
      id: '/workforce/probation'
      path: '/workforce/probation'
      fullPath: '/workforce/probation'
      preLoaderRoute: typeof WorkforceProbationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workforce/leave': {
      id: '/workforce/leave'
      path: '/workforce/leave'
      fullPath: '/workforce/leave'
      preLoaderRoute: typeof WorkforceLeaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workforce/establishment': {
      id: '/workforce/establishment'
      path: '/workforce/establishment'
      fullPath: '/workforce/establishment'
      preLoaderRoute: typeof WorkforceEstablishmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workforce/employment': {
      id: '/workforce/employment'
      path: '/workforce/employment'
      fullPath: '/workforce/employment'
      preLoaderRoute: typeof WorkforceEmploymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workforce/competencies': {
      id: '/workforce/competencies'
      path: '/workforce/competencies'
      fullPath: '/workforce/competencies'
      preLoaderRoute: typeof WorkforceCompetenciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workforce/agency': {
      id: '/workforce/agency'
      path: '/workforce/agency'
      fullPath: '/workforce/agency'
      preLoaderRoute: typeof WorkforceAgencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vitals/audit': {
      id: '/vitals/audit'
      path: '/audit'
      fullPath: '/vitals/audit'
      preLoaderRoute: typeof VitalsAuditRouteImport
      parentRoute: typeof VitalsRoute
    }
    '/residents/$id': {
      id: '/residents/$id'
      path: '/$id'
      fullPath: '/residents/$id'
      preLoaderRoute: typeof ResidentsIdRouteImport
      parentRoute: typeof ResidentsRoute
    }
    '/reports/daily-care': {
      id: '/reports/daily-care'
      path: '/daily-care'
      fullPath: '/reports/daily-care'
      preLoaderRoute: typeof ReportsDailyCareRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/maintenance/work-orders': {
      id: '/maintenance/work-orders'
      path: '/work-orders'
      fullPath: '/maintenance/work-orders'
      preLoaderRoute: typeof MaintenanceWorkOrdersRouteImport
      parentRoute: typeof MaintenanceRoute
    }
    '/maintenance/settings': {
      id: '/maintenance/settings'
      path: '/settings'
      fullPath: '/maintenance/settings'
      preLoaderRoute: typeof MaintenanceSettingsRouteImport
      parentRoute: typeof MaintenanceRoute
    }
    '/maintenance/safety-compliance': {
      id: '/maintenance/safety-compliance'
      path: '/safety-compliance'
      fullPath: '/maintenance/safety-compliance'
      preLoaderRoute: typeof MaintenanceSafetyComplianceRouteImport
      parentRoute: typeof MaintenanceRoute
    }
    '/maintenance/rooms-locations': {
      id: '/maintenance/rooms-locations'
      path: '/rooms-locations'
      fullPath: '/maintenance/rooms-locations'
      preLoaderRoute: typeof MaintenanceRoomsLocationsRouteImport
      parentRoute: typeof MaintenanceRoute
    }
    '/maintenance/reports': {
      id: '/maintenance/reports'
      path: '/reports'
      fullPath: '/maintenance/reports'
      preLoaderRoute: typeof MaintenanceReportsRouteImport
      parentRoute: typeof MaintenanceRoute
    }
    '/maintenance/planned-maintenance': {
      id: '/maintenance/planned-maintenance'
      path: '/planned-maintenance'
      fullPath: '/maintenance/planned-maintenance'
      preLoaderRoute: typeof MaintenancePlannedMaintenanceRouteImport
      parentRoute: typeof MaintenanceRoute
    }
    '/maintenance/housekeeping': {
      id: '/maintenance/housekeeping'
      path: '/housekeeping'
      fullPath: '/maintenance/housekeeping'
      preLoaderRoute: typeof MaintenanceHousekeepingRouteImport
      parentRoute: typeof MaintenanceRoute
    }
    '/maintenance/corrective-actions': {
      id: '/maintenance/corrective-actions'
      path: '/corrective-actions'
      fullPath: '/maintenance/corrective-actions'
      preLoaderRoute: typeof MaintenanceCorrectiveActionsRouteImport
      parentRoute: typeof MaintenanceRoute
    }
    '/maintenance/contractors': {
      id: '/maintenance/contractors'
      path: '/contractors'
      fullPath: '/maintenance/contractors'
      preLoaderRoute: typeof MaintenanceContractorsRouteImport
      parentRoute: typeof MaintenanceRoute
    }
    '/maintenance/certificates': {
      id: '/maintenance/certificates'
      path: '/certificates'
      fullPath: '/maintenance/certificates'
      preLoaderRoute: typeof MaintenanceCertificatesRouteImport
      parentRoute: typeof MaintenanceRoute
    }
    '/maintenance/assets': {
      id: '/maintenance/assets'
      path: '/assets'
      fullPath: '/maintenance/assets'
      preLoaderRoute: typeof MaintenanceAssetsRouteImport
      parentRoute: typeof MaintenanceRoute
    }
    '/inspection/$residentId': {
      id: '/inspection/$residentId'
      path: '/inspection/$residentId'
      fullPath: '/inspection/$residentId'
      preLoaderRoute: typeof InspectionResidentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charts/$residentId': {
      id: '/charts/$residentId'
      path: '/charts/$residentId'
      fullPath: '/charts/$residentId'
      preLoaderRoute: typeof ChartsResidentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessments/reassessment': {
      id: '/assessments/reassessment'
      path: '/reassessment'
      fullPath: '/assessments/reassessment'
      preLoaderRoute: typeof AssessmentsReassessmentRouteImport
      parentRoute: typeof AssessmentsRoute
    }
    '/assessments/$assessmentId': {
      id: '/assessments/$assessmentId'
      path: '/$assessmentId'
      fullPath: '/assessments/$assessmentId'
      preLoaderRoute: typeof AssessmentsAssessmentIdRouteImport
      parentRoute: typeof AssessmentsRoute
    }
    '/workforce/staff/$staffMemberId': {
      id: '/workforce/staff/$staffMemberId'
      path: '/$staffMemberId'
      fullPath: '/workforce/staff/$staffMemberId'
      preLoaderRoute: typeof WorkforceStaffStaffMemberIdRouteImport
      parentRoute: typeof WorkforceStaffRoute
    }
    '/workforce/rostering/vacant': {
      id: '/workforce/rostering/vacant'
      path: '/vacant'
      fullPath: '/workforce/rostering/vacant'
      preLoaderRoute: typeof WorkforceRosteringVacantRouteImport
      parentRoute: typeof WorkforceRosteringRoute
    }
    '/workforce/rostering/templates': {
      id: '/workforce/rostering/templates'
      path: '/templates'
      fullPath: '/workforce/rostering/templates'
      preLoaderRoute: typeof WorkforceRosteringTemplatesRouteImport
      parentRoute: typeof WorkforceRosteringRoute
    }
    '/workforce/rostering/settings': {
      id: '/workforce/rostering/settings'
      path: '/settings'
      fullPath: '/workforce/rostering/settings'
      preLoaderRoute: typeof WorkforceRosteringSettingsRouteImport
      parentRoute: typeof WorkforceRosteringRoute
    }
    '/workforce/rostering/requirements': {
      id: '/workforce/rostering/requirements'
      path: '/requirements'
      fullPath: '/workforce/rostering/requirements'
      preLoaderRoute: typeof WorkforceRosteringRequirementsRouteImport
      parentRoute: typeof WorkforceRosteringRoute
    }
    '/workforce/rostering/reports': {
      id: '/workforce/rostering/reports'
      path: '/reports'
      fullPath: '/workforce/rostering/reports'
      preLoaderRoute: typeof WorkforceRosteringReportsRouteImport
      parentRoute: typeof WorkforceRosteringRoute
    }
    '/workforce/rostering/periods': {
      id: '/workforce/rostering/periods'
      path: '/periods'
      fullPath: '/workforce/rostering/periods'
      preLoaderRoute: typeof WorkforceRosteringPeriodsRouteImport
      parentRoute: typeof WorkforceRosteringRoute
    }
    '/workforce/rostering/pending': {
      id: '/workforce/rostering/pending'
      path: '/pending'
      fullPath: '/workforce/rostering/pending'
      preLoaderRoute: typeof WorkforceRosteringPendingRouteImport
      parentRoute: typeof WorkforceRosteringRoute
    }
    '/workforce/rostering/current': {
      id: '/workforce/rostering/current'
      path: '/current'
      fullPath: '/workforce/rostering/current'
      preLoaderRoute: typeof WorkforceRosteringCurrentRouteImport
      parentRoute: typeof WorkforceRosteringRoute
    }
    '/workforce/rostering/conflicts': {
      id: '/workforce/rostering/conflicts'
      path: '/conflicts'
      fullPath: '/workforce/rostering/conflicts'
      preLoaderRoute: typeof WorkforceRosteringConflictsRouteImport
      parentRoute: typeof WorkforceRosteringRoute
    }
    '/workforce/rostering/changes': {
      id: '/workforce/rostering/changes'
      path: '/changes'
      fullPath: '/workforce/rostering/changes'
      preLoaderRoute: typeof WorkforceRosteringChangesRouteImport
      parentRoute: typeof WorkforceRosteringRoute
    }
    '/workforce/rostering/availability': {
      id: '/workforce/rostering/availability'
      path: '/availability'
      fullPath: '/workforce/rostering/availability'
      preLoaderRoute: typeof WorkforceRosteringAvailabilityRouteImport
      parentRoute: typeof WorkforceRosteringRoute
    }
    '/workforce/rostering/agency': {
      id: '/workforce/rostering/agency'
      path: '/agency'
      fullPath: '/workforce/rostering/agency'
      preLoaderRoute: typeof WorkforceRosteringAgencyRouteImport
      parentRoute: typeof WorkforceRosteringRoute
    }
    '/residents/$id/timeline': {
      id: '/residents/$id/timeline'
      path: '/timeline'
      fullPath: '/residents/$id/timeline'
      preLoaderRoute: typeof ResidentsIdTimelineRouteImport
      parentRoute: typeof ResidentsIdRoute
    }
    '/residents/$id/record': {
      id: '/residents/$id/record'
      path: '/record'
      fullPath: '/residents/$id/record'
      preLoaderRoute: typeof ResidentsIdRecordRouteImport
      parentRoute: typeof ResidentsIdRoute
    }
    '/residents/$id/quality-of-life': {
      id: '/residents/$id/quality-of-life'
      path: '/quality-of-life'
      fullPath: '/residents/$id/quality-of-life'
      preLoaderRoute: typeof ResidentsIdQualityOfLifeRouteImport
      parentRoute: typeof ResidentsIdRoute
    }
    '/residents/$id/care-plan': {
      id: '/residents/$id/care-plan'
      path: '/care-plan'
      fullPath: '/residents/$id/care-plan'
      preLoaderRoute: typeof ResidentsIdCarePlanRouteImport
      parentRoute: typeof ResidentsIdRoute
    }
    '/residents/$id/assessments': {
      id: '/residents/$id/assessments'
      path: '/assessments'
      fullPath: '/residents/$id/assessments'
      preLoaderRoute: typeof ResidentsIdAssessmentsRouteImport
      parentRoute: typeof ResidentsIdRoute
    }
    '/maintenance/work-orders/new': {
      id: '/maintenance/work-orders/new'
      path: '/new'
      fullPath: '/maintenance/work-orders/new'
      preLoaderRoute: typeof MaintenanceWorkOrdersNewRouteImport
      parentRoute: typeof MaintenanceWorkOrdersRoute
    }
    '/maintenance/work-orders/$workOrderId': {
      id: '/maintenance/work-orders/$workOrderId'
      path: '/$workOrderId'
      fullPath: '/maintenance/work-orders/$workOrderId'
      preLoaderRoute: typeof MaintenanceWorkOrdersWorkOrderIdRouteImport
      parentRoute: typeof MaintenanceWorkOrdersRoute
    }
    '/maintenance/contractors/register': {
      id: '/maintenance/contractors/register'
      path: '/register'
      fullPath: '/maintenance/contractors/register'
      preLoaderRoute: typeof MaintenanceContractorsRegisterRouteImport
      parentRoute: typeof MaintenanceContractorsRoute
    }
    '/maintenance/contractors/new': {
      id: '/maintenance/contractors/new'
      path: '/new'
      fullPath: '/maintenance/contractors/new'
      preLoaderRoute: typeof MaintenanceContractorsNewRouteImport
      parentRoute: typeof MaintenanceContractorsRoute
    }
    '/maintenance/contractors/$contractorId': {
      id: '/maintenance/contractors/$contractorId'
      path: '/$contractorId'
      fullPath: '/maintenance/contractors/$contractorId'
      preLoaderRoute: typeof MaintenanceContractorsContractorIdRouteImport
      parentRoute: typeof MaintenanceContractorsRoute
    }
    '/maintenance/certificates/types': {
      id: '/maintenance/certificates/types'
      path: '/types'
      fullPath: '/maintenance/certificates/types'
      preLoaderRoute: typeof MaintenanceCertificatesTypesRouteImport
      parentRoute: typeof MaintenanceCertificatesRoute
    }
    '/maintenance/certificates/requirements': {
      id: '/maintenance/certificates/requirements'
      path: '/requirements'
      fullPath: '/maintenance/certificates/requirements'
      preLoaderRoute: typeof MaintenanceCertificatesRequirementsRouteImport
      parentRoute: typeof MaintenanceCertificatesRoute
    }
    '/maintenance/certificates/register': {
      id: '/maintenance/certificates/register'
      path: '/register'
      fullPath: '/maintenance/certificates/register'
      preLoaderRoute: typeof MaintenanceCertificatesRegisterRouteImport
      parentRoute: typeof MaintenanceCertificatesRoute
    }
    '/maintenance/certificates/new': {
      id: '/maintenance/certificates/new'
      path: '/new'
      fullPath: '/maintenance/certificates/new'
      preLoaderRoute: typeof MaintenanceCertificatesNewRouteImport
      parentRoute: typeof MaintenanceCertificatesRoute
    }
    '/maintenance/certificates/missing': {
      id: '/maintenance/certificates/missing'
      path: '/missing'
      fullPath: '/maintenance/certificates/missing'
      preLoaderRoute: typeof MaintenanceCertificatesMissingRouteImport
      parentRoute: typeof MaintenanceCertificatesRoute
    }
    '/maintenance/certificates/expired': {
      id: '/maintenance/certificates/expired'
      path: '/expired'
      fullPath: '/maintenance/certificates/expired'
      preLoaderRoute: typeof MaintenanceCertificatesExpiredRouteImport
      parentRoute: typeof MaintenanceCertificatesRoute
    }
    '/maintenance/certificates/due-soon': {
      id: '/maintenance/certificates/due-soon'
      path: '/due-soon'
      fullPath: '/maintenance/certificates/due-soon'
      preLoaderRoute: typeof MaintenanceCertificatesDueSoonRouteImport
      parentRoute: typeof MaintenanceCertificatesRoute
    }
    '/maintenance/certificates/archived': {
      id: '/maintenance/certificates/archived'
      path: '/archived'
      fullPath: '/maintenance/certificates/archived'
      preLoaderRoute: typeof MaintenanceCertificatesArchivedRouteImport
      parentRoute: typeof MaintenanceCertificatesRoute
    }
    '/maintenance/certificates/$id': {
      id: '/maintenance/certificates/$id'
      path: '/$id'
      fullPath: '/maintenance/certificates/$id'
      preLoaderRoute: typeof MaintenanceCertificatesIdRouteImport
      parentRoute: typeof MaintenanceCertificatesRoute
    }
    '/assessments/new/$residentId': {
      id: '/assessments/new/$residentId'
      path: '/new/$residentId'
      fullPath: '/assessments/new/$residentId'
      preLoaderRoute: typeof AssessmentsNewResidentIdRouteImport
      parentRoute: typeof AssessmentsRoute
    }
    '/maintenance/work-orders/$workOrderId/edit': {
      id: '/maintenance/work-orders/$workOrderId/edit'
      path: '/edit'
      fullPath: '/maintenance/work-orders/$workOrderId/edit'
      preLoaderRoute: typeof MaintenanceWorkOrdersWorkOrderIdEditRouteImport
      parentRoute: typeof MaintenanceWorkOrdersWorkOrderIdRoute
    }
    '/maintenance/contractors/$contractorId/edit': {
      id: '/maintenance/contractors/$contractorId/edit'
      path: '/edit'
      fullPath: '/maintenance/contractors/$contractorId/edit'
      preLoaderRoute: typeof MaintenanceContractorsContractorIdEditRouteImport
      parentRoute: typeof MaintenanceContractorsContractorIdRoute
    }
    '/maintenance/certificates/$id/renew': {
      id: '/maintenance/certificates/$id/renew'
      path: '/renew'
      fullPath: '/maintenance/certificates/$id/renew'
      preLoaderRoute: typeof MaintenanceCertificatesIdRenewRouteImport
      parentRoute: typeof MaintenanceCertificatesIdRoute
    }
    '/maintenance/certificates/$id/edit': {
      id: '/maintenance/certificates/$id/edit'
      path: '/edit'
      fullPath: '/maintenance/certificates/$id/edit'
      preLoaderRoute: typeof MaintenanceCertificatesIdEditRouteImport
      parentRoute: typeof MaintenanceCertificatesIdRoute
    }
  }
}

interface AssessmentsRouteChildren {
  AssessmentsAssessmentIdRoute: typeof AssessmentsAssessmentIdRoute
  AssessmentsReassessmentRoute: typeof AssessmentsReassessmentRoute
  AssessmentsIndexRoute: typeof AssessmentsIndexRoute
  AssessmentsNewResidentIdRoute: typeof AssessmentsNewResidentIdRoute
}

const AssessmentsRouteChildren: AssessmentsRouteChildren = {
  AssessmentsAssessmentIdRoute: AssessmentsAssessmentIdRoute,
  AssessmentsReassessmentRoute: AssessmentsReassessmentRoute,
  AssessmentsIndexRoute: AssessmentsIndexRoute,
  AssessmentsNewResidentIdRoute: AssessmentsNewResidentIdRoute,
}

const AssessmentsRouteWithChildren = AssessmentsRoute._addFileChildren(
  AssessmentsRouteChildren,
)

interface MaintenanceCertificatesIdRouteChildren {
  MaintenanceCertificatesIdEditRoute: typeof MaintenanceCertificatesIdEditRoute
  MaintenanceCertificatesIdRenewRoute: typeof MaintenanceCertificatesIdRenewRoute
}

const MaintenanceCertificatesIdRouteChildren: MaintenanceCertificatesIdRouteChildren =
  {
    MaintenanceCertificatesIdEditRoute: MaintenanceCertificatesIdEditRoute,
    MaintenanceCertificatesIdRenewRoute: MaintenanceCertificatesIdRenewRoute,
  }

const MaintenanceCertificatesIdRouteWithChildren =
  MaintenanceCertificatesIdRoute._addFileChildren(
    MaintenanceCertificatesIdRouteChildren,
  )

interface MaintenanceCertificatesRouteChildren {
  MaintenanceCertificatesIdRoute: typeof MaintenanceCertificatesIdRouteWithChildren
  MaintenanceCertificatesArchivedRoute: typeof MaintenanceCertificatesArchivedRoute
  MaintenanceCertificatesDueSoonRoute: typeof MaintenanceCertificatesDueSoonRoute
  MaintenanceCertificatesExpiredRoute: typeof MaintenanceCertificatesExpiredRoute
  MaintenanceCertificatesMissingRoute: typeof MaintenanceCertificatesMissingRoute
  MaintenanceCertificatesNewRoute: typeof MaintenanceCertificatesNewRoute
  MaintenanceCertificatesRegisterRoute: typeof MaintenanceCertificatesRegisterRoute
  MaintenanceCertificatesRequirementsRoute: typeof MaintenanceCertificatesRequirementsRoute
  MaintenanceCertificatesTypesRoute: typeof MaintenanceCertificatesTypesRoute
}

const MaintenanceCertificatesRouteChildren: MaintenanceCertificatesRouteChildren =
  {
    MaintenanceCertificatesIdRoute: MaintenanceCertificatesIdRouteWithChildren,
    MaintenanceCertificatesArchivedRoute: MaintenanceCertificatesArchivedRoute,
    MaintenanceCertificatesDueSoonRoute: MaintenanceCertificatesDueSoonRoute,
    MaintenanceCertificatesExpiredRoute: MaintenanceCertificatesExpiredRoute,
    MaintenanceCertificatesMissingRoute: MaintenanceCertificatesMissingRoute,
    MaintenanceCertificatesNewRoute: MaintenanceCertificatesNewRoute,
    MaintenanceCertificatesRegisterRoute: MaintenanceCertificatesRegisterRoute,
    MaintenanceCertificatesRequirementsRoute:
      MaintenanceCertificatesRequirementsRoute,
    MaintenanceCertificatesTypesRoute: MaintenanceCertificatesTypesRoute,
  }

const MaintenanceCertificatesRouteWithChildren =
  MaintenanceCertificatesRoute._addFileChildren(
    MaintenanceCertificatesRouteChildren,
  )

interface MaintenanceContractorsContractorIdRouteChildren {
  MaintenanceContractorsContractorIdEditRoute: typeof MaintenanceContractorsContractorIdEditRoute
}

const MaintenanceContractorsContractorIdRouteChildren: MaintenanceContractorsContractorIdRouteChildren =
  {
    MaintenanceContractorsContractorIdEditRoute:
      MaintenanceContractorsContractorIdEditRoute,
  }

const MaintenanceContractorsContractorIdRouteWithChildren =
  MaintenanceContractorsContractorIdRoute._addFileChildren(
    MaintenanceContractorsContractorIdRouteChildren,
  )

interface MaintenanceContractorsRouteChildren {
  MaintenanceContractorsContractorIdRoute: typeof MaintenanceContractorsContractorIdRouteWithChildren
  MaintenanceContractorsNewRoute: typeof MaintenanceContractorsNewRoute
  MaintenanceContractorsRegisterRoute: typeof MaintenanceContractorsRegisterRoute
}

const MaintenanceContractorsRouteChildren: MaintenanceContractorsRouteChildren =
  {
    MaintenanceContractorsContractorIdRoute:
      MaintenanceContractorsContractorIdRouteWithChildren,
    MaintenanceContractorsNewRoute: MaintenanceContractorsNewRoute,
    MaintenanceContractorsRegisterRoute: MaintenanceContractorsRegisterRoute,
  }

const MaintenanceContractorsRouteWithChildren =
  MaintenanceContractorsRoute._addFileChildren(
    MaintenanceContractorsRouteChildren,
  )

interface MaintenanceWorkOrdersWorkOrderIdRouteChildren {
  MaintenanceWorkOrdersWorkOrderIdEditRoute: typeof MaintenanceWorkOrdersWorkOrderIdEditRoute
}

const MaintenanceWorkOrdersWorkOrderIdRouteChildren: MaintenanceWorkOrdersWorkOrderIdRouteChildren =
  {
    MaintenanceWorkOrdersWorkOrderIdEditRoute:
      MaintenanceWorkOrdersWorkOrderIdEditRoute,
  }

const MaintenanceWorkOrdersWorkOrderIdRouteWithChildren =
  MaintenanceWorkOrdersWorkOrderIdRoute._addFileChildren(
    MaintenanceWorkOrdersWorkOrderIdRouteChildren,
  )

interface MaintenanceWorkOrdersRouteChildren {
  MaintenanceWorkOrdersWorkOrderIdRoute: typeof MaintenanceWorkOrdersWorkOrderIdRouteWithChildren
  MaintenanceWorkOrdersNewRoute: typeof MaintenanceWorkOrdersNewRoute
}

const MaintenanceWorkOrdersRouteChildren: MaintenanceWorkOrdersRouteChildren = {
  MaintenanceWorkOrdersWorkOrderIdRoute:
    MaintenanceWorkOrdersWorkOrderIdRouteWithChildren,
  MaintenanceWorkOrdersNewRoute: MaintenanceWorkOrdersNewRoute,
}

const MaintenanceWorkOrdersRouteWithChildren =
  MaintenanceWorkOrdersRoute._addFileChildren(
    MaintenanceWorkOrdersRouteChildren,
  )

interface MaintenanceRouteChildren {
  MaintenanceAssetsRoute: typeof MaintenanceAssetsRoute
  MaintenanceCertificatesRoute: typeof MaintenanceCertificatesRouteWithChildren
  MaintenanceContractorsRoute: typeof MaintenanceContractorsRouteWithChildren
  MaintenanceCorrectiveActionsRoute: typeof MaintenanceCorrectiveActionsRoute
  MaintenanceHousekeepingRoute: typeof MaintenanceHousekeepingRoute
  MaintenancePlannedMaintenanceRoute: typeof MaintenancePlannedMaintenanceRoute
  MaintenanceReportsRoute: typeof MaintenanceReportsRoute
  MaintenanceRoomsLocationsRoute: typeof MaintenanceRoomsLocationsRoute
  MaintenanceSafetyComplianceRoute: typeof MaintenanceSafetyComplianceRoute
  MaintenanceSettingsRoute: typeof MaintenanceSettingsRoute
  MaintenanceWorkOrdersRoute: typeof MaintenanceWorkOrdersRouteWithChildren
}

const MaintenanceRouteChildren: MaintenanceRouteChildren = {
  MaintenanceAssetsRoute: MaintenanceAssetsRoute,
  MaintenanceCertificatesRoute: MaintenanceCertificatesRouteWithChildren,
  MaintenanceContractorsRoute: MaintenanceContractorsRouteWithChildren,
  MaintenanceCorrectiveActionsRoute: MaintenanceCorrectiveActionsRoute,
  MaintenanceHousekeepingRoute: MaintenanceHousekeepingRoute,
  MaintenancePlannedMaintenanceRoute: MaintenancePlannedMaintenanceRoute,
  MaintenanceReportsRoute: MaintenanceReportsRoute,
  MaintenanceRoomsLocationsRoute: MaintenanceRoomsLocationsRoute,
  MaintenanceSafetyComplianceRoute: MaintenanceSafetyComplianceRoute,
  MaintenanceSettingsRoute: MaintenanceSettingsRoute,
  MaintenanceWorkOrdersRoute: MaintenanceWorkOrdersRouteWithChildren,
}

const MaintenanceRouteWithChildren = MaintenanceRoute._addFileChildren(
  MaintenanceRouteChildren,
)

interface ReportsRouteChildren {
  ReportsDailyCareRoute: typeof ReportsDailyCareRoute
}

const ReportsRouteChildren: ReportsRouteChildren = {
  ReportsDailyCareRoute: ReportsDailyCareRoute,
}

const ReportsRouteWithChildren =
  ReportsRoute._addFileChildren(ReportsRouteChildren)

interface ResidentsIdRouteChildren {
  ResidentsIdAssessmentsRoute: typeof ResidentsIdAssessmentsRoute
  ResidentsIdCarePlanRoute: typeof ResidentsIdCarePlanRoute
  ResidentsIdQualityOfLifeRoute: typeof ResidentsIdQualityOfLifeRoute
  ResidentsIdRecordRoute: typeof ResidentsIdRecordRoute
  ResidentsIdTimelineRoute: typeof ResidentsIdTimelineRoute
}

const ResidentsIdRouteChildren: ResidentsIdRouteChildren = {
  ResidentsIdAssessmentsRoute: ResidentsIdAssessmentsRoute,
  ResidentsIdCarePlanRoute: ResidentsIdCarePlanRoute,
  ResidentsIdQualityOfLifeRoute: ResidentsIdQualityOfLifeRoute,
  ResidentsIdRecordRoute: ResidentsIdRecordRoute,
  ResidentsIdTimelineRoute: ResidentsIdTimelineRoute,
}

const ResidentsIdRouteWithChildren = ResidentsIdRoute._addFileChildren(
  ResidentsIdRouteChildren,
)

interface ResidentsRouteChildren {
  ResidentsIdRoute: typeof ResidentsIdRouteWithChildren
  ResidentsIndexRoute: typeof ResidentsIndexRoute
}

const ResidentsRouteChildren: ResidentsRouteChildren = {
  ResidentsIdRoute: ResidentsIdRouteWithChildren,
  ResidentsIndexRoute: ResidentsIndexRoute,
}

const ResidentsRouteWithChildren = ResidentsRoute._addFileChildren(
  ResidentsRouteChildren,
)

interface VitalsRouteChildren {
  VitalsAuditRoute: typeof VitalsAuditRoute
}

const VitalsRouteChildren: VitalsRouteChildren = {
  VitalsAuditRoute: VitalsAuditRoute,
}

const VitalsRouteWithChildren =
  VitalsRoute._addFileChildren(VitalsRouteChildren)

interface WorkforceRosteringRouteChildren {
  WorkforceRosteringAgencyRoute: typeof WorkforceRosteringAgencyRoute
  WorkforceRosteringAvailabilityRoute: typeof WorkforceRosteringAvailabilityRoute
  WorkforceRosteringChangesRoute: typeof WorkforceRosteringChangesRoute
  WorkforceRosteringConflictsRoute: typeof WorkforceRosteringConflictsRoute
  WorkforceRosteringCurrentRoute: typeof WorkforceRosteringCurrentRoute
  WorkforceRosteringPendingRoute: typeof WorkforceRosteringPendingRoute
  WorkforceRosteringPeriodsRoute: typeof WorkforceRosteringPeriodsRoute
  WorkforceRosteringReportsRoute: typeof WorkforceRosteringReportsRoute
  WorkforceRosteringRequirementsRoute: typeof WorkforceRosteringRequirementsRoute
  WorkforceRosteringSettingsRoute: typeof WorkforceRosteringSettingsRoute
  WorkforceRosteringTemplatesRoute: typeof WorkforceRosteringTemplatesRoute
  WorkforceRosteringVacantRoute: typeof WorkforceRosteringVacantRoute
}

const WorkforceRosteringRouteChildren: WorkforceRosteringRouteChildren = {
  WorkforceRosteringAgencyRoute: WorkforceRosteringAgencyRoute,
  WorkforceRosteringAvailabilityRoute: WorkforceRosteringAvailabilityRoute,
  WorkforceRosteringChangesRoute: WorkforceRosteringChangesRoute,
  WorkforceRosteringConflictsRoute: WorkforceRosteringConflictsRoute,
  WorkforceRosteringCurrentRoute: WorkforceRosteringCurrentRoute,
  WorkforceRosteringPendingRoute: WorkforceRosteringPendingRoute,
  WorkforceRosteringPeriodsRoute: WorkforceRosteringPeriodsRoute,
  WorkforceRosteringReportsRoute: WorkforceRosteringReportsRoute,
  WorkforceRosteringRequirementsRoute: WorkforceRosteringRequirementsRoute,
  WorkforceRosteringSettingsRoute: WorkforceRosteringSettingsRoute,
  WorkforceRosteringTemplatesRoute: WorkforceRosteringTemplatesRoute,
  WorkforceRosteringVacantRoute: WorkforceRosteringVacantRoute,
}

const WorkforceRosteringRouteWithChildren =
  WorkforceRosteringRoute._addFileChildren(WorkforceRosteringRouteChildren)

interface WorkforceStaffRouteChildren {
  WorkforceStaffStaffMemberIdRoute: typeof WorkforceStaffStaffMemberIdRoute
}

const WorkforceStaffRouteChildren: WorkforceStaffRouteChildren = {
  WorkforceStaffStaffMemberIdRoute: WorkforceStaffStaffMemberIdRoute,
}

const WorkforceStaffRouteWithChildren = WorkforceStaffRoute._addFileChildren(
  WorkforceStaffRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsDashboardRoute: AccountsDashboardRoute,
  AlertsRoute: AlertsRoute,
  AssessmentsRoute: AssessmentsRouteWithChildren,
  AuditLogsRoute: AuditLogsRoute,
  CarePlansRoute: CarePlansRoute,
  ComplianceRoute: ComplianceRoute,
  DailyNotesRoute: DailyNotesRoute,
  HandoversRoute: HandoversRoute,
  IncidentsRoute: IncidentsRoute,
  InterventionsRoute: InterventionsRoute,
  MaintenanceRoute: MaintenanceRouteWithChildren,
  MdtNotesRoute: MdtNotesRoute,
  OperationsRoute: OperationsRoute,
  OutingsRoute: OutingsRoute,
  ProfileRoute: ProfileRoute,
  QualityGovernanceRoute: QualityGovernanceRoute,
  ReportsRoute: ReportsRouteWithChildren,
  ResidentsRoute: ResidentsRouteWithChildren,
  RisksRoute: RisksRoute,
  StaffManagementRoute: StaffManagementRoute,
  TasksRoute: TasksRoute,
  TrainingDashboardRoute: TrainingDashboardRoute,
  VisitorsRoute: VisitorsRoute,
  VitalsRoute: VitalsRouteWithChildren,
  ChartsResidentIdRoute: ChartsResidentIdRoute,
  InspectionResidentIdRoute: InspectionResidentIdRoute,
  WorkforceAgencyRoute: WorkforceAgencyRoute,
  WorkforceCompetenciesRoute: WorkforceCompetenciesRoute,
  WorkforceEmploymentRoute: WorkforceEmploymentRoute,
  WorkforceEstablishmentRoute: WorkforceEstablishmentRoute,
  WorkforceLeaveRoute: WorkforceLeaveRoute,
  WorkforceProbationRoute: WorkforceProbationRoute,
  WorkforceRecruitmentRoute: WorkforceRecruitmentRoute,
  WorkforceRegistrationsRoute: WorkforceRegistrationsRoute,
  WorkforceRosteringRoute: WorkforceRosteringRouteWithChildren,
  WorkforceStaffRoute: WorkforceStaffRouteWithChildren,
  WorkforceTrainingRoute: WorkforceTrainingRoute,
  WorkforceVisaDocumentsRoute: WorkforceVisaDocumentsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
